CREATE TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_TRIGGER](
	[SURVEY_AUTOMATION_SERVICE_TRIGGER_ID] [int] NOT NULL,
	[FILE_NAME] [varchar](max) NULL,
	[IS_SMS] [bit] NULL,
	[IS_EMAIL] [bit] NULL,
	[PRACTICE_CODE] [int] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [nvarchar](255) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [nvarchar](255) NULL,
	[DELETED] [bit] NULL,
	[IN_PROGRESS] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[SURVEY_AUTOMATION_SERVICE_TRIGGER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_TRIGGER] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_TRIGGER] ADD  DEFAULT ('FOX_SERVICE') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_TRIGGER] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_TRIGGER] ADD  DEFAULT ('FOX_SERVICE') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUTOMATION_SERVICE_TRIGGER] ADD  DEFAULT ((0)) FOR [DELETED]
GO


