USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_ORDER_INFORMATION]    Script Date: 7/21/2022 9:09:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_ORDER_INFORMATION](
	[ORDER_INFO_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CASE_ID] [bigint] NULL,
	[ORDER_STATUS_ID] [int] NULL,
	[CASE_TYPE_ID] [int] NULL,
	[PRESC_PROVIDER_ID_old] [bigint] NULL,
	[EFFECTIVE_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[VISIT_PER_WEEK] [int] NULL,
	[NO_OF_WEEK] [int] NULL,
	[TOTAL_VISITS]  AS ([VISIT_PER_WEEK]*[NO_OF_WEEK]),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_ORDER_INFORMATION_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_ORDER_INFORMATION_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_ORDER_INFORMATION_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_ORDER_INFORMATION_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_ORDER_INFORMATION_DELETED]  DEFAULT ((0)),
	[PRESC_PROVIDER_ID] [bigint] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_EF960954C22F46308453917EA8DC162F]  DEFAULT (newsequentialid()),
	[FOX_GUID] [varchar](50) NULL,
 CONSTRAINT [PK_FOX_TBL_ORDER_INFORMATIO] PRIMARY KEY CLUSTERED 
(
	[ORDER_INFO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


