USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_USER_TEAMS]    Script Date: 8/15/2022 11:41:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOX_TBL_USER_TEAMS](
	[USER_TEAM_ID] [bigint] NOT NULL,
	[USER_ID] [bigint] NULL,
	[PHD_CALL_SCENARIO_ID] [bigint] NULL,
	[PRACTICE_CODE] [varchar](255) NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK__FOX_TBL___4B661FFF203F3615] PRIMARY KEY CLUSTERED 
(
	[USER_TEAM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_USER_TEAMS] ADD  CONSTRAINT [DF__FOX_TBL_A__CREAT__49262C61]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_USER_TEAMS] ADD  CONSTRAINT [DF__FOX_TBL_A__CREAT__4A1A509A]  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_USER_TEAMS] ADD  CONSTRAINT [DF__FOX_TBL_A__MODIF__4B0E74D3]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_USER_TEAMS] ADD  CONSTRAINT [DF__FOX_TBL_A__MODIF__4C02990C]  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_USER_TEAMS] ADD  CONSTRAINT [DF__FOX_TBL_A__DELET__4CF6BD45]  DEFAULT ((0)) FOR [DELETED]
GO


