USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_WORK_ORDER_HISTORY]    Script Date: 7/21/2022 9:40:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_WORK_ORDER_HISTORY](
	[LOG_ID] [bigint] NOT NULL,
	[WORK_ID] [bigint] NOT NULL,
	[UNIQUE_ID] [varchar](50) NULL,
	[LOG_MESSAGE] [varchar](500) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_WORK_ORDER_HISTORY_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_ON] [datetime] NOT NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_D14B3DA77A7E435FA8CA886578DD8BCF]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK__FOX_TBL___4364C8826AEBC166] PRIMARY KEY CLUSTERED 
(
	[LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


