USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PROVIDER]    Script Date: 7/21/2022 9:27:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PROVIDER](
	[FOX_PROVIDER_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[REGION_CODE] [varchar](10) NULL,
	[REGION_NAME] [varchar](50) NULL,
	[PROVIDER_CODE] [bigint] NULL,
	[FOX_PROVIDER_CODE] [varchar](10) NULL,
	[PROVIDER_NAME] [varchar](100) NULL,
	[CONTRACTED_QUOTA] [varchar](10) NULL,
	[STATUS] [varchar](50) NULL,
	[EMPLOYEE_ID] [varchar](10) NULL,
	[ASHA_ID] [varchar](10) NULL,
	[UBER] [varchar](1) NULL,
	[CONTRACT] [varchar](1) NULL,
	[HOT_SYNC_ENABLED] [varchar](1) NULL,
	[HOT_SYNC_AUTO_LOCK] [varchar](1) NULL,
	[LAST_LOGIN] [varchar](10) NULL,
	[LAST_LOGIN_DATE] [datetime] NULL,
	[PROGRAM] [varchar](10) NULL,
	[FIRST_NAME] [varchar](50) NULL,
	[LAST_NAME] [varchar](50) NULL,
	[MI] [varchar](1) NULL,
	[ADDRESS] [varchar](500) NULL,
	[CITY] [varchar](50) NULL,
	[STATE] [varchar](2) NULL,
	[ZIP] [varchar](9) NULL,
	[PHONE] [varchar](10) NULL,
	[FAX] [varchar](10) NULL,
	[EMAIL] [varchar](255) NULL,
	[INDIVIDUAL_NPI] [varchar](10) NULL,
	[GROUP_NPI] [varchar](10) NULL,
	[LICENSE_NO] [varchar](15) NULL,
	[TAX_ID] [varchar](9) NULL,
	[TAXONOMY_CODE] [varchar](30) NULL,
	[GROUP_TAXONOMY_CODE] [varchar](30) NULL,
	[HOLD_BILLING_UNTIL_DOS] [datetime] NULL,
	[SSN] [varchar](9) NULL,
	[REFERRAL_REGION_ID] [bigint] NULL,
	[IS_INACTIVE] [bit] NULL CONSTRAINT [DF_FOX_TBL_PROVIDER_IS_INACTIVE_1]  DEFAULT ((0)),
	[DISCIPLINE_ID] [int] NULL,
	[TREATMENT_LOC_ID] [bigint] NULL,
	[PRIMARY_POS_DISTANCE] [int] NULL,
	[VISIT_QOUTA_WEEK_ID] [int] NULL,
	[ACTIVE_CASES] [int] NULL,
	[PTO_HRS] [int] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PROVIDER_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL CONSTRAINT [DF_FOX_TBL_PROVIDER_3_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PROVIDER_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL CONSTRAINT [DF_FOX_TBL_PROVIDER_3_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NULL CONSTRAINT [DF_FOX_TBL_PROVIDER_3_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_0C5CB64A5C114F4999EE338119060E83]  DEFAULT (newsequentialid()),
	[PROFILE_PICTURE] [varchar](200) NULL,
	[LATITUDE] [varchar](50) NULL,
	[LONGITUDE] [varchar](50) NULL,
	[IS_FACILITY] [bit] NULL,
	[IS_POINT_ON_MAP] [bit] NULL,
	[CLR] [money] NULL,
 CONSTRAINT [PK_FOX_TBL_PROVIDER] PRIMARY KEY CLUSTERED 
(
	[FOX_PROVIDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


