USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_SURVEY_AUDIT_SCORES]    Script Date: 7/21/2022 10:00:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_SURVEY_AUDIT_SCORES](
	[SURVEY_AUDIT_SCORES_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[SURVEY_CALL_ID] [bigint] NULL,
	[SURVEY_ID] [bigint] NULL,
	[GREETINGS] [bigint] NULL,
	[CALL_HANDLING_SKILLS] [bigint] NULL,
	[GRAMMER_PRONOUNCIATION_VOCABULARY] [bigint] NULL,
	[CLIENT_EXPERIENCE_TOTAL] [bigint] NULL,
	[CLIENT_EXPERIENCE_COMMENT] [varchar](1000) NULL,
	[VERIFIED_PATIENT_ACCOUNT] [bigint] NULL,
	[ACCOUNT_AND_SCRIPT_READINESS] [bigint] NULL,
	[PATIENT_VERIFICATION_AND_INSURANCE] [bigint] NULL,
	[CASE_HANDLING] [bigint] NULL,
	[EMAIL_TO_STAKE_HOLDERS] [bigint] NULL,
	[ESCALATION] [bigint] NULL,
	[SYSTEM_PROCESS_TOTAL] [bigint] NULL,
	[SYSTEM_PROCESS_COMMENT] [varchar](1000) NULL,
	[BONUS_POINTS] [int] NULL,
	[PERFORMANCE_KILLER] [int] NULL,
	[WOW_FACTOR_COMMENT] [varchar](1000) NULL,
	[TOTAL_POINTS] [int] NULL,
	[AUDITOR_NAME] [varchar](255) NULL,
	[AGENT_NAME] [varchar](255) NULL,
	[CREATED_BY] [varchar](255) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](255) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
	[GRADE] [varchar](1) NULL,
	[GREETINGS_TOTAL] [bigint] NULL,
	[CALL_HANDLING_SKILLS_TOTAL] [bigint] NULL,
	[GRAMMER_PRONOUNCIATION_VOCABULARY_TOTAL] [bigint] NULL,
	[VERIFIED_PATIENT_ACCOUNT_TOTAL] [bigint] NULL,
	[ACCOUNT_AND_SCRIPT_READINESS_TOTAL] [bigint] NULL,
	[CASE_HANDLING_TOTAL] [bigint] NULL,
	[EMAIL_TO_STAKE_HOLDERS_TOTAL] [bigint] NULL,
	[ESCALATION_TOTAL] [bigint] NULL,
	[BONUS_POINTS_TOTAL] [bigint] NULL,
	[PERFORMANCE_KILLER_TOTAL] [bigint] NULL,
	[PHD_CALL_ID] [bigint] NULL,
	[CALL_TYPE] [varchar](20) NULL,
	[PRODUCT_KNOWLEDGE] [bigint] NULL,
	[CORRECT_NOTES_AND_TRACKING] [bigint] NULL,
	[PRODUCT_KNOWLEDGE_TOTAL] [bigint] NULL,
	[CORRECT_NOTES_AND_TRACKING_TOTAL] [bigint] NULL,
	[PHD_CALL_SCENARIO_ID] [int] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[DOCUMENTED_DATE_TIME] [bigint] NULL,
	[DOCUMENTED_RELEVANT_DETAILS] [bigint] NULL,
	[MARKED_QUSTIONS_CORRECTLY] [bigint] NULL,
	[MARKED_SURVEY_STATUS] [bigint] NULL,
	[CORRECTLY_IDENTIFY_FLAG] [bigint] NULL,
	[CORRECTLY_SEPARATE_QUESTION] [bigint] NULL,
	[FOLLOWED_SCRIPTED_SURVEY] [bigint] NULL,
	[FOLLOWED_CLOSING_SCRIPT] [bigint] NULL,
	[DOCUMENTED_DATE_TIME_TOTAL] [bigint] NULL,
	[DOCUMENTED_RELEVANT_DETAILS_TOTAL] [bigint] NULL,
	[MARKED_QUSTIONS_CORRECTLY_TOTAL] [bigint] NULL,
	[MARKED_SURVEY_STATUS_TOTAL] [bigint] NULL,
	[CORRECTLY_IDENTIFY_FLAG_TOTAL] [bigint] NULL,
	[CORRECTLY_SEPARATE_QUESTION_TOTAL] [bigint] NULL,
	[FOLLOWED_SCRIPTED_SURVEY_TOTAL] [bigint] NULL,
	[FOLLOWED_CLOSING_SCRIPT_TOTAL] [bigint] NULL,
	[SCORING_CRITERIA] [varchar](10) NULL,
	[APPROPRIATE_GREETING] [bigint] NULL,
	[APPROPRIATE_GREETING_TOTAL] [bigint] NULL,
	[TONE_OF_PATIENT] [bigint] NULL,
	[TONE_OF_PATIENT_TOTAL] [bigint] NULL,
	[COMPASSION_AND_EMPATHY] [bigint] NULL,
	[COMPASSION_AND_EMPATHY_TOTAL] [bigint] NULL,
	[GRAMMAR_AND_PRONUNCIATION] [bigint] NULL,
	[GRAMMAR_AND_PRONUNCIATION_TOTAL] [bigint] NULL,
	[PATIENT_IDENTITY] [bigint] NULL,
	[PATIENT_IDENTITY_TOTAL] [bigint] NULL,
	[ANSWER_PATIENT_QUESTIONS] [bigint] NULL,
	[ANSWER_PATIENT_QUESTIONS_TOTAL] [bigint] NULL,
	[STRONG_PRODUCT_KNOWLEDGE] [bigint] NULL,
	[STRONG_PRODUCT_KNOWLEDGE_TOTAL] [bigint] NULL,
	[COMMUNICATE_INFORMATION] [bigint] NULL,
	[COMMUNICATE_INFORMATION_TOTAL] [bigint] NULL,
	[DOCUMENTATION_COMPLETED_COMMUNICATED] [bigint] NULL,
	[DOCUMENTATION_COMPLETED_COMMUNICATED_TOTAL] [bigint] NULL,
	[APPROPRIATE_CLOSING] [bigint] NULL,
	[APPROPRIATE_CLOSING_TOTAL] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[SURVEY_AUDIT_SCORES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUDIT_SCORES] ADD  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUDIT_SCORES] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUDIT_SCORES] ADD  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUDIT_SCORES] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_SURVEY_AUDIT_SCORES] ADD  DEFAULT ((0)) FOR [DELETED]
GO


