USE [MIS_DB]
GO

CREATE TABLE [dbo].[FOX_TBL_AUTOMATED_SURVEY_UNSUBSCRIPTION](
	[AUTOMATED_SURVEY_UNSUBSCRIPTION_ID] [bigint] NOT NULL,
	[SURVEY_ID] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[SMS_UNSUBSCRIBE] [bit] NULL,
	[EMAIL_UNSUBSCRIBE] [bit] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTOMATED_SURVEY_UNSUBSCRIPTION] ADD  DEFAULT ((0)) FOR [SMS_UNSUBSCRIBE]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTOMATED_SURVEY_UNSUBSCRIPTION] ADD  DEFAULT ((0)) FOR [EMAIL_UNSUBSCRIBE]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTOMATED_SURVEY_UNSUBSCRIPTION] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTOMATED_SURVEY_UNSUBSCRIPTION] ADD  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTOMATED_SURVEY_UNSUBSCRIPTION] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTOMATED_SURVEY_UNSUBSCRIPTION] ADD  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTOMATED_SURVEY_UNSUBSCRIPTION] ADD  DEFAULT ((0)) FOR [DELETED]
GO