USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_DASHBOARD_ACCESS]    Script Date: 7/21/2022 9:50:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_DASHBOARD_ACCESS](
	[DASHBOARD_ACCESS_ID] [bigint] NOT NULL,
	[USER_NAME] [varchar](70) NULL,
	[SHOW_AS_ROLE] [bigint] NULL,
	[REFERRAL_REGION_ID] [bigint] NULL,
	[IS_WRITE_ALLOWDED] [bit] NULL CONSTRAINT [DF_FOX_TBL_DASHBOARD_ACCESSdas_IS_WRITE_ALLOWDED]  DEFAULT ((0)),
	[DELETED] [bit] NULL CONSTRAINT [DF_FOX_TBL_DASHBOARD_ACCESSdas_DELETED]  DEFAULT ((0)),
	[CREATED_BY] [varchar](70) NULL CONSTRAINT [DF_FOX_TBL_DASHBOARD_ACCESSdas_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_ON] [datetime] NULL CONSTRAINT [DF_FOX_TBL_DASHBOARD_ACCESSdas_CREATED_ON]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NULL CONSTRAINT [DF_FOX_TBL_DASHBOARD_ACCESSdas_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL CONSTRAINT [DF_FOX_TBL_DASHBOARD_ACCESSdas_MODIFIED_DATE]  DEFAULT (getdate()),
 CONSTRAINT [PK_FOX_TBL_DASHBOARD_ACCESSdas] PRIMARY KEY CLUSTERED 
(
	[DASHBOARD_ACCESS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


