USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_REFERRAL_SOURCE_INACTIVE_REASON]    Script Date: 7/21/2022 9:32:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_REFERRAL_SOURCE_INACTIVE_REASON](
	[INACTIVE_REASON_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[REASON] [varchar](100) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_REFERRAL_SOURCE_INACTIVE_REASON_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_REFERRAL_SOURCE_INACTIVE_REASON_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_REFERRAL_SOURCE_INACTIVE_REASON_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_REFERRAL_SOURCE_INACTIVE_REASON_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_REFERRAL_SOURCE_INACTIVE_REASON_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_70527DA152434E7098E18EF7AD01BB73]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_REFERRAL_SOURCE_INACTIVE_REASON] PRIMARY KEY CLUSTERED 
(
	[INACTIVE_REASON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


