USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_SOURCE_OF_REFERRAL]    Script Date: 7/21/2022 9:35:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_SOURCE_OF_REFERRAL](
	[SOURCE_OF_REFERRAL_ID] [int] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CODE] [varchar](10) NULL,
	[DESCRIPTION] [varchar](300) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_SOURCE_OF_REFERRAL_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_SOURCE_OF_REFERRAL_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_SOURCE_OF_REFERRAL_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_SOURCE_OF_REFERRAL_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_SOURCE_OF_REFERRAL_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_6E5AA34E6C664EE991F6B91777552391]  DEFAULT (newsequentialid()),
	[END_DATE] [datetime] NULL,
	[IS_ACTIVE] [bit] NULL,
	[START_DATE] [datetime] NULL,
 CONSTRAINT [PK_FOX_TBL_SOURCE_OF_REFERRAL] PRIMARY KEY CLUSTERED 
(
	[SOURCE_OF_REFERRAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


