USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PR_PERIOD]    Script Date: 7/21/2022 9:25:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PR_PERIOD](
	[PR_PERIOD_ID] [int] NOT NULL,
	[PERIOD_DESCRIPTION] [varchar](50) NOT NULL,
	[PRACTICE_CODE] [bigint] NOT NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PR_PERIOD_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PR_PERIOD_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PR_PERIOD_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PR_PERIOD_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PR_PERIOD_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_9E0922DB72EE4EBD80A369D61EF109B7]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_PR_PERIOD] PRIMARY KEY CLUSTERED 
(
	[PR_PERIOD_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


