USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_FAX_SERVICE_CONFIG]    Script Date: 7/21/2022 8:55:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_FAX_SERVICE_CONFIG](
	[FOXREHAB_CONFIG_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[EMERGENCY_EMAIL] [varchar](50) NULL,
	[ENVIRONMENT_EMAIL] [varchar](50) NULL,
	[FAX_ID] [varchar](50) NULL,
	[FAX_USERNAME] [varchar](50) NULL,
	[FAX_PASSWORD] [varchar](50) NULL,
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_F__DELET__17B8F22E]  DEFAULT ((0)),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_FAX_SERVICE_CONFIG_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_FAX_SERVICE_CONFIG_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_FAX_SERVICE_CONFIG_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_FAX_SERVICE_CONFIG_MODIFIED_DATE]  DEFAULT (getdate()),
	[EMAIL_PASSWORD] [varchar](50) NULL,
	[EMAIL_USERNAME] [varchar](50) NULL,
	[ENVIRONMENT_NAME] [varchar](200) NULL,
	[LOAD_FAXES] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_F__LOAD___18AD1667]  DEFAULT ((0)),
	[LOAD_EMAILS] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_F__LOAD___19A13AA0]  DEFAULT ((0)),
	[DIR_PATH_DB] [varchar](500) NULL,
	[DIR_PATH_SERVER] [varchar](500) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_25CDE312B52048638BBFF100B87818F6]  DEFAULT (newsequentialid()),
	[IS_DIRECT_MAIL] [bit] NULL CONSTRAINT [DF__FOX_TBL_F__IS_DI__6E436DCE]  DEFAULT ((0)),
 CONSTRAINT [PK__FOX_TBL___BE5C9BC19F94E5D5] PRIMARY KEY CLUSTERED 
(
	[FOXREHAB_CONFIG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


