USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_CORRECTED_CLAIM]    Script Date: 7/21/2022 8:52:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_CORRECTED_CLAIM](
	[CORRECTED_CLAIM_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[CHART_ID] [varchar](100) NULL,
	[CHARGE_ENTRY_DATE] [datetime] NULL,
	[CASE_NO] [varchar](50) NULL,
	[FOX_TBL_INSURANCE_ID] [bigint] NULL,
	[DOS_FROM] [datetime] NULL,
	[DOS_TO] [datetime] NULL,
	[SOURCE_ID_old] [bigint] NULL,
	[REQUESTED_BY] [varchar](70) NULL,
	[REQUESTED_DATE] [datetime] NULL,
	[WORK_DATE] [datetime] NULL,
	[STATUS_ID] [int] NULL,
	[REMARKS] [varchar](3000) NULL,
	[RESPONSE] [varchar](3000) NULL,
	[RESPONSE_BY] [varchar](70) NULL,
	[CORRECTED_CLAIM_TYPE_ID] [int] NULL,
	[RESPONSE_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_CORRECTED_CLAIM_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_C__CREAT__64394E28]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_CORRECTED_CLAIM_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_C__MODIF__6621969A]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_C__DELET__6715BAD3]  DEFAULT ((0)),
	[SOURCE_ID] [bigint] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_A7B4E1254A5C43AEB05A9B1573A59908]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK__FOX_TBL___22F75A22C2275A29] PRIMARY KEY CLUSTERED 
(
	[CORRECTED_CLAIM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


