USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PRACTICE_ROLE_RIGHTS]    Script Date: 7/21/2022 9:26:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PRACTICE_ROLE_RIGHTS](
	[RIGHTS_OF_ROLE_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NOT NULL,
	[CHECKED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_P__CHECK__6893EEF1]  DEFAULT ((0)),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PRACTICE_ROLE_RIGHTS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_P__CREAT__6A7C3763]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PRACTICE_ROLE_RIGHTS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_P__MODIF__6C647FD5]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_P__DELET__6D58A40E]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_2C08F40CE1E541988BB62B26CF0FEAF0]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK__FOX_TBL___3B0F25A8DB9C5C87] PRIMARY KEY CLUSTERED 
(
	[RIGHTS_OF_ROLE_ID] ASC,
	[PRACTICE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


