USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_GROUP]    Script Date: 7/21/2022 9:01:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_GROUP](
	[GROUP_ID] [bigint] NOT NULL,
	[GROUP_NAME] [varchar](100) NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_GROUP_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL CONSTRAINT [DF_FOX_TBL_USERS_GROUP_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_GROUP_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL CONSTRAINT [DF_FOX_TBL_USERS_GROUP_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NULL CONSTRAINT [DF_FOX_TBL_USERS_GROUP_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_68A53ED335ED44CAA8FD489730A16DAB]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_USERS_GROUP] PRIMARY KEY CLUSTERED 
(
	[GROUP_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


