
CREATE TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE](
	[CONSENT_TO_CARE_ID] [bigint] NOT NULL,
	[SEND_TO] [varchar](70) NULL,
	[SIGNATORY] [varchar](100) NULL,
	[CASE_ID] [bigint] NULL,
	[STATUS_ID] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[SIGNATURE_PATH] [varchar](70) NULL,
	[SOURCE_TYPE] [varchar](70) NULL,
	[EXPIRY_DATE_UTC] [datetime] NULL,
	[TEMPLATE_HTML] [varchar](max) NULL,
	[FAILED_ATTEMPTS] [int] NULL,
	[SENT_TO_ID] [bigint] NULL,
	[TASK_ID] [bigint] NULL,
	[SIGNED_PDF_PATH] [varchar](500) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[CONSENT_TO_CARE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE] ADD  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE] ADD  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE] ADD  DEFAULT ((0)) FOR [DELETED]
GO

GO