USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_ADD_HBR_TASK_LOGS]    Script Date: 8/15/2022 11:30:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOX_TBL_ADD_HBR_TASK_LOGS](
	[ADD_HBR_TASK_LOGS_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[TASK_ID] [bigint] NULL,
	[CREATED_BY] [varchar](255) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](255) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ADD_HBR_TASK_LOGS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_ADD_HBR_TASK_LOGS] ADD  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ADD_HBR_TASK_LOGS] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ADD_HBR_TASK_LOGS] ADD  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ADD_HBR_TASK_LOGS] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ADD_HBR_TASK_LOGS] ADD  DEFAULT ((0)) FOR [DELETED]
GO


