USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_SENDER_TYPE]    Script Date: 7/21/2022 9:34:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_SENDER_TYPE](
	[FOX_TBL_SENDER_TYPE_ID] [bigint] NOT NULL,
	[SENDER_TYPE_NAME] [varchar](50) NULL,
	[SENDER_TYPE_DESCRIPTION] [varchar](50) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[DISPLAY_ORDER] [int] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_TYPE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_TYPE_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_TYPE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_TYPE_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_TYPE_DELETED]  DEFAULT ((0)),
	[IsInternal] [bit] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_596ACD4A8793499F83B5C5DDAA4E1FE6]  DEFAULT (newsequentialid())
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


