USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_CASE_TREATMENT_TEAM]    Script Date: 7/21/2022 9:47:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_CASE_TREATMENT_TEAM](
	[TREATMENT_TEAM_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[CASE_ID] [bigint] NULL,
	[TREATING_PROVIDER_ID] [bigint] NULL,
	[ADMIT_DATE] [date] NULL,
	[START_DATE] [date] NULL,
	[END_DATE] [date] NULL,
	[LAST_VISIT_DATE] [date] NULL,
	[CERTIFICATION_END_DATE] [date] NULL,
	[CASE_PROVIDER_ID] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_TREATMENT_TEAM_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_TREATMENT_TEAM_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_TREATMENT_TEAM_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_TREATMENT_TEAM_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_TREATMENT_TEAM_DELETED]  DEFAULT ((0)),
	[FOX_GUID] [varchar](50) NULL,
 CONSTRAINT [PK_FOX_TBL_CASE_TREATMENT_TEAM] PRIMARY KEY CLUSTERED 
(
	[TREATMENT_TEAM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


