USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL]    Script Date: 7/21/2022 9:46:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL](
	[FRICTIONLESS_REFERRAL_FILE_ID] [bigint] NOT NULL,
	[UNIQUE_ID] [varchar](50) NULL,
	[FILE_PATH] [varchar](500) NULL,
	[FILE_PATH1] [varchar](500) NULL,
	[WORK_ID] [bigint] NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[DELETED] [bit] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
 CONSTRAINT [PK_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] PRIMARY KEY CLUSTERED 
(
	[FRICTIONLESS_REFERRAL_FILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_CREATED_BY]  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_MODIFIED_BY]  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL] ADD  CONSTRAINT [DF_FOX_TBL_FRICTIONLESS_WORK_QUEUE_FILE_ALL_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO


