USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_ADJUSTMENT_LOGS]    Script Date: 7/21/2022 8:40:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_ADJUSTMENT_LOGS](
	[ADJUSTMENT_LOG_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NOT NULL,
	[ADJUSTMENT_DETAIL_ID] [bigint] NULL,
	[LOG_MESSAGE] [varchar](3000) NULL,
	[FIELD_NAME] [varchar](80) NULL,
	[PREVIOUS_VALUE] [varchar](5000) NULL,
	[NEW_VALUE] [varchar](5000) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_ADJUSTMENT_LOGS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_ADJUSTMENT_LOGS_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_ADJUSTMENT_LOGS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_ADJUSTMENT_LOGS_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_ADJUSTMENT_LOGS_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_D04FB5DB5D7D4F83BBA0698AB54867C6]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_ADJUSTMENT_LOGS] PRIMARY KEY CLUSTERED 
(
	[ADJUSTMENT_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


