USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_TASKSUBTYPE_REFSOURCE_MAPPING]    Script Date: 7/21/2022 9:38:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_TASKSUBTYPE_REFSOURCE_MAPPING](
	[TASKSUBTYPE_REFSOURCE_MAPPING_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CONDITION] [varchar](100) NULL,
	[ORDER_STATUS_ID] [int] NULL,
	[SOURCE_ID_old] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_TASKSUBTYPE_REFSOURCE_MAPPING_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_TASKSUBTYPE_REFSOURCE_MAPPING_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_TASKSUBTYPE_REFSOURCE_MAPPING_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_TASKSUBTYPE_REFSOURCE_MAPPING_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_TASKSUBTYPE_REFSOURCE_MAPPING_DELETED]  DEFAULT ((0)),
	[TASK_SUB_TYPE_INTEL_TASK_FIELD_ID] [bigint] NULL,
	[SOURCE_ID] [bigint] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_439465D8D3974EA28EA92435FD5A68B9]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_TASKSUBTYPE_REFSOURCE_MAPPING] PRIMARY KEY CLUSTERED 
(
	[TASKSUBTYPE_REFSOURCE_MAPPING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


