USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_MATRIX_AND_FACILITY_FREEZ]    Script Date: 7/21/2022 9:07:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_MATRIX_AND_FACILITY_FREEZ](
	[PATIENT_ACCOUNT] [bigint] NOT NULL,
	[CLAIM_NO] [bigint] NOT NULL,
	[FINANCIAL_CLASS] [varchar](300) NULL,
	[FC_CODE] [varchar](50) NULL,
	[STATE] [varchar](2) NULL,
	[PROVIDER_CODE] [bigint] NOT NULL,
	[PROVIDER_NAME] [varchar](102) NULL,
	[LOCATION_NAME] [varchar](200) NOT NULL,
	[REFERRAL_REGION_CODE] [varchar](25) NULL,
	[FACILITY] [varchar](100) NULL,
	[FACILTIY_CODE] [varchar](10) NULL,
	[REFERRAL_REGION_NAME] [varchar](100) NULL,
	[INSURANCE_NAME] [varchar](50) NULL,
	[DOE] [date] NULL,
	[DATE_OF_SERVICE] [date] NULL,
	[BILLED_CHARGES] [money] NULL,
	[EXPECTED_CHARGES] [money] NULL,
	[CONTRACTUAL_ALLOWANCE] [money] NULL,
	[ADJ_IN_PERIODS] [money] NULL,
	[PAY_IN_PERIODS] [money] NULL,
	[FOX_UNITS] [numeric](38, 0) NULL,
	[PRACTICE_CODE] [int] NOT NULL,
	[DISP_NAME] [varchar](100) NULL,
	[UNITS] [float] NULL,
	[FOX_PROVIDER_CODE] [varchar](10) NULL,
	[AR_FOR_PERIODS] [money] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


