USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_SHARED_SCHEDULER]    Script Date: 7/21/2022 9:34:55 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_SHARED_SCHEDULER](
	[SHARED_SCHEDULER_ID] [bigint] NOT NULL,
	[SHARED_BY_PROVIDER] [bigint] NULL,
	[SHARED_WITH_PROVIDER] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
 CONSTRAINT [PK_FOX_TBL_SHARED_SCHEDULER] PRIMARY KEY CLUSTERED 
(
	[SHARED_SCHEDULER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


