USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_ACQUISITION_PATIENT]    Script Date: 10/25/2022 11:21:06 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOX_TBL_ACQUISITION_PATIENT](
	[FOX_TBL_PATIENT_ACQUISITION_ID] [bigint] NOT NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[IS_ACQUISITION] [bit] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
 CONSTRAINT [PK_FOX_TBL_ACQUISITION_PATIENT] PRIMARY KEY CLUSTERED 
(
	[FOX_TBL_PATIENT_ACQUISITION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_ACQUISITION_PATIENT] ADD  CONSTRAINT [DF_FOX_TBL_ACQUISITION_PATIENT_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ACQUISITION_PATIENT] ADD  CONSTRAINT [DF_FOX_TBL_ACQUISITION_PATIENT_CREATED_BY]  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ACQUISITION_PATIENT] ADD  CONSTRAINT [DF_FOX_TBL_ACQUISITION_PATIENT_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ACQUISITION_PATIENT] ADD  CONSTRAINT [DF_FOX_TBL_ACQUISITION_PATIENT_MODIFIED_BY]  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ACQUISITION_PATIENT] ADD  CONSTRAINT [DF_FOX_TBL_ACQUISITION_PATIENT_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO

