USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PATIENT_PROCEDURE]    Script Date: 7/21/2022 9:19:21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PATIENT_PROCEDURE](
	[PAT_PROC_ID] [bigint] NOT NULL,
	[WORK_ID] [bigint] NULL,
	[PROC_CODE] [varchar](20) NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[CPT_DESC] [varchar](255) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_PROCEDURE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_P__CREAT__3F91D95E]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_PROCEDURE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_P__MODIF__417A21D0]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_P__DELET__426E4609]  DEFAULT ((0)),
	[SPECIALITY_PROGRAM] [varchar](500) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_30AE1CF694D444EC8E2B4F9E512F5D3F]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK__FOX_TBL___76B2DA872919046C] PRIMARY KEY CLUSTERED 
(
	[PAT_PROC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


