USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_AUTH_CHARGES]    Script Date: 7/21/2022 8:44:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_AUTH_CHARGES](
	[AUTH_CHARGES_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[AUTH_ID] [bigint] NULL,
	[CPT_RANGE_FROM_CODE] [varchar](20) NULL,
	[CPT_RANGE_TO_CODE] [varchar](20) NULL,
	[IS_EXEMPT] [bit] NULL,
	[DIAGNOSIS_CODE] [varchar](20) NULL,
	[VALUE] [money] NULL,
	[VALUE_TYPE_ID] [int] NULL,
	[USED] [money] NULL,
	[REMAINING]  AS ([VALUE]-[USED]),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_CHARGES_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_CHARGES_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_CHARGES_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_CHARGES_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_CHARGES_DELETED]  DEFAULT ((0)),
	[CHARGES] [varchar](20) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_4A5EC15239114057959513D9D8B707D1]  DEFAULT (newsequentialid()),
	[FOX_GUID] [varchar](50) NULL,
 CONSTRAINT [PK_FOX_TBL_AUTH_CHARGES] PRIMARY KEY CLUSTERED 
(
	[AUTH_CHARGES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


