USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_EMAIL_CONFIG]    Script Date: 7/21/2022 8:54:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_EMAIL_CONFIG](
	[ID] [bigint] NOT NULL,
	[EMAIL_ADDRESS] [varchar](255) NOT NULL,
	[ON_INDEX] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_E__ON_IN__096AD2D7]  DEFAULT ((0)),
	[ON_COMPELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_E__ON_CO__0A5EF710]  DEFAULT ((0)),
	[SERVICE_EXCEPTION] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_E__SERVI__0B531B49]  DEFAULT ((0)),
	[ON_REFERRAL_RECEIVE] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_E__ON_RE__0C473F82]  DEFAULT ((0)),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_EMAIL_CONFIG_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_E__CREAT__0E2F87F4]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_EMAIL_CONFIG_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_E__MODIF__1017D066]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_E__DELET__110BF49F]  DEFAULT ((0)),
	[IsUrgentEmail] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_E__IsUrg__120018D8]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_9B071046FE5F45F4B35A8399550BBE41]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK__FOX_TBL___3214EC270854B63B] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


