USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_CLIENT_EXPERIENCE_SERVICE_LOG]    Script Date: 7/21/2022 9:47:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_CLIENT_EXPERIENCE_SERVICE_LOG](
	[FOX_TBL_ClIENT_EXPERIENCE_LOG_ID] [bigint] NOT NULL,
	[SURVEY_FLAG] [varchar](15) NULL,
	[SURVEY_ID_COUNT] [int] NULL,
	[IS_SUCCESSFUL] [bit] NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](255) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[FOX_TBL_ClIENT_EXPERIENCE_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


