USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_ORDERING_REF_SOURCE]    Script Date: 7/21/2022 9:10:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_ORDERING_REF_SOURCE](
	[SOURCE_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CODE] [varchar](10) NULL,
	[NAME] [varchar](100) NULL,
	[FIRST_NAME] [varchar](50) NULL,
	[LAST_NAME] [varchar](50) NULL,
	[TITLE] [varchar](50) NULL,
	[ADDRESS] [varchar](500) NULL,
	[ADDRESS_2] [varchar](500) NULL,
	[CITY] [varchar](50) NULL,
	[STATE] [varchar](2) NULL,
	[ZIP] [varchar](9) NULL,
	[PHONE] [varchar](20) NULL,
	[FAX] [varchar](20) NULL,
	[REFERRAL_REGION] [varchar](10) NULL,
	[NPI] [varchar](11) NULL,
	[ACCOUNT] [varchar](100) NULL,
	[ORGANIZATION] [varchar](100) NULL,
	[ACO] [varchar](100) NULL,
	[PRACTICE_ORGANIZATION_ID] [bigint] NULL,
	[INACTIVE_REASON_ID] [bigint] NULL,
	[INACTIVE_DATE] [datetime] NULL,
	[SOURCE_DELIVERY_METHOD_ID] [bigint] NULL,
	[NOTES] [varchar](3000) NULL,
	[ACO_ID] [bigint] NULL,
	[REFERRAL_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_ORDERING_REF_SOURCE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL CONSTRAINT [DF__FOX_TBL_O__CREAT__39643086_6906]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_ORDERING_REF_SOURCE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL CONSTRAINT [DF__FOX_TBL_O__MODIF__3B4C78F8_6906]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_O__DELET__3C409D31_6906]  DEFAULT ((0)),
	[MI] [varchar](1) NULL,
	[CELL] [varchar](10) NULL,
	[Speciality] [varchar](100) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_93CFBFF2C2394ECC946A55B5DCC1E795]  DEFAULT (newsequentialid()),
	[EMAIL] [varchar](255) NULL,
 CONSTRAINT [PK_FOX_TBL_ORDERING_REF_SOURCE_6906] PRIMARY KEY CLUSTERED 
(
	[SOURCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


