USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_CANCEL_CHARGE_REGIONS]    Script Date: 2/19/2024 10:42:27 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOX_TBL_CANCEL_CHARGE_REGIONS](
	[CANCEL_REGION_ID] [bigint] NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[MODIFIED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NULL,
	[REFERRAL_REGION_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[CANCEL_REGION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_CANCEL_CHARGE_REGIONS] ADD  CONSTRAINT [DF_CREATED_BY]  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CANCEL_CHARGE_REGIONS] ADD  CONSTRAINT [DF_MODIFIED_BY]  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CANCEL_CHARGE_REGIONS] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_CANCEL_CHARGE_REGIONS] ADD  CONSTRAINT [DF_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_CANCEL_CHARGE_REGIONS] ADD  CONSTRAINT [DF_DELETED_DEFAULT]  DEFAULT ((0)) FOR [DELETED]
GO

