CREATE TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_NOT_ANSWERED_REASON](
	[NOT_ANSWERD_REASON_ID] [bigint] NOT NULL,
	[SURVEY_ID] [bigint] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[NOT_ANSWERED_REASON] [varchar](70) NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[NOT_ANSWERD_REASON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_NOT_ANSWERED_REASON] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_NOT_ANSWERED_REASON] ADD  DEFAULT ('FOXTEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_NOT_ANSWERED_REASON] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_NOT_ANSWERED_REASON] ADD  DEFAULT ('FOXTEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_NOT_ANSWERED_REASON] ADD  DEFAULT ((0)) FOR [DELETED]
GO


