USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_WORK_ORDER_ADDTIONAL_INFO]    Script Date: 7/21/2022 10:01:48 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_WORK_ORDER_ADDTIONAL_INFO](
	[WORK_ORDER_ADDTIONAL_INFO_ID] [bigint] NOT NULL,
	[WORK_ID] [bigint] NULL,
	[IS_TRASH_REFERRAL] [bit] NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_FOX_TBL_WORK_ORDER_ADDTIONAL_INFO] PRIMARY KEY CLUSTERED 
(
	[WORK_ORDER_ADDTIONAL_INFO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


