USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_NOTES]    Script Date: 7/21/2022 9:09:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_NOTES](
	[NOTES_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CASE_ID] [bigint] NULL,
	[TASK_ID] [bigint] NULL,
	[AUTH_ID] [bigint] NULL,
	[NOTES_TYPE_ID] [bigint] NULL,
	[NOTES] [varchar](max) NULL,
	[IS_NOTABLE] [bit] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_NOTES_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_NOTES_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_NOTES_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_NOTES_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_NOTES_DELETED]  DEFAULT ((0)),
	[IS_ACTIVE] [bit] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_C218EC5143534CAD8D9B08B2DE398A49]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_NOTES] PRIMARY KEY CLUSTERED 
(
	[NOTES_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


