USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_QLIK_EXPORT_LOG]    Script Date: 7/21/2022 9:57:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_QLIK_EXPORT_LOG](
	[QLIK_EXPORT_LOG_ID] [bigint] NOT NULL,
	[EXPORT_CONTENTS] [varchar](500) NULL,
	[IS_SUCCESSFUL] [bit] NOT NULL,
	[DELETED] [bit] NOT NULL,
	[CREATED_BY] [varchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[QLIK_EXPORT_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


