USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_RECONCILIATION_REASON]    Script Date: 7/21/2022 9:58:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_RECONCILIATION_REASON](
	[FOX_TBL_RECONCILIATION_REASON_ID] [bigint] NOT NULL,
	[REASON] [varchar](100) NULL,
	[CREATED_BY] [varchar](70) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[FOX_TBL_RECONCILIATION_REASON_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


