USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PHD_CALL_MAPPING]    Script Date: 7/21/2022 9:55:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PHD_CALL_MAPPING](
	[PHD_CALL_MAPPING_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PHD_CALL_SCENARIO_ID] [bigint] NULL,
	[PHD_CALL_REASON_ID] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_FOX_TBL_PHD_CALL_MAPPING] PRIMARY KEY CLUSTERED 
(
	[PHD_CALL_MAPPING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


