USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_RECONCILIATION_UPLOAD_LOG]    Script Date: 7/21/2022 9:58:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_RECONCILIATION_UPLOAD_LOG](
	[ID] [bigint] NOT NULL,
	[LAST_UPDATED_DATE] [datetime] NULL,
	[TOTAL_RECORDS] [bigint] NULL,
	[SUCCESSFULLY_ADDED] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[PRACTICE_CODE] [bigint] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


