USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_FACILITY_TYPE]    Script Date: 7/21/2022 8:55:11 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_FACILITY_TYPE](
	[FACILITY_TYPE_ID] [bigint] NOT NULL,
	[NAME] [varchar](100) NULL,
	[DISPLAY_NAME] [varchar](300) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_FACILITY_TYPE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_FACILITY_TYPE_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_FACILITY_TYPE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_FACILITY_TYPE_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_FACILITY_TYPE_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_21D57D3EDF8F40059FEC3FFEA2589960]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_FACILITY_TYPE] PRIMARY KEY CLUSTERED 
(
	[FACILITY_TYPE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


