USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_FILE_TIME_LOG]    Script Date: 7/21/2022 8:55:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_FILE_TIME_LOG](
	[FILE_MODIFIED_DATE] [datetime] NULL,
	[FILE_NAME] [varchar](1000) NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


