USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_THERAPY_TREATMENT_REFERRAL_REQUEST_FORM]    Script Date: 7/21/2022 10:01:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_THERAPY_TREATMENT_REFERRAL_REQUEST_FORM](
	[THERAPY_TREATMENT_REFERRAL_REQUEST_FORM_ID] [bigint] NOT NULL,
	[WORK_ID] [bigint] NULL,
	[THERAPY_TREATMENT_REFERRAL_REQUEST_HTML] [varchar](max) NULL,
	[CREATED_BY] [varchar](70) NULL,
	[CREATED_DATE] [datetime] NULL,
 CONSTRAINT [PK_FOX_TBL_THERAPY_TREATMENT_REFERRAL_REQUEST_FORM] PRIMARY KEY CLUSTERED 
(
	[THERAPY_TREATMENT_REFERRAL_REQUEST_FORM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


