USE [MIS_DB]
GO
/****** Object:  Table [dbo].[FOX_TBL_PHD_FAQS_DETAILS]    Script Date: 10/29/2022 12:37:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS](
	[FAQS_ID] [bigint] NOT NULL,
	[QUESTIONS] [varchar](250) NULL,
	[ANSWERS] [nvarchar](max) NULL,
	[PRACTICE_CODE] [bigint] NOT NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_FOX_TBL_PHD_FAQS_DETAILS] PRIMARY KEY CLUSTERED 
(
	[FAQS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_CREATED_BY]  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_MODIFIED_BY]  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_PHD_FAQS_DETAILS] ADD  CONSTRAINT [DF_FOX_TBL_PHD_FAQS_DETAILS_DELETED]  DEFAULT ('0') FOR [DELETED]
GO

