USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL]    Script Date: 7/21/2022 9:46:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE](
	[FOX_FRICTIONLESS_UNAVAILABLE_ID] [bigint] NOT NULL,
	[FIRST_NAME] [varchar](70) NULL,
	[LAST_NAME] [varchar](70) NULL,
	[EMAIL] [varchar](100) NULL,
	[ZIP_CODE] [varchar](20) NULL,
	[CITY_NAME] [varchar](100) NULL,
	[PHONE_NUMBER] [varchar](10) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
	[FRICTIONLESS_REFERRAL_ID] [bigint] NULL,
	[ADDRESS] [varchar](500) NULL,
	[STATE] [varchar](2) NULL,
	[POA_FRICTIONLESS_REFERRAL_ID] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[FOX_FRICTIONLESS_UNAVAILABLE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE] ADD  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE] ADD  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE] ADD  DEFAULT ((0)) FOR [DELETED]
GO

