USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_MEDICARE_LIMIT]    Script Date: 7/21/2022 9:07:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_MEDICARE_LIMIT](
	[MEDICARE_LIMIT_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[Patient_Account] [bigint] NULL,
	[CASE_ID] [bigint] NULL,
	[EFFECTIVE_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[ABN_EST_WK_COST] [money] NULL,
	[ABN_COMMENTS] [varchar](max) NULL,
	[NPI] [varchar](10) NULL,
	[MEDICARE_LIMIT_TYPE_ID] [int] NULL,
	[MEDICARE_LIMIT_STATUS] [varchar](10) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_MEDICARE_LIMIT_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_MEDICARE_LIMIT_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_MEDICARE_LIMIT_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_MEDICARE_LIMIT_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_MEDICARE_LIMIT_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_7D351F527FF14CA9AFFA85F660142DB0]  DEFAULT (newsequentialid()),
	[FOX_GUID] [varchar](50) NULL,
 CONSTRAINT [PK_FOX_TBL_MEDICARE_LIMIT] PRIMARY KEY CLUSTERED 
(
	[MEDICARE_LIMIT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


