USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PHD_CALLING_UPDATE_SERVICE_CONFIG]    Script Date: 7/21/2022 9:56:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PHD_CALLING_UPDATE_SERVICE_CONFIG](
	[PHD_CALLING_UPDATE_SERVICE_CONFIG_ID] [int] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[ENVIRONMENT_NAME] [varchar](50) NULL,
	[LOAD_XML] [bit] NULL,
	[RECORDING_FOLDER_PATH] [varchar](500) NULL,
	[XML_FOLDER_PATH] [varchar](500) NULL,
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALLING_UPDATE_SERVICE_CONFIG_DELETED]  DEFAULT ((0)),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALLING_UPDATE_SERVICE_CONFIG_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALLING_UPDATE_SERVICE_CONFIG_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALLING_UPDATE_SERVICE_CONFIG_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALLING_UPDATE_SERVICE_CONFIG_MODIFIED_DATE]  DEFAULT (getdate()),
	[LAST_EXECUTION_DATE] [datetime] NULL,
 CONSTRAINT [PK_FOX_TBL_PHD_CALLING_UPDATE_SERVICE_CONFIG] PRIMARY KEY CLUSTERED 
(
	[PHD_CALLING_UPDATE_SERVICE_CONFIG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


