USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_WORK_QUEUE_File_All]    Script Date: 7/21/2022 9:41:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_WORK_QUEUE_File_All](
	[FILE_ID] [bigint] NOT NULL,
	[UNIQUE_ID] [varchar](50) NULL,
	[FILE_PATH] [varchar](500) NULL,
	[FILE_PATH1] [varchar](500) NULL,
	[deleted] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_W__delet__77A12857]  DEFAULT ((0)),
	[WORK_ID] [bigint] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_8F0D3A1AFB224232A82702E86FE118AF]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK__FOX_TBL___49C04C7AA1692A63] PRIMARY KEY CLUSTERED 
(
	[FILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


