USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PATIENT_SURVEY_CALL_LOG]    Script Date: 7/21/2022 9:20:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_CALL_LOG](
	[SURVEY_CALL_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[ACU_CALL_ID] [bigint] NULL,
	[SURVEY_ID] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[FILE_NAME] [varchar](500) NULL,
	[IS_RECEIVED] [bit] NULL,
	[CALL_DURATION] [varchar](20) NULL,
	[IS_TO_PATIENT] [bit] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_CALL_LOG_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_CALL_LOG_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_CALL_LOG_DELETED]  DEFAULT ((0)),
	[CALL_OUT_COME] [varchar](50) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_D2F0FCE9DD9744A1AC1F5E579033AAD3]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_PATIENT_SURVEY_CALL_LOG] PRIMARY KEY CLUSTERED 
(
	[SURVEY_CALL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


