USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_RECONCILE_DEMOGRAPHICS]    Script Date: 7/21/2022 9:28:21 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_RECONCILE_DEMOGRAPHICS](
	[FOX_REC_DEM_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NOT NULL,
	[FIRST_NAME] [varchar](50) NULL,
	[LAST_NAME] [varchar](50) NULL,
	[DOB] [datetime] NULL,
	[GENDER] [varchar](15) NULL,
	[ADDRESS] [varchar](500) NULL,
	[CITY] [varchar](50) NULL,
	[ZIP] [varchar](9) NULL,
	[STATE] [varchar](2) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_RECONCILE_DEMOGRAPHICS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_R__CREAT__79BE7AF3]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_RECONCILE_DEMOGRAPHICS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_R__MODIF__7BA6C365]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_R__DELET__7C9AE79E]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_88E064E914B94C9F8A69F350B687D341]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK__FOX_TBL___B84895ED17819512] PRIMARY KEY CLUSTERED 
(
	[FOX_REC_DEM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


