USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_WORK_QUEUE]    Script Date: 7/21/2022 9:40:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_WORK_QUEUE](
	[WORK_ID] [bigint] NOT NULL,
	[UNIQUE_ID] [varchar](50) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[SORCE_TYPE] [varchar](30) NULL,
	[SORCE_NAME] [varchar](255) NULL,
	[WORK_STATUS] [varchar](50) NULL,
	[RECEIVE_DATE] [datetime] NULL,
	[TOTAL_PAGES] [int] NULL,
	[NO_OF_SPLITS] [int] NULL,
	[FILE_PATH] [varchar](500) NULL,
	[ASSIGNED_TO] [varchar](70) NULL,
	[ASSIGNED_BY] [varchar](70) NULL,
	[ASSIGNED_DATE] [datetime] NULL,
	[COMPLETED_BY] [varchar](70) NULL,
	[COMPLETED_DATE] [datetime] NULL,
	[INDEXED_BY] [varchar](70) NULL,
	[INDEXED_DATE] [datetime] NULL,
	[DOCUMENT_TYPE] [bigint] NULL,
	[SENDER_ID_old] [bigint] NULL,
	[FACILITY_NAME] [varchar](100) NULL,
	[DEPARTMENT_ID] [varchar](50) NULL,
	[IS_EMERGENCY_ORDER] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_W__IS_EM__70F42AC8]  DEFAULT ((0)),
	[REASON_FOR_VISIT] [varchar](1000) NULL,
	[ACCOUNT_NUMBER] [varchar](100) NULL,
	[UNIT_CASE_NO] [varchar](100) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_WORK_QUEUE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_W__CREAT__72DC733A]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_WORK_QUEUE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_W__MODIF__74C4BBAC]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_W__DELET__75B8DFE5]  DEFAULT ((0)),
	[TRANSFER_DATE] [datetime] NULL,
	[supervisor_status] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_W__super__76AD041E]  DEFAULT ((0)),
	[FAX_ID] [varchar](50) NULL,
	[INDEXER_ASSIGN_DATE] [datetime] NULL,
	[AGENT_ASSIGN_DATE] [datetime] NULL,
	[IS_VERIFIED_BY_RECIPIENT] [bit] NULL,
	[IsSigned] [bit] NULL,
	[SignedBy] [bigint] NULL,
	[FOX_TBL_SENDER_TYPE_ID] [bigint] NULL,
	[FOX_TBL_SENDER_NAME_ID] [bigint] NULL,
	[GuestID] [varchar](500) NULL,
	[REASON_FOR_THE_URGENCY] [varchar](200) NULL,
	[IS_POST_ACUTE] [bit] NULL,
	[IS_EVALUATE_TREAT] [bit] NULL,
	[HEALTH_NAME] [varchar](100) NULL,
	[HEALTH_NUMBER] [varchar](100) NULL,
	[Expected_Discharge_Date] [datetime] NULL,
	[IS_VERBAL_ORDER] [bit] NULL,
	[VO_ON_BEHALF_OF] [bigint] NULL,
	[VO_RECIEVED_BY] [varchar](70) NULL,
	[VO_DATE_TIME] [datetime] NULL,
	[FACILITY_ID] [bigint] NULL,
	[SENDER_ID] [bigint] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_76A256EB2BB64E7FAC7538B4E12D03EC]  DEFAULT (newsequentialid()),
	[IS_TRASH_REFERRAL] [bit] NULL,
	[RFO_Type] [varchar](50) NULL,
	[OCR_STATUS_ID] [bigint] NULL,
	[FOX_SOURCE_CATEGORY_ID] [bigint] NULL,
	[SENT_FOR_SIGNATURES] [varchar](255) NULL,
	[REFERRAL_EMAIL_SENT_TO] [varchar](100) NULL,
	[IS_DENIED] [bit] NULL,
	[SIGNED_ON] [datetime] NULL,
 CONSTRAINT [PK__FOX_TBL___894A0757F788C1D6] PRIMARY KEY CLUSTERED 
(
	[WORK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


