USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_AUTO_INDEXING_CONFIG]    Script Date: 7/21/2022 9:45:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_AUTO_INDEXING_CONFIG](
	[AUTO_INDEXING_SERVICE_CONFIG_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[ENVIRONMENT_NAME] [varchar](255) NULL,
	[LAST_EXECUTION_TIME] [datetime] NULL,
	[LAST_EXECUTION_DATE] [datetime] NULL,
	[LOAD_SERVICE] [bit] NULL,
	[CREATED_BY] [varchar](255) NOT NULL DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](255) NOT NULL DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[AUTO_INDEXING_SERVICE_CONFIG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


