USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_DETAIL_EXPORT_INFO]    Script Date: 7/21/2022 8:53:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_DETAIL_EXPORT_INFO](
	[DETAIL_EXPORT_INFO_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[EMAIL] [varchar](300) NULL,
	[EXPORT_PATH] [varchar](500) NULL,
	[IS_EXPIRED] [bit] NULL,
	[STATUS] [nchar](10) NULL,
	[CREATED_BY] [varchar](70) NOT NULL DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL DEFAULT ((0)),
	[REPORT_TYPE_ID] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


