USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_USER_RIGHTS]    Script Date: 7/21/2022 9:39:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_USER_RIGHTS](
	[RIGHT_ID] [bigint] NOT NULL,
	[RIGHT_NAME] [varchar](50) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_USER_RIGHTS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_U__CREAT__685EE4C7]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_USER_RIGHTS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_U__MODIF__6A472D39]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_U__DELET__6B3B5172]  DEFAULT ((0)),
	[RIGHT_TYPE_ID] [bigint] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_82AD9B40896C41FCAD6A583E5FD3FA9D]  DEFAULT (newsequentialid()),
	[Display_Order] [int] NULL,
 CONSTRAINT [PK__FOX_TBL___52DCC0728A03EEF7] PRIMARY KEY CLUSTERED 
(
	[RIGHT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


