USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_CASE]    Script Date: 7/21/2022 8:48:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_CASE](
	[CASE_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[CASE_TYPE_ID] [int] NULL,
	[DISCIPLINE_ID] [int] NULL,
	[CASE_NO] [varchar](100) NULL,
	[CASE_STATUS_ID] [int] NULL,
	[CASE_SUFFIX_ID] [int] NULL,
	[GROUP_IDENTIFIER_ID] [int] NULL,
	[TREATING_PROVIDER_ID] [bigint] NULL,
	[POS_ID] [bigint] NULL,
	[TREATING_REGION_ID] [bigint] NULL,
	[IS_MANUAL_CHANGE_REGION] [bit] NULL,
	[ADMISSION_DATE] [datetime] NULL,
	[START_CARE_DATE] [datetime] NULL,
	[END_CARE_DATE] [datetime] NULL,
	[VISIT_PER_WEEK] [int] NULL,
	[NO_OF_WEEK] [int] NULL,
	[TOTAL_VISITS]  AS ([VISIT_PER_WEEK]*[NO_OF_WEEK]),
	[WORK_ID] [bigint] NULL,
	[ORDERING_REF_SOURCE_ID_old] [bigint] NULL,
	[ACU_IDENTIFIER_ID] [bigint] NULL,
	[HOSPITAL_IDENTIFIER_ID] [bigint] NULL,
	[SNF_IDENTIFIER_ID] [bigint] NULL,
	[HHH_IDENTIFIER_ID] [bigint] NULL,
	[REF_REGION_ID] [bigint] NULL,
	[SOURCE_OF_REFERRAL_ID] [int] NULL,
	[PRIMARY_PHY_ID_old] [bigint] NULL,
	[CERTIFYING_REF_SOURCE_ID_old] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_CASE_DELETED]  DEFAULT ((0)),
	[HEAR_ABOUT_US_ID] [bigint] NULL,
	[ORDERING_REF_SOURCE_ID] [bigint] NULL,
	[CERTIFYING_REF_SOURCE_ID] [bigint] NULL,
	[PRIMARY_PHY_ID] [bigint] NULL,
	[RT_CASE_NO] [varchar](100) NULL,
	[PATIENT_RESP_INS_ID] [bigint] NULL,
	[HOLD_DATE] [datetime] NULL,
	[HOLD_TILL_DATE] [datetime] NULL,
	[IsWellness] [bit] NULL,
	[IsSkilled] [bit] NULL,
	[DISCHARGE_DATE] [datetime] NULL,
	[HOLD_DURATION] [varchar](50) NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_0F7AE3AF32944322AB6FA68C845A1233]  DEFAULT (newsequentialid()),
	[FOX_GUID] [varchar](50) NULL,
	[Hold_Follow_Up_Date] [datetime] NULL,
	[NON_ADMIT_DATE] [datetime] NULL,
	[NON_ADMIT_REASON] [varchar](500) NULL,
	[STAT_FOX_GUID] [varchar](50) NULL,
	[ACTIVE_ASSIGNED_ON] [datetime] NULL,
	[PENDING_ASSIGNMENT_ON] [datetime] NULL,
 CONSTRAINT [PK_FOX_TBL_CASE] PRIMARY KEY CLUSTERED 
(
	[CASE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


