USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_INTERFACE_SYNCH]    Script Date: 7/21/2022 9:06:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_INTERFACE_SYNCH](
	[FOX_INTERFACE_SYNCH_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[CASE_ID] [bigint] NULL,
	[TASK_ID] [bigint] NULL,
	[IS_SYNCED] [bit] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_INTERFACE_SYNCH_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_I__CREAT__51E593C3]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_INTERFACE_SYNCH_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_I__MODIF__53CDDC35]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_I__DELET__54C2006E]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_36E8C3AD48424D64B7FE647DA47A963C]  DEFAULT (newsequentialid()),
	[Work_ID] [bigint] NULL,
	[APPLICATION] [varchar](50) NULL,
	[APPOINTMENT_ID] [bigint] NULL,
	[GENERAL_NOTE_ID] [bigint] NULL,
	[TASK_LOG_ID] [bigint] NULL,
	[ACTION] [varchar](50) NULL,
	[TREATMENT_TEAM_ID] [bigint] NULL,
 CONSTRAINT [PK__FOX_TBL___442C1E52CA8819CF] PRIMARY KEY CLUSTERED 
(
	[FOX_INTERFACE_SYNCH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


