USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_HEAR_ABOUT_US_OPTIONS]    Script Date: 7/21/2022 9:02:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_HEAR_ABOUT_US_OPTIONS](
	[FOX_TBL_HEAR_ABOUT_US_OPTION_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CODE] [varchar](10) NULL,
	[NAME] [varchar](100) NULL,
	[DESCRIPTION] [varchar](300) NULL,
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_HEAR_ABOUT_US_OPTIONS_DELETED]  DEFAULT ((0)),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_HEAR_ABOUT_US_OPTIONS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_HEAR_ABOUT_US_OPTIONS_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_HEAR_ABOUT_US_OPTIONS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_Table_1_CREATED_DATE1]  DEFAULT (getdate()),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_B406A73F07D747C18381651F041C00E2]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_HEAR_ABOUT_US_OPTIONS] PRIMARY KEY CLUSTERED 
(
	[FOX_TBL_HEAR_ABOUT_US_OPTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


