USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PATIENT_SURVEY_HISTORY]    Script Date: 7/21/2022 9:21:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_HISTORY](
	[SURVEY_HISTORY_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[SURVEY_ID] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[IS_CONTACT_HQ] [bit] NULL,
	[IS_RESPONSED_BY_HQ] [bit] NULL,
	[IS_REFERABLE] [bit] NULL,
	[IS_IMPROVED_SETISFACTION] [bit] NULL,
	[FEEDBACK] [varchar](3000) NULL,
	[SURVEY_FLAG] [varchar](50) NULL,
	[SURVEY_STATUS_BASE] [varchar](50) NULL,
	[SURVEY_STATUS_CHILD] [varchar](50) NULL,
	[SURVEY_BY] [varchar](70) NULL,
	[SURVEY_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_HISTORY_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL,
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_HISTORY_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_7DD3454317914C8AA80CCC86EC073DC4]  DEFAULT (newsequentialid()),
	[IS_QUESTION_ANSWERED] [bit] NULL,
	[IS_EXCEPTIONAL] [bit] NULL,
	[IS_PROTECTIVE_EQUIPMENT] [bit] NULL,
 CONSTRAINT [PK_FOX_TBL_PATIENT_SURVEY_HISTORY] PRIMARY KEY CLUSTERED 
(
	[SURVEY_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


