CREATE TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_STATUS](
	[CONSENT_TO_CARE_STATUS_ID] [bigint] NOT NULL,
	[STATUS_NAME] [varchar](50) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK_FOX_TBL_CONSENT_TO_CARE_STATUS] PRIMARY KEY CLUSTERED 
(
	[CONSENT_TO_CARE_STATUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_STATUS] ADD  CONSTRAINT [DF_FOX_TBL_CONSENT_TO_CARE_STATUS_CREATED_BY]  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_STATUS] ADD  CONSTRAINT [DF_FOX_TBL_CONSENT_TO_CARE_STATUS_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_STATUS] ADD  CONSTRAINT [DF_FOX_TBL_CONSENT_TO_CARE_STATUS_MODIFIED_BY]  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_STATUS] ADD  CONSTRAINT [DF_FOX_TBL_CONSENT_TO_CARE_STATUS_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_STATUS] ADD  CONSTRAINT [DF_FOX_TBL_CONSENT_TO_CARE_STATUS_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO