USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_REGION_COVER_SHEET]    Script Date: 7/21/2022 9:59:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_REGION_COVER_SHEET](
	[REGION_COVER_SHEET_ID] [bigint] NOT NULL,
	[REFERRAL_REGION_ID] [bigint] NULL,
	[REFERRAL_REGION_CODE] [varchar](10) NULL,
	[IS_FAX_COVER_LETTER] [bit] NULL,
	[FILE_PATH] [varchar](500) NULL,
	[CREATED_BY] [varchar](70) NULL DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NULL DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL DEFAULT (getdate()),
	[DELETED] [bit] NULL DEFAULT ((0)),
PRIMARY KEY CLUSTERED 
(
	[REGION_COVER_SHEET_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


