USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PATIENT_SURVEY_FORMAT_TYPE]    Script Date: 7/21/2022 9:21:35 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_FORMAT_TYPE](
	[SURVEY_FORMAT_TYPE_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[FORMAT_TYPE] [varchar](20) NULL,
	[IS_ACTIVE] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_FORMAT_TYPE_IS_ACTIVE]  DEFAULT ((0)),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_FORMAT_TYPE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_FORMAT_TYPE_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_FORMAT_TYPE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_FORMAT_TYPE_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_FORMAT_TYPE_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_F662469323724BB09A9B275BB08772DF]  DEFAULT (newsequentialid())
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


