USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_APPOINTMENT]    Script Date: 7/21/2022 8:42:47 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_APPOINTMENT](
	[APPOINTMENT_ID] [bigint] NOT NULL,
	[APPOINTMENT_DATE] [date] NULL,
	[VISIT_TYPE_ID] [bigint] NULL,
	[TIME_FROM] [varchar](15) NULL,
	[TIME_TO] [varchar](15) NULL,
	[PROVIDER_ID] [bigint] NULL,
	[CASE_ID] [bigint] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[APPOINTMENT_STATUS_ID] [bigint] NULL,
	[SIGNED_BY] [varchar](70) NULL,
	[REASON_FOR_SIGNING] [varchar](500) NULL,
	[SIGNATURE_PATH] [varchar](500) NULL,
	[LATITUDE] [float] NULL,
	[LONGITUDE] [float] NULL,
	[NOTES] [varchar](500) NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_APPOINTMENT_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_APPOINTMENT_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[DELETED] [bit] NULL,
	[VISIT_FREQUENCY] [int] NULL,
	[VISIT_CRITERIA] [varchar](50) NULL,
	[DURATION_DAYS] [int] NULL,
	[IsSendForApproval] [bit] NULL,
	[AssignToProviderID] [bigint] NULL,
	[PTOID] [bigint] NULL,
	[IsClinicianAssignHisOwnAppt] [bit] NULL,
	[IsApproveRD] [bit] NULL,
	[IsDenyRD] [bit] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_3A1E0C499C6546BBAA42871DF50BDAB4]  DEFAULT (newsequentialid()),
	[ISSEND] [bit] NULL,
	[SENDTOID] [bigint] NULL,
	[ISSENDTOORS] [bit] NULL,
	[SENDDATE] [datetime] NULL,
	[IsBlocked] [bit] NULL,
	[ReasonForBlocked] [varchar](2000) NULL,
	[Accuracy] [float] NULL,
	[APPOINTMENT_COMPLETE_DATE_TIME] [datetime] NULL,
	[CANCELLATION_REASON_ID] [bigint] NULL,
	[ANTICIPATED_UNIT] [varchar](50) NULL,
	[REASON_FOR_REASSIGN] [varchar](500) NULL,
	[APPOINTMENT_NOTES] [varchar](8000) NULL,
 CONSTRAINT [PK_FOX_TBL_APPOINTMENT] PRIMARY KEY CLUSTERED 
(
	[APPOINTMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


