USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_CRAWLER_AVAYA_RECORDING_NOT_FOUND_LOGS]    Script Date: 7/21/2022 10:02:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_CRAWLER_AVAYA_RECORDING_NOT_FOUND_LOGS](
	[FOX_CRAWLER_LOG_ID] [bigint] NOT NULL,
	[INCOMING_CALL_NO] [varchar](10) NULL,
	[RECORDING_FOR_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](255) NOT NULL CONSTRAINT [DF_FOX_TBL_CRAWLER_AVAYA_RECORDING_NOT_FOUND_LOGS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_CRAWLER_AVAYA_RECORDING_NOT_FOUND_LOGS_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](255) NOT NULL CONSTRAINT [DF_FOX_TBL_CRAWLER_AVAYA_RECORDING_NOT_FOUND_LOGS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_CRAWLER_AVAYA_RECORDING_NOT_FOUND_LOGS_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_CRAWLER_AVAYA_RECORDING_NOT_FOUND_LOGS_DELETED]  DEFAULT ((0)),
 CONSTRAINT [PK_FOX_TBL_CRAWLER_AVAYA_RECORDING_NOT_FOUND_LOGS] PRIMARY KEY CLUSTERED 
(
	[FOX_CRAWLER_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


