USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_ADJUSTMENT_LOGS]    Script Date: 7/21/2022 8:40:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY](
	[ANNOUNCEMENT_HISTORY_ID] [bigint] NOT NULL,
	[ANNOUNCEMENT_ID] [bigint] NULL,
	[USER_ID] [bigint] NULL,
	[USER_NAME] [varchar](50) NULL,
	[SHOW_COUNT] [int] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ANNOUNCEMENT_HISTORY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_ANNOUNCEMENT_HISTORY] ADD  DEFAULT ('0') FOR [DELETED]
GO
