USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_REFERRAL_REGION]    Script Date: 7/21/2022 9:31:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_REFERRAL_REGION](
	[REFERRAL_REGION_ID] [bigint] NOT NULL,
	[REFERRAL_REGION_CODE] [varchar](10) NULL,
	[REFERRAL_REGION_NAME] [varchar](50) NULL,
	[ACCOUNT_MANAGER_EMAIL] [varchar](255) NULL,
	[ACCOUNT_MANAGER] [varchar](100) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_REFERRAL_REGION_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_REFERRAL_REGION_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_R__DELET__7C598B98]  DEFAULT ((0)),
	[IS_ACTIVE] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_R__IS_AC__7D4DAFD1]  DEFAULT ((1)),
	[PRACTICE_CODE] [bigint] NULL CONSTRAINT [DF__FOX_TBL_R__PRACT__043C0966]  DEFAULT ((1012714)),
	[REGIONAL_DIRECTOR_ID] [bigint] NULL,
	[STATE_CODE] [varchar](2) NULL,
	[IN_ACTIVEDATE] [datetime] NULL,
	[ALTERNATE_REGION_ID] [bigint] NULL,
	[IS_INACTIVE] [bit] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_8A164CB17713445A9A7C15232F14B795]  DEFAULT (newsequentialid()),
	[END_DATE] [datetime] NULL,
	[START_DATE] [datetime] NULL,
	[ACCOUNT_MANAGER_ID] [bigint] NULL,
	[SENIOR_REGIONAL_DIRECTOR_ID] [bigint] NULL,
 CONSTRAINT [PK__FOX_TBL___FC698E1E66E1935E] PRIMARY KEY CLUSTERED 
(
	[REFERRAL_REGION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


