USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_VISIT_QOUTA_PER_WEEK]    Script Date: 7/21/2022 9:39:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_VISIT_QOUTA_PER_WEEK](
	[VISIT_QOUTA_WEEK_ID] [int] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[VISIT_QOUTA_WEEK] [varchar](50) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_VISIT_QOUTA_PER_WEEK_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_VISIT_QOUTA_PER_WEEK_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_B066E8B124934934A0E70A887B6C0ECB]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_VISIT_QOUTA_PER_WEEK] PRIMARY KEY CLUSTERED 
(
	[VISIT_QOUTA_WEEK_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


