USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_AUTH_DOC]    Script Date: 7/21/2022 8:44:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_AUTH_DOC](
	[AUTH_DOC_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[AUTH_ID] [bigint] NULL,
	[FILE_PATH] [varchar](500) NULL,
	[LOGO_FILE_PATH] [varchar](500) NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
 CONSTRAINT [PK_FOX_TBL_AUTH_DOCS] PRIMARY KEY CLUSTERED 
(
	[AUTH_DOC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[FOX_TBL_AUTH_DOC] ADD  CONSTRAINT [DF_FOX_TBL_AUTH_DOC_CREATED_BY]  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTH_DOC] ADD  CONSTRAINT [DF_FOX_TBL_AUTH_DOCS_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTH_DOC] ADD  CONSTRAINT [DF_FOX_TBL_AUTH_DOC_MODIFIED_BY]  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTH_DOC] ADD  CONSTRAINT [DF_FOX_TBL_AUTH_DOCS_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTH_DOC] ADD  CONSTRAINT [DF_FOX_TBL_AUTH_DOCS_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO

ALTER TABLE [dbo].[FOX_TBL_AUTH_DOC] ADD  CONSTRAINT [MSmerge_df_rowguid_7CBF67518C0A4C6494BCAE75549C2235]  DEFAULT (newsequentialid()) FOR [rowguid]
GO


