USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL]    Script Date: 7/21/2022 9:46:05 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL](
	[FRICTIONLESS_REFERRAL_ID] [bigint] NOT NULL,
	[USER_TYPE] [varchar](50) NULL,
	[IS_SIGNED_REFERRAL] [bit] NULL,
	[SUBMITER_FIRST_NAME] [varchar](50) NULL,
	[SUBMITTER_LAST_NAME] [varchar](50) NULL,
	[SUBMITTER_PHONE] [varchar](10) NULL,
	[SUBMITTER_EMAIL] [varchar](50) NULL,
	[PROVIDER_NPI] [varchar](50) NULL,
	[PROVIDER_FIRST_NAME] [varchar](50) NULL,
	[PROVIDER_LAST_NAME] [varchar](50) NULL,
	[PROVIDER_ADDRESS] [varchar](500) NULL,
	[PROVIDER_CITY] [varchar](50) NULL,
	[PROVIDER_STATE] [varchar](2) NULL,
	[PROVIDER_TAXONOMY_DESC] [varchar](100) NULL,
	[PROVIDER_ZIP_CODE] [varchar](9) NULL,
	[PROVIDER_REGION] [varchar](50) NULL,
	[PROVIDER_REGION_CODE] [varchar](10) NULL,
	[PROVIDER_FAX] [varchar](10) NULL,
	[PROVIDER_PHONE_NO] [varchar](10) NULL,
	[PATIENT_FIRST_NAME] [varchar](50) NULL,
	[PATIENT_LAST_NAME] [varchar](50) NULL,
	[PATIENT_DOB] [datetime] NULL,
	[PATIENT_MOBILE_NO] [varchar](10) NULL,
	[PATIENT_EMAIL] [varchar](50) NULL,
	[PATIENT_SUBSCRIBER_ID] [varchar](25) NULL,
	[PATIENT_INSURANCE_PAYER_ID] [varchar](10) NULL,
	[IS_CHECK_ELIGIBILITY] [bit] NULL,
	[PATIENT_DISCIPLINE_ID] [varchar](50) NULL,
	[PATIENT_REFERRAL_NOTES] [varchar](500) NULL,
	[WORK_ID] [bigint] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_DATE] [datetime] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
	[PATIENT_ZIP_CODE] [varchar](9) NULL,
	[PATIENT_CITY_NAME] [varchar](50) NULL,
	[PATIENT_STATE] [varchar](2) NULL,
	[PATIENT_ADDRESS] [varchar](500) NULL,
 CONSTRAINT [PK__FOX_TBL___BC96F500A761BB87] PRIMARY KEY CLUSTERED 
(
	[FRICTIONLESS_REFERRAL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__CREAT__3FDCB949]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__CREAT__40D0DD82]  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__MODIF__41C501BB]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__MODIF__42B925F4]  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_FRICTIONLESS_REFERRAL] ADD  CONSTRAINT [DF__FOX_TBL_F__DELET__43AD4A2D]  DEFAULT ((0)) FOR [DELETED]
GO




