USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_SENDER]    Script Date: 7/21/2022 9:34:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_SENDER](
	[SENDER_ID] [bigint] NOT NULL,
	[SENDER_NAME] [varchar](100) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
 CONSTRAINT [PK__FOX_TBL___4EE891C873984C32] PRIMARY KEY CLUSTERED 
(
	[SENDER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[FOX_TBL_SENDER] ADD  CONSTRAINT [DF_FOX_TBL_SENDER_CREATED_BY]  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_SENDER] ADD  CONSTRAINT [DF__FOX_TBL_S__CREAT__287969DC]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_SENDER] ADD  CONSTRAINT [DF_FOX_TBL_SENDER_MODIFIED_BY]  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_SENDER] ADD  CONSTRAINT [DF__FOX_TBL_S__MODIF__2A61B24E]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_SENDER] ADD  CONSTRAINT [DF__FOX_TBL_S__DELET__2B55D687]  DEFAULT ((0)) FOR [DELETED]
GO

ALTER TABLE [dbo].[FOX_TBL_SENDER] ADD  CONSTRAINT [MSmerge_df_rowguid_DB82164528354F2D8FA2C653CEC4C682]  DEFAULT (newsequentialid()) FOR [rowguid]
GO


