USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PROGRESS_NOTE]    Script Date: 7/21/2022 9:27:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PROGRESS_NOTE](
	[PROGRESS_NOTE_ID] [bigint] NOT NULL,
	[APPOINTMENT_ID] [bigint] NULL,
	[PROGRESS_NOTE_APPOINTMENT_ID] [bigint] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PROGRESS_NOTE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PROGRESS_NOTE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_B2CDF509FB474070AD7C93E901FC9EF9]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_PROGRESS_NOTE] PRIMARY KEY CLUSTERED 
(
	[PROGRESS_NOTE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


