USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PASSWORD_HISTORY]    Script Date: 7/21/2022 9:10:44 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PASSWORD_HISTORY](
	[PASSWORD_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NOT NULL,
	[USER_ID] [bigint] NOT NULL,
	[PASSWORD] [varchar](255) NULL,
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PASSWORD_HISTORY_CREATED_DATE]  DEFAULT (getdate()),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PASSWORD_HISTORY_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PASSWORD_HISTORY_MODIFIED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PASSWORD_HISTORY_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PASSWORD_HISTORY_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_245642E211954E68BE73705E09BB5927]  DEFAULT (newsequentialid())
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


