USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PATIENT_PAT_DOCUMENT]    Script Date: 7/21/2022 9:18:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PATIENT_PAT_DOCUMENT](
	[PAT_DOCUMENT_ID] [bigint] NOT NULL,
	[PATIENT_ACCOUNT] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NOT NULL,
	[WORK_ID] [bigint] NULL,
	[DOCUMENT_TYPE] [int] NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[SHOW_ON_PATIENT_PORTAL] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_PAD_DOCUMENT_SHOW_ON_PATIENT_PORTAL]  DEFAULT ((0)),
	[COMMENTS] [varchar](1000) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_PAT_DOCUMENT_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_PAD_DOCUMENT_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_PAT_DOCUMENT_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_PAD_DOCUMENT_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_PAD_DOCUMENT_DELETED]  DEFAULT ((0)),
	[PARENT_DOCUMENT_ID] [bigint] NULL,
	[CASE_ID] [bigint] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_2769B7BD79E7490C8A516785C8A13771]  DEFAULT (newsequentialid()),
	[FOX_PHD_CALL_DETAILS_ID] [bigint] NULL,
 CONSTRAINT [PK_FOX_TBL_PATIENT_PAD_DOCUMENT] PRIMARY KEY CLUSTERED 
(
	[PAT_DOCUMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


