USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_DEFAULT_CALL_HANDLING_VALUES]    Script Date: 7/21/2022 9:50:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_DEFAULT_CALL_HANDLING_VALUES](
	[DAEAULT_HANDLING_ID] [bigint] NOT NULL,
	[USER_ID] [bigint] NULL,
	[PHD_CALL_SCENARIO_ID] [bigint] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[DELETED] [bit] NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](255) NULL,
	[MODIFIED_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[DAEAULT_HANDLING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


