CREATE TABLE [dbo].[FOX_TBL_CONSENT_FORM](
	[FOX_TBL_CONSENT_FORM_ID] [bigint] NOT NULL,
	[CONSENT_FORM_TITLE] [varchar](max) NULL,
	[CONSENT_FORM_DEFINATION] [varchar](max) NULL,
	[CONSENT_FORM_DOWNLOAD_LINK] [varchar](250) NULL,
	[CONSENT_FORM_BILL_OF_RIGHT] [varchar](250) NULL,
	[CONSENT_FORM_INSURENACE_COVERGAE] [varchar](250) NULL,
	[CONSENT_FORM_SIGN_PAD] [varchar](250) NULL,
	[CONSENT_FORM_SIGN_PAD_HYPER_LINK] [varchar](250) NULL,
	[CONSENT_FORM_CONTACT_US] [varchar](250) NULL,
	[CONSENT_FORM_CONTACT_US_HYPER_LINK] [varchar](250) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NULL,
	[CONSENT_FORM_HTML_TEMPLATE_PORTAL] [varchar](max) NULL,
	[CONSENT_FORM_HTML_TEMPLATE_TRAX] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[FOX_TBL_CONSENT_FORM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_FORM] ADD  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_FORM] ADD  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_FORM] ADD  DEFAULT ((0)) FOR [DELETED]
GO