USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_WORK_TRANSFER]    Script Date: 7/21/2022 9:41:34 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_WORK_TRANSFER](
	[WORK_TRANFER_ID] [bigint] NOT NULL,
	[WORK_ID] [bigint] NULL,
	[TRANSFER_COMMENTS] [varchar](3000) NULL,
	[TRANSFER_REASON] [varchar](500) NULL,
	[TRANSFER_BY] [varchar](70) NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_WORK_TRANSFER_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_W__MODIF__798970C9]  DEFAULT (getdate()),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_WORK_TRANSFER_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_W__CREAT__7B71B93B]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_W__DELET__7C65DD74]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_497EA9660E9240B69001F9DDE0102218]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK__FOX_TBL___C3E4C07EF7E95BE2] PRIMARY KEY CLUSTERED 
(
	[WORK_TRANFER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


