USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_SPLASH]    Script Date: 7/21/2022 10:03:23 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_SPLASH](
	[FOX_SPLASH_ID] [bigint] NOT NULL,
	[SPLASH_TYPE] [varchar](500) NOT NULL,
	[USER_ID] [bigint] NOT NULL,
	[USER_NAME] [varchar](70) NOT NULL,
	[SHOW_COUNT] [bigint] NOT NULL CONSTRAINT [DF_FOX_TBL_SPLASH_SHOW_COUNT]  DEFAULT ((0)),
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_SPLASH_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_SPLASH_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_SPLASH_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_SPLASH_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_SPLASH_DELETED]  DEFAULT ((0)),
 CONSTRAINT [PK_FOX_TBL_SPLASH] PRIMARY KEY CLUSTERED 
(
	[FOX_SPLASH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


