USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_DISCOUNT]    Script Date: 7/21/2022 8:54:07 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_DISCOUNT](
	[PR_DISCOUNT_ID] [int] NOT NULL,
	[TYPE] [varchar](50) NOT NULL,
	[CODE] [varchar](50) NOT NULL,
	[PERCENTAGE] [money] NOT NULL,
	[PRACTICE_CODE] [bigint] NOT NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_DISCOUNT_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_DISCOUNT_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_DISCOUNT_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_DISCOUNT_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_DISCOUNT_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_F56270514BE549F9AC86FF99A777FC12]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_DISCOUNT] PRIMARY KEY CLUSTERED 
(
	[PR_DISCOUNT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


