USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_COMMUNICATION_STATUS_OF_CARE]    Script Date: 7/21/2022 8:51:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_COMMUNICATION_STATUS_OF_CARE](
	[FOX_CARE_STATUS_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CARE_STATUS_NAME] [varchar](50) NOT NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_COMMUNICATION_STATUS_OF_CARE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_COMMUNICATION_STATUS_OF_CARE_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_COMMUNICATION_STATUS_OF_CARE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_COMMUNICATION_STATUS_OF_CARE_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_COMMUNICATION_STATUS_OF_CARE_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_7021D11B1EBE4EB79F8B20175738D282]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_COMMUNICATION_STATUS_OF_CARE] PRIMARY KEY CLUSTERED 
(
	[FOX_CARE_STATUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


