USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PATIENT_DOCUMENTS]    Script Date: 7/21/2022 9:17:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PATIENT_DOCUMENTS](
	[PAT_DOC_ID] [bigint] NOT NULL,
	[PATIENT_ACCOUNT] [bigint] NOT NULL,
	[WORK_ID] [bigint] NULL,
	[PROC_CODE] [bigint] NULL,
	[COMENTS] [varchar](20) NULL,
	[FILE_PATH] [varchar](500) NULL,
	[FILE_NAME] [varchar](500) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_DOCUMENTS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_P__CREAT__2D732923]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_DOCUMENTS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF__FOX_TBL_P__MODIF__2F5B7195]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_P__DELET__304F95CE]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_6C39E13C91C74CF78F4A599CAE6378FF]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK__FOX_TBL___79DAB8377E032B72] PRIMARY KEY CLUSTERED 
(
	[PAT_DOC_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


