USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_APP_USER_ADDITIONAL_INFO]    Script Date: 7/21/2022 9:44:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_APP_USER_ADDITIONAL_INFO](
	[FOX_USER_ADDITIONAL_INFO_ID] [bigint] NOT NULL,
	[FOX_TBL_APPLICATION_USER_ID] [bigint] NOT NULL,
	[IS_ELECTRONIC_POC] [bit] NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[DELETED] [bit] NOT NULL,
 CONSTRAINT [PK__fox_tbl___3214EC07DE88BF8E] PRIMARY KEY CLUSTERED 
(
	[FOX_USER_ADDITIONAL_INFO_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


