USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_ELIG_HTML]    Script Date: 7/21/2022 9:50:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_ELIG_HTML](
	[ELIG_HTML_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[PATIENT_INSURANCE_ID] [bigint] NULL,
	[ELIG_HTML] [text] NULL,
	[CREATED_BY] [varchar](255) NOT NULL CONSTRAINT [DF_FOX_TBL_ELIG_HTML_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_ELIG_HTML_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](255) NOT NULL CONSTRAINT [DF_FOX_TBL_ELIG_HTML_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_ELIG_HTML_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_ELIG_HTML_DELETED]  DEFAULT ((0)),
 CONSTRAINT [PK_FOX_TBL_ELIG_HTML] PRIMARY KEY CLUSTERED 
(
	[ELIG_HTML_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


