USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PHD_CALL_DETAILS]    Script Date: 7/21/2022 9:23:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PHD_CALL_DETAILS](
	[FOX_PHD_CALL_DETAILS_ID] [bigint] NOT NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[MRN] [varchar](100) NULL,
	[DOS] [datetime] NULL,
	[CALL_SCENARIO] [varchar](10) NULL,
	[CALL_DATE] [datetime] NULL,
	[CALL_TIME] [datetime] NULL,
	[CALL_DURATION] [varchar](3) NULL,
	[CALL_REASON] [varchar](50) NULL,
	[CALLER_NAME] [varchar](100) NULL,
	[RELATIONSHIP] [varchar](10) NULL,
	[INCOMING_CALL_NO] [varchar](10) NULL,
	[PATIENT_EMAIL_ADDRESS] [varchar](255) NULL,
	[REQUEST] [varchar](50) NULL,
	[CALL_ATTENDED_BY] [varchar](70) NULL,
	[CALL_DETAILS] [varchar](1000) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALL_DETAILS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALL_DETAILS_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALL_DETAILS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALL_DETAILS_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_P__DELET__2A56F720]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_97124F01FDFC4E74B83794C4AFF73022]  DEFAULT (newsequentialid()),
	[CURRENT_EXTENSION] [varchar](5) NULL,
	[CALL_RECORDING_PATH] [varchar](70) NULL,
	[GENERAL_NOTE_ID] [bigint] NULL,
	[AMOUNT] [money] NULL,
	[CALL_CATEGORY_ID] [bigint] NULL,
	[PRIORITY] [varchar](25) NULL,
	[FOLLOW_UP_DATE] [datetime] NULL,
	[SSCM_CASE_ID] [varchar](50) NULL,
	[FILE_PATH] [varchar](500) NULL,
 CONSTRAINT [PK_FOX_TBL_PHD_CALL_DETAILS] PRIMARY KEY CLUSTERED 
(
	[FOX_PHD_CALL_DETAILS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


