USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PATIENT_SURVEY_DELETED_RECORDS]    Script Date: 7/21/2022 9:20:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_DELETED_RECORDS](
	[SURVEY_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[FACILITY_OR_CLIENT_ID] [varchar](100) NULL,
	[PATIENT_ACCOUNT_NUMBER] [bigint] NULL,
	[RESPONSIBLE_PARTY_LAST_NAME] [varchar](50) NULL,
	[RESPONSIBLE_PARTY_FIRST_NAME] [varchar](50) NULL,
	[RESPONSIBLE_PARTY_MIDDLE_INITIAL] [char](1) NULL,
	[RESPONSIBLE_PARTY_ADDRESS] [varchar](500) NULL,
	[RESPONSIBLE_PARTY_CITY] [varchar](50) NULL,
	[RESPONSIBLE_PARTY_STATE] [char](2) NULL,
	[RESPONSIBLE_PARTY_ZIP_CODE] [varchar](20) NULL,
	[RESPONSIBLE_PARTY_TELEPHONE] [varchar](20) NULL,
	[RESPONSIBLE_PARTY_SSN] [char](20) NULL,
	[RESPONSIBLE_PARTY_SEX] [varchar](15) NULL,
	[RESPONSIBLE_PARTY_DATE_OF_BIRTH] [datetime] NULL,
	[PATIENT_LAST_NAME] [varchar](50) NULL,
	[PATIENT_FIRST_NAME] [varchar](50) NULL,
	[PATIENT_MIDDLE_INITIAL] [char](1) NULL,
	[PATIENT_ADDRESS] [varchar](500) NULL,
	[PATIENT_CITY] [varchar](50) NULL,
	[PATIENT_STATE] [char](2) NULL,
	[PATIENT_ZIP_CODE] [varchar](20) NULL,
	[PATIENT_TELEPHONE_NUMBER] [varchar](20) NULL,
	[PATIENT_SOCIAL_SECURITY_NUMBER] [char](20) NULL,
	[PATIENT_GENDER] [varchar](15) NULL,
	[PATIENT_DATE_OF_BIRTH] [datetime] NULL,
	[ALTERNATE_CONTACT_LAST_NAME] [varchar](50) NULL,
	[ALTERNATE_CONTACT_FIRST_NAME] [varchar](50) NULL,
	[ALTERNATE_CONTACT_MIDDLE_INITIAL] [char](1) NULL,
	[ALTERNATE_CONTACT_TELEPHONE] [varchar](10) NULL,
	[EMR_LOCATION_CODE] [varchar](50) NULL,
	[EMR_LOCATION_DESCRIPTION] [varchar](200) NULL,
	[SERVICE_OR_PAYMENT_DESCRIPTION] [varchar](200) NULL,
	[PROVIDER] [varchar](50) NULL,
	[REGION] [varchar](50) NULL,
	[LAST_VISIT_DATE] [datetime] NULL,
	[DISCHARGE_DATE] [datetime] NULL,
	[ATTENDING_DOCTOR_NAME] [varchar](50) NULL,
	[PT_OT_SLP] [varchar](10) NULL,
	[REFERRAL_DATE] [datetime] NULL,
	[PROCEDURE_OR_TRAN_CODE] [varchar](50) NULL,
	[SERVICE_OR_PAYMENT_AMOUNT] [money] NULL,
	[IS_CONTACT_HQ] [bit] NULL,
	[IS_RESPONSED_BY_HQ] [bit] NULL,
	[IS_REFERABLE] [bit] NULL,
	[IS_IMPROVED_SETISFACTION] [bit] NULL,
	[FEEDBACK] [varchar](3000) NULL,
	[SURVEY_FLAG] [varchar](50) NULL,
	[SURVEY_STATUS_BASE] [varchar](50) NULL,
	[SURVEY_STATUS_CHILD] [varchar](50) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_DELETED_RECORDS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_DELETED_RECORDS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL,
	[IS_SURVEYED] [bit] NOT NULL,
	[FILE_NAME] [varchar](200) NULL,
	[SHEET_NAME] [varchar](200) NULL,
	[TOTAL_RECORD_IN_FILE] [bigint] NULL,
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_SURVEY_DELETED_RECORDS_DELETED]  DEFAULT ((0)),
	[IN_PROGRESS] [bit] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_AB2661C417FE4F7D9D9B1CD7D2FB954E]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_PATIENT_SURVEY_DELETED_RECORDS] PRIMARY KEY CLUSTERED 
(
	[SURVEY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


