USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PHD_CALL_PATIENT_VERIFICATION]    Script Date: 7/21/2022 9:23:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PHD_CALL_PATIENT_VERIFICATION](
	[FOX_PHD_CALL_PATIENT_VERIFICATION_ID] [bigint] NOT NULL,
	[PATIENT_ACCOUNT] [bigint] NULL,
	[IS_PATIENT_ACCOUNT_VERIFIED] [bit] NULL,
	[IS_PATIENT_MRN_VERIFIED] [bit] NULL,
	[IS_PATIENT_LAST_NAME_VERIFIED] [bit] NULL,
	[IS_PATIENT_FIRST_NAME_VERIFIED] [bit] NULL,
	[IS_PATIENT_DOB_VERIFIED] [bit] NULL,
	[IS_PATIENT_AGE_VERIFIED] [bit] NULL,
	[IS_PATIENT_SSN_VERIFIED] [bit] NULL,
	[IS_PATIENT_ADDRESS_VERIFIED] [bit] NULL,
	[IS_PATIENT_EMAIL_ADDRESS_VERIFIED] [bit] NULL,
	[IS_PATIENT_HOME_PHONE_VERIFIED] [bit] NULL,
	[IS_PATIENT_CELL_PHONE_VERIFIED] [bit] NULL,
	[LAST_VERIFIED_DATE] [datetime] NOT NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALL_PATIENT_VERIFICATION_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALL_PATIENT_VERIFICATION_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALL_PATIENT_VERIFICATION_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALL_PATIENT_VERIFICATION_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PHD_CALL_PATIENT_VERIFICATION_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_3C09867B98244792950B0BC9E1F2EEC3]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_PHD_CALL_PATIENT_VERIFICATION] PRIMARY KEY CLUSTERED 
(
	[FOX_PHD_CALL_PATIENT_VERIFICATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


