USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PATIENT_SURVEY_INBOUND_CALL]    Script Date: 1/27/2023 5:31:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_INBOUND_CALL](
	[SURVEY_INBOUND_CALL_ID] [bigint] NOT NULL,
	[CALL_DATE] [datetime] NULL,
	[CALL_START_TIME] [datetime] NULL,
	[CALL_END_TIME] [datetime] NULL,
	[CALL_NO] [varchar](10) NULL,
	[CALL_BY] [varchar](70) NULL,
	[IS_INCOMING] [bit] NULL,
	[OFFICE_NAME] [varchar](20) NULL,
	[EXTENSION] [varchar](5) NULL,
	[CALL_RECORDING_PATH] [varchar](500) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[SURVEY_INBOUND_CALL_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_INBOUND_CALL] ADD  DEFAULT ('FOX_TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_INBOUND_CALL] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_INBOUND_CALL] ADD  DEFAULT ('FOX_TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_INBOUND_CALL] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_PATIENT_SURVEY_INBOUND_CALL] ADD  DEFAULT ((0)) FOR [DELETED]
GO


