USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_RECONCILIATION_FILES]    Script Date: 7/21/2022 9:30:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_RECONCILIATION_FILES](
	[RECONCILIATION_FILE_ID] [bigint] NOT NULL,
	[RECONCILIATION_ID] [bigint] NULL,
	[RECONCILIATION_CATEGORY] [varchar](50) NULL,
	[LOGO_PATH] [varchar](500) NULL,
	[IMAGE_PATH] [varchar](500) NULL,
	[CREATED_BY] [varchar](70) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
 CONSTRAINT [PK_FOX_TBL_RECONCILIATION_FILES] PRIMARY KEY CLUSTERED 
(
	[RECONCILIATION_FILE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[FOX_TBL_RECONCILIATION_FILES] ADD  CONSTRAINT [DF_FOX_TBL_RECONCILIATION_FILES_CREATED_BY]  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_RECONCILIATION_FILES] ADD  CONSTRAINT [DF_FOX_TBL_RECONCILIATION_FILES_CREATED_DATE]  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_RECONCILIATION_FILES] ADD  CONSTRAINT [DF_FOX_TBL_RECONCILIATION_FILES_MODIFIED_BY]  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_RECONCILIATION_FILES] ADD  CONSTRAINT [DF_FOX_TBL_RECONCILIATION_FILES_MODIFIED_DATE]  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_RECONCILIATION_FILES] ADD  CONSTRAINT [DF_FOX_TBL_RECONCILIATION_FILES_DELETED]  DEFAULT ((0)) FOR [DELETED]
GO

ALTER TABLE [dbo].[FOX_TBL_RECONCILIATION_FILES] ADD  CONSTRAINT [MSmerge_df_rowguid_7323B5DF543447F7A1F92BE266EDE104]  DEFAULT (newsequentialid()) FOR [rowguid]
GO


