USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PATIENT_ADDRESS_ADDITIONAL_INFO]    Script Date: 7/21/2022 9:54:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PATIENT_ADDRESS_ADDITIONAL_INFO](
	[PATIENT_ADDRESS_ADDITIONAL_INFO] [bigint] NOT NULL,
	[PATIENT_ADDRESS_HISTORY_ID] [bigint] NULL,
	[WORK_ID] [bigint] NULL,
	[Longitude] [float] NULL,
	[Latitude] [float] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_ADDRESS_ADDITIONAL_INFO_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_ADDRESS_ADDITIONAL_INFO_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_ADDRESS_ADDITIONAL_INFO_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_ADDRESS_ADDITIONAL_INFO_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_PATIENT_ADDRESS_ADDITIONAL_INFO_DELETED]  DEFAULT ((0)),
 CONSTRAINT [PK_FOX_TBL_PATIENT_ADDRESS_ADDITIONAL_INFO] PRIMARY KEY CLUSTERED 
(
	[PATIENT_ADDRESS_ADDITIONAL_INFO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


