USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_SENDER_NAME]    Script Date: 7/21/2022 9:34:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_SENDER_NAME](
	[FOX_TBL_SENDER_NAME_ID] [bigint] NOT NULL,
	[FOX_TBL_SENDER_TYPE_ID] [bigint] NULL,
	[SENDER_NAME_CODE] [varchar](70) NULL,
	[SENDER_NAME_DESCRIPTION] [varchar](300) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_NAME_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_NAME_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_NAME_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_NAME_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_SENDER_NAME_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_BBAFDE67CC4446CA933B671A60FB7113]  DEFAULT (newsequentialid())
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


