USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_EMAIL_FAX_LOG]    Script Date: 7/21/2022 9:51:15 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_EMAIL_FAX_LOG](
	[FOX_EMAIL_FAX_LOG_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NOT NULL,
	[TYPE] [varchar](10) NULL,
	[FROM] [varchar](100) NULL,
	[TO] [varchar](100) NULL,
	[CC] [varchar](500) NULL,
	[BCC] [varchar](500) NULL,
	[ATTACHMENT_PATH] [varchar](500) NULL,
	[STATUS] [varchar](200) NULL,
	[EXCEPTION_SHORT_MSG] [varchar](1000) NULL,
	[EXCEPTION_TRACE] [varchar](5000) NULL,
	[WORK_ID] [bigint] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_EMAIL_FAX_LOG_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_EMAIL_FAX_LOG_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_EMAIL_FAX_LOG_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_EMAIL_FAX_LOG_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_EMAIL_FAX_LOG_DELETED]  DEFAULT ((0)),
	[WORK_STATUS] [varchar](20) NULL,
	[Body] [varchar](2000) NULL,
 CONSTRAINT [PK_FOX_TBL_EMAIL_FAX_LOG] PRIMARY KEY CLUSTERED 
(
	[FOX_EMAIL_FAX_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


