USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_AUTH]    Script Date: 7/21/2022 8:43:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_AUTH](
	[AUTH_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[AUTH_UNIQUE_ID] [varchar](50) NULL,
	[AUTH_PARENT_ID] [bigint] NULL,
	[Parent_Patient_insurance_Id] [bigint] NULL,
	[RECORD_DATE] [datetime] NULL,
	[RECORD_TIME] [datetime] NULL,
	[REQUESTED_ON] [datetime] NULL,
	[RECEIVED_ON] [datetime] NULL,
	[REQUESTED_VISITS] [int] NULL,
	[EFFECTIVE_FROM] [datetime] NULL,
	[EFFECTIVE_TO] [datetime] NULL,
	[AUTH_STATUS_ID] [int] NULL,
	[CASE_ID] [bigint] NULL,
	[DISCIPLINE_ID] [int] NULL,
	[BILLING_PROVIDER_ID] [bigint] NULL,
	[AUTH_NUMBER] [varchar](100) NULL,
	[REFERRED_BY_ID] [bigint] NULL,
	[VERIFIED_BY] [varchar](70) NULL,
	[LOC_ID] [bigint] NULL,
	[MULT_VALUE] [money] NULL,
	[MULT_VALUE_TYPE_ID] [int] NULL,
	[MULT_USED] [money] NULL,
	[MULT_REMAINING]  AS ([MULT_VALUE]-[MULT_USED]),
	[IS_AS_ONE] [bit] NULL,
	[TOTAL] [money] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_AUTH_DELETED]  DEFAULT ((0)),
	[ISSIMPLE] [bit] NULL,
	[BILLCODE] [varchar](150) NULL,
	[SimpleAllowded] [int] NULL,
	[SimpleUsed] [int] NULL,
	[BILLING_PROVIDER_ID_6906] [bigint] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_42BBF873437149B8AAB07A8CF33E154F]  DEFAULT (newsequentialid()),
	[FOX_GUID] [varchar](50) NULL,
 CONSTRAINT [PK_FOX_TBL_AUTH] PRIMARY KEY CLUSTERED 
(
	[AUTH_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


