USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_ACTIVE_INDEXER_LOGS]    Script Date: 7/21/2022 9:43:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_ACTIVE_INDEXER_LOGS](
	[ACTIVE_INDEXER_LOG_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[INDEXER] [varchar](255) NULL,
	[LOG_MESSAGE] [varchar](500) NULL,
	[CREATED_BY] [varchar](255) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](255) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ACTIVE_INDEXER_LOG_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


