USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_APPOINTMENT_STATUS]    Script Date: 7/21/2022 8:43:14 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_APPOINTMENT_STATUS](
	[APPOINTMENT_STATUS_ID] [bigint] NOT NULL,
	[DESCRIPTION] [varchar](50) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_APPOINTMENT_STATUS_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_APPOINTMENT_STATUS_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NULL,
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_C09E4615CB784D7AAFF8BD4AC4DD166F]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_APPOINTMENT_STATUS] PRIMARY KEY CLUSTERED 
(
	[APPOINTMENT_STATUS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


