USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_BLACKLISTED_WHITELISTED_SOURCE]    Script Date: 7/21/2022 9:46:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_BLACKLISTED_WHITELISTED_SOURCE](
	[BLACKLISTED_WHITELISTED_SOURCE_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[SOURCE_TYPE] [varchar](30) NULL,
	[SOURCE_NAME] [varchar](255) NULL,
	[IS_BLACK_LISTED] [bit] NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_BLACKLISTED_WHITELISTED_SOURCE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_BLACKLISTED_WHITELISTED_SOURCE_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_BLACKLISTED_WHITELISTED_SOURCE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX_TBL_BLACKLISTED_WHITELISTED_SOURCE_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX_TBL_BLACKLISTED_WHITELISTED_SOURCE_DELETED]  DEFAULT ((0)),
 CONSTRAINT [PK_FOX_TBL_BLACKLISTED_WHITELISTED_SOURCE] PRIMARY KEY CLUSTERED 
(
	[BLACKLISTED_WHITELISTED_SOURCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


