CREATE TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_DOCUMENTS](
	[DOCUMENTS_ID] [bigint] NOT NULL,
	[CONSENT_TO_CARE_ID] [bigint] NULL,
	[LOGO_PATH] [varchar](500) NULL,
	[IMAGE_PATH] [varchar](500) NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[CREATED_BY] [varchar](70) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](70) NULL,
	[DELETED] [bit] NULL,
	[DOCUMENT_TYPE_ID] [bigint] NULL,
	[IsSigned] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[DOCUMENTS_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_DOCUMENTS] ADD  DEFAULT ('FOX TEAM') FOR [CREATED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_DOCUMENTS] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_DOCUMENTS] ADD  DEFAULT (getdate()) FOR [MODIFIED_DATE]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_DOCUMENTS] ADD  DEFAULT ('FOX TEAM') FOR [MODIFIED_BY]
GO

ALTER TABLE [dbo].[FOX_TBL_CONSENT_TO_CARE_DOCUMENTS] ADD  DEFAULT ((0)) FOR [DELETED]
GO

GO