USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_INSURANCE]    Script Date: 7/21/2022 9:04:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_INSURANCE](
	[FOX_TBL_INSURANCE_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[INSURANCE_PAYERS_ID] [varchar](10) NULL,
	[INSURANCE_NAME] [varchar](100) NULL,
	[PAYING_AGENCY] [varchar](100) NULL,
	[PAYER_TYPE] [varchar](10) NULL,
	[PLAN_CODE] [varchar](100) NULL,
	[ADDRESS] [varchar](100) NULL,
	[INSURANCE_ID] [bigint] NULL,
	[ADDRESS_1] [varchar](100) NULL,
	[CITY] [varchar](50) NULL,
	[STATE] [varchar](2) NULL,
	[ZIP] [varchar](9) NULL,
	[COUNTY] [varchar](50) NULL,
	[PHONE] [varchar](20) NULL,
	[FAX] [varchar](20) NULL,
	[FIELD_SET] [varchar](50) NULL,
	[ALLOW_CONCURRENT_THERAPY] [varchar](50) NULL,
	[ALLOW_CO_TREATMENT] [varchar](50) NULL,
	[CCI_VALIDATION] [varchar](50) NULL,
	[MODIFIER_KX] [varchar](50) NULL,
	[MODIFIER_52_APPLIES] [varchar](50) NULL,
	[CAP_TRACKING] [varchar](50) NULL,
	[MPPR_ADJUSTED] [varchar](50) NULL,
	[PQRS] [varchar](50) NULL,
	[FUNCTIONAL_LIMITATIONS_REPORTING] [varchar](50) NULL,
	[EIGHT_MIN_RULE_CALCULATION_METHOD] [varchar](50) NULL,
	[BILL_FORM] [varchar](50) NULL,
	[ELECTRONIC_SUBMISSION] [varchar](50) NULL,
	[CLAIM_FILING_INDICATOR_CODE] [varchar](500) NULL,
	[SUBSEQUENT_ELECTRONIC_CLAIM] [varchar](50) NULL,
	[SEPARATE_CLAIM_FOR_EACH_DISCIPLINE] [bit] NULL,
	[REBILL_REQUIRES_DCN] [bit] NULL,
	[INCLUDE_ZEROPOINT_ONE_CHARGES_ON_PROFESSIONAL_CLAIMS_SUBMITTED_AFTER_PRIMARY_INSTITUTIONAL_CLAIMS] [bit] NULL,
	[APPLY_SEQUESTRATION_ADJUSTMENT] [bit] NULL,
	[SEPARATE_PROFESSIONAL_CLAIM_BY_RENDERING_THERAPIST_NPI] [bit] NULL,
	[RIM_HOLDS_WILL_PREVENT_CLAIMS_FROM_RELEASING] [bit] NULL,
	[PHYSICIAN_REQUIREMENT_NPI] [bit] NULL,
	[RENDERING_PROVIDER_REQUIRES_NPI] [bit] NULL,
	[RENDERING_PROVIDER_REQUIRES_STATE_LICENSE] [bit] NULL,
	[RENDERING_PROVIDER_REQUIRES_TAXONOMY] [bit] NULL,
	[REQUIRE_ADMITTING_DIAGNOSIS] [bit] NULL,
	[PHONE_NUMBER_FOR_AUTHORIZATIONS] [varchar](50) NULL,
	[TIMELY_FILING_LIMIT] [int] NULL,
	[OUTPATIENT_PRIOR_AUTHORIZATION_REQUIRED] [bit] NULL,
	[OUTPATIENT_INCLUDE_KX_MODIFIER_ON_CLAIMS] [bit] NULL,
	[OUTPATIENT_APPLY_KX_TO_ENTIRE_CLAIM_PERIOD] [bit] NULL,
	[OUTPATIENT_INCLUDE_59_MODIFIER_ON_CLAIMS] [bit] NULL,
	[RENDERING_PROVIDER_CREDENTIALING_REQUIREMENTS] [varchar](100) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_INSURANCE_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NULL CONSTRAINT [DF__FOX_TBL_I__CREAT__10B720AE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_INSURANCE_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NULL CONSTRAINT [DF__FOX_TBL_I__MODIF__129F6920]  DEFAULT (getdate()),
	[DELETED] [bit] NULL CONSTRAINT [DF__FOX_TBL_I__DELET__13938D59]  DEFAULT ((0)),
	[IS_CCI_VALIDATION] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_I__IS_CC__424E7C42]  DEFAULT ((0)),
	[IS_MODIFIER_KX] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_I__IS_MO__4342A07B]  DEFAULT ((0)),
	[IS_CAP_TRACKING] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_I__IS_CA__4436C4B4]  DEFAULT ((0)),
	[IS_PQRS] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_I__IS_PQ__452AE8ED]  DEFAULT ((0)),
	[IS_FUNCTIONAL_LIMITATIONS_REPORTING] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_I__IS_FU__461F0D26]  DEFAULT ((0)),
	[FINANCIAL_CLASS_ID] [int] NULL,
	[Is_Authorization_Required] [bit] NOT NULL CONSTRAINT [DF__FOX_TBL_I__Is_Au__1374F6AC]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_0E0DD161905C49E4A3BC19C37275458B]  DEFAULT (newsequentialid()),
	[FEE_REDIRECT] [varchar](10) NULL,
	[CARRIER_STATE] [varchar](2) NULL,
	[CARRIER_LOCALITY] [varchar](10) NULL,
	[CARRIER] [varchar](10) NULL,
 CONSTRAINT [PK_FOX_TBL_INSURANCE_6906] PRIMARY KEY CLUSTERED 
(
	[FOX_TBL_INSURANCE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


