USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_APPLICATION_USER_CLAIMS]    Script Date: 7/21/2022 9:44:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_APPLICATION_USER_CLAIMS](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [varchar](128) NULL,
	[ClaimType] [varchar](100) NULL,
	[ClaimValue] [varchar](500) NULL,
	[IdentityUser_Id] [varchar](128) NULL,
 CONSTRAINT [PK_dbo.FOX_TBL_APPLICATION_USER_CLAIMS] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


