USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_CANCELLATION_REASON]    Script Date: 7/21/2022 9:46:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_CANCELLATION_REASON](
	[CANCELLATION_REASON_ID] [bigint] NOT NULL,
	[CANCELLATION_CODE] [varchar](50) NULL,
	[CANCELLATION_DESCRIPTION] [varchar](255) NULL,
	[RT_CANCELLATION_CODE] [varchar](50) NULL,
	[CREATED_BY] [varchar](255) NOT NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](255) NOT NULL,
	[MODIFIED_DATE] [datetime] NOT NULL,
	[DELETED] [bit] NOT NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


