USE [MIS_DB]
GO

/****** Object:  Table [dbo].[FOX_TBL_PRIMARY_PAYER]    Script Date: 7/21/2022 9:26:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[FOX_TBL_PRIMARY_PAYER](
	[PRIMARY_PAYER_ID] [bigint] NOT NULL,
	[PRACTICE_CODE] [bigint] NULL,
	[STATE] [varchar](10) NULL,
	[FEE_SCHEDULE_LOCALITY] [varchar](50) NULL,
	[INSURANCE_CODE] [varchar](50) NULL,
	[PAYER_NAME] [varchar](250) NULL,
	[RR_PTS] [varchar](50) NULL,
	[COUNTIES] [varchar](1000) NULL,
	[CREATED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PRIMARY_PAYER_CREATED_BY]  DEFAULT ('FOX TEAM'),
	[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX-TBL_PRIMARY_PAYER_CREATED_DATE]  DEFAULT (getdate()),
	[MODIFIED_BY] [varchar](70) NOT NULL CONSTRAINT [DF_FOX_TBL_PRIMARY_PAYER_MODIFIED_BY]  DEFAULT ('FOX TEAM'),
	[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_FOX-TBL_PRIMARY_PAYER_MODIFIED_DATE]  DEFAULT (getdate()),
	[DELETED] [bit] NOT NULL CONSTRAINT [DF_FOX-TBL_PRIMARY_PAYER_DELETED]  DEFAULT ((0)),
	[rowguid] [uniqueidentifier] ROWGUIDCOL  NOT NULL CONSTRAINT [MSmerge_df_rowguid_7C0C25D2DF4646C38BCCE3C940DBC444]  DEFAULT (newsequentialid()),
 CONSTRAINT [PK_FOX_TBL_PRIMARY_PAYER] PRIMARY KEY CLUSTERED 
(
	[PRIMARY_PAYER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


