USE [MIS_DB]
GO

/****** Object:  Table [dbo].[MTBCSOFT_TBL_FOLLOWUP_NOTES]    Script Date: 7/21/2022 9:42:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MTBCSOFT_TBL_FOLLOWUP_NOTES](
	[NOTE_ID] [bigint] NOT NULL,
	[PARENT_NOTE_ID] [bigint] NULL,
	[CLAIM_NO] [bigint] NULL,
	[DETAILS] [varchar](6000) NULL,
	[FOLLOWED_BY] [varchar](50) NULL,
	[FOLLOW_UP_DATE] [datetime] NULL,
	[STATUS] [char](5) NULL,
	[STATUS_BY] [varchar](50) NULL,
	[STATUS_DATE] [datetime] NULL,
	[DELETED] [bit] NULL,
	[CREATED_BY] [varchar](50) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](50) NULL,
	[MODIFIED_DATE] [datetime] NULL,
 CONSTRAINT [PK_FOLLOW_UP_NOTE_ID] PRIMARY KEY CLUSTERED 
(
	[NOTE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


