USE [MIS_DB]
GO

/****** Object:  Table [dbo].[MTBCSOFT_TBL_CASH_PROJECTION]    Script Date: 7/21/2022 9:42:13 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MTBCSOFT_TBL_CASH_PROJECTION](
	[CASH_PROJECTION_ID] [bigint] NOT NULL,
	[PARENT_ID] [bigint] NULL,
	[INSPAYER_ID] [bigint] NULL,
	[FEE_SCHEDULER_MULTIPLIER] [money] NULL,
	[EFFECTIVE_FROM] [datetime] NULL,
	[EFFECTIVE_TO] [datetime] NULL,
	[DELETED] [bigint] NULL,
	[CREATED_BY] [varchar](25) NULL,
	[CREATED_DATE] [datetime] NULL,
	[MODIFIED_BY] [varchar](25) NULL,
	[MODIFIED_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[CASH_PROJECTION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


