--------------------------------------------------------
----- Folder Name: SupportScripts > DataModifications
----- File Name: DataModifications.sql	
----- Created By: Muhammad Arslan Tufail
----- Created Date: 08/25/2022
----- Modified By: Muhammad Arslan Tufail
----- Modified Date: 08/25/2022
--------------------------------------------------------