IF (OBJECT_ID('AF_PROC_GETINTERFAXDETAILS') IS NOT NULL) DROP PROCEDURE AF_PROC_GETINTERFAXDETAILS
GO
CREATE PROCEDURE [dbo].[AF_PROC_GETINTERFAXDETAILS]      
@PRAC_CODE BIGINT      
AS       
BEGIN        
--DECLARE @PRAC_CODE BIGINT    = 1013140  
    SELECT ISNULL([INTERFAX_NO],'') AS [INTERFAX_NO] ,ISNULL([INTERFAX_USERNAME],'') AS [INTERFAX_USERNAME] ,  
 ISNULL([INTERFAX_PASSWORD],'') AS [INTERFAX_PASSWORD],isnull([ACC_COMPANY],'') AS [ACC_COMPANY],   
 PRACTICE_CODE AS PRACTICE_CODE , ENABLE_FAX AS enable_fax  
  
FROM [PRACTICES_PROFILE_OTHER_INFO]   
WHERE [PRACTICE_CODE] = @PRAC_CODE     
  
END      

