IF (OBJECT_ID('FOX_PROC_GET_ROLE_RIGHTS_USER') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_ROLE_RIGHTS_USER  
GO  
--------------------------------------------------------------------------------------  
CREATE Procedure [dbo].[FOX_PROC_GET_ROLE_RIGHTS_USER] --'1011163','1163TESTING'      
(      
 @PRACTICE_CODE bigint,    
 @USER_NAME  VARCHAR(50)    
)      
AS      
BEGIN     
DECLARE @USERROLE VARCHAR(50);    
SET  @USERROLE= (SELECT R.ROLE_NAME FROM FOX_TBL_APPLICATION_USER UR     
INNER JOIN FOX_TBL_ROLE R ON R.ROLE_ID=UR.ROLE_ID     
WHERE USER_NAME=@USER_NAME)    
SET NOCOUNT ON;      
SELECT R.ROLE_ID,ROLE_NAME,RI.RIGHT_ID,RI.RIGHT_NAME,convert(bit,isnull(PR.CHECKED,0)) as IS_CHECKED,ISNULL(PR.RIGHTS_OF_ROLE_ID,ROR.RIGHTS_OF_ROLE_ID) RIGHTS_OF_ROLE_ID      
  FROM FOX_TBL_USER_RIGHTS RI        
  inner JOIN FOX_TBL_RIGHTS_OF_ROLE ROR ON ROR.RIGHT_ID=RI.RIGHT_ID and isnull(ROR.deleted,0)<>1      
  inner JOIN FOX_TBL_ROLE R ON ROR.ROLE_ID=R.ROLE_ID and isnull(r.DELETED,0) = 0 and (R.PRACTICE_CODE is null or R.PRACTICE_CODE = @PRACTICE_CODE)      
  left join FOX_TBL_PRACTICE_ROLE_RIGHTS PR on PR.RIGHTS_OF_ROLE_ID=ROR.RIGHTS_OF_ROLE_ID and PR.PRACTICE_CODE=@PRACTICE_CODE  and isnull(PR.Deleted,0)<>1   
  WHERE R.ROLE_NAME= @USERROLE and  isnull(RI.Deleted,0)<>1   
END      
