IF (OBJECT_ID('FOX_PROC_GET_PSR_FEEDBACK_CALLER_NAME_LIST') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PSR_FEEDBACK_CALLER_NAME_LIST  
GO  
--01  
-- =============================================  
-- AUTHOR:  <DEVELOPER, YOUSAF>  
-- CREATE DATE: <CREATE DATE, 05/04/2018>  
-- DESCRIPTION: <GET PATIENT SURVEY REPORT; DETAILED>  
  
-- [DBO].[FOX_PROC_GET_PSR_USER_NAME_LIST_RAFAY] 1011163, 54410118  
  
CREATE PROCEDURE [DBO].[FOX_PROC_GET_PSR_FEEDBACK_CALLER_NAME_LIST] --1011163, ''  
 (  
 @PRACTICE_CODE BIGINT,  
 @ROLE_ID BIGINT  
 --,@SEARCH_TEXT VARCHAR(100)  
 )  
AS  
BEGIN  
 IF OBJECT_ID('TEMPDB..#TEMP_TBL_PS_USER') IS NOT NULL  
  DROP TABLE #TEMP_TBL_PS_USER  
  
 SELECT CASE               
     WHEN ISNULL(LAST_NAME, '') = '' THEN ISNULL(FIRST_NAME, '')              
     ELSE ISNULL(LAST_NAME, '') + ', ' + ISNULL(FIRST_NAME, '')              
     END AS FULL_NAME  
  ,LAST_NAME  
  ,FIRST_NAME  
  ,USER_NAME  
 INTO #TEMP_TBL_PS_USER  
 FROM FOX_TBL_APPLICATION_USER  
 WHERE ROLE_ID = @ROLE_ID   
     AND ISNULL(DELETED, 0) = 0  
  AND PRACTICE_CODE = @PRACTICE_CODE  
  
 SELECT *  
 FROM #TEMP_TBL_PS_USER  
 --WHERE USER_NAME LIKE '%' + @SEARCH_TEXT + '%'  
 ORDER BY USER_NAME  
END  
