IF (OBJECT_ID('FOX_PROC_GET_PATIENT_PENDING_BALANCE') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PATIENT_PENDING_BALANCE  
GO
CREATE PROCEDURE FOX_PROC_GET_PATIENT_PENDING_BALANCE    
@PATIENT_ACCOUNT BIGINT          
AS          
 BEGIN        
IF OBJECT_ID('TEMPDB.DBO.#NUMBER_OF_DAYS', 'U') IS NOT NULL DROP TABLE #NUMBER_OF_DAYS;         
IF OBJECT_ID('TEMPDB.DBO.#STATEMENT_HISTORY', 'U') IS NOT NULL DROP TABLE #STATEMENT_HISTORY;         
      
DECLARE @CLAIMS_AMOUNT_DUE DECIMAL(8, 2)      
DECLARE @NoOfDays INT      
DECLARE @AMOUNT DECIMAL(8, 2)      
      
 SET @CLAIMS_AMOUNT_DUE = (SELECT SUM(amt_due) AS Patient_Balance       
 FROM claims         
 WHERE patient_account = @PATIENT_ACCOUNT       
         AND isnull(claims.deleted, 0) = 0         
        AND pat_status IN('N', 'R', 'B', 'C', 'D'))      
      
 IF(@CLAIMS_AMOUNT_DUE >= 500.00)      
  BEGIN      
   SELECT TOP 1 DATEDIFF(DAY, CONVERT(VARCHAR, PROCESS_DATE, 23), CONVERT(VARCHAR, GETDATE(), 23)) AS CALCULATED_DIFF, PROCESS_DATE      
   INTO #NUMBER_OF_DAYS      
   FROM PATIENT_STATEMENT_HISTORY      
   WHERE PATIENT_ACCOUNT = @PATIENT_ACCOUNT  AND SUBMISSION_TYPE = 'PAT'      
   ORDER BY PROCESS_DATE DESC      
   SET @NoOfDays = (SELECT CALCULATED_DIFF FROM  #NUMBER_OF_DAYS)      
      
   IF(@NoOfDays > 45)      
    BEGIN      
     SELECT AMOUNT, CLAIM_NO, PROCESS_DATE, S_NO      
        INTO #STATEMENT_HISTORY      
     FROM PATIENT_STATEMENT_HISTORY       
     WHERE PATIENT_ACCOUNT = @PATIENT_ACCOUNT AND PROCESS_DATE = (SELECT PROCESS_DATE FROM  #NUMBER_OF_DAYS)      
     --GROUP BY CLAIM_NO, AMOUNT, PROCESS_DATE      
     ORDER BY S_NO DESC      
      
     SELECT @AMOUNT = (SELECT Sum(AMOUNT) AS TOTAL_AMOUNT FROM #STATEMENT_HISTORY)       
      
     IF(@AMOUNT >= 500.00)      
      BEGIN      
       SELECT TOP 1 @AMOUNT AS Statement_Patient_Balance, @CLAIMS_AMOUNT_DUE AS Patient_Balance, CONVERT(VARCHAR, PROCESS_DATE, 103) AS PROCESS_DATE, @NoOfDays AS NoOfDays      
       FROM #STATEMENT_HISTORY      
      END      
    END      
  END      
      
 ELSE      
  BEGIN      
   PRINT @CLAIMS_AMOUNT_DUE      
  END      
      
END 