IF (OBJECT_ID('FOX_PROC_INSERT_WORK_FILES_FROM_SERVICE') IS NOT NULL ) DROP PROCEDURE FOX_PROC_INSERT_WORK_FILES_FROM_SERVICE  
GO 
CREATE Procedure [dbo].[FOX_PROC_INSERT_WORK_FILES_FROM_SERVICE] 
(
@FILE_ID bigint,
 @WORK_ID BIGINT,
 @UNIQUE_ID varchar(50),
 @FILE_PATH1 varchar(max),
 @FILE_PATH varchar(max)

)
AS
BEGIN
SET NOCOUNT ON;

insert into FOX_TBL_WORK_QUEUE_File_All(FILE_ID,UNIQUE_ID,FILE_PATH,FILE_PATH1,deleted,WORK_ID)
values(@FILE_ID,@UNIQUE_ID,@FILE_PATH,@FILE_PATH1,0,@WORK_ID)
--values(@FILE_ID,@UNIQUE_ID,replace(@FILE_PATH,'\','/'),replace(@FILE_PATH1,'\','/'),0,@WORK_ID)
END

