IF (OBJECT_ID('FOX_PROC_GET_REFERRAL_REGION_BY_ORDERING_REF_SOURCE_ID') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_REFERRAL_REGION_BY_ORDERING_REF_SOURCE_ID  
GO   
--7  
  
--EXEC [FOX_PROC_GET_REFERRAL_REGION_BY_ORDERING_REF_SOURCE_ID] 54838934, 1011163    
CREATE PROCEDURE [FOX_PROC_GET_REFERRAL_REGION_BY_ORDERING_REF_SOURCE_ID]   
@ORDERING_REF_SOURCE_ID BIGINT,   
@PRACTICE_CODE          BIGINT  
AS  
SELECT RR.REFERRAL_REGION_CODE,   
       RR.REFERRAL_REGION_NAME,   
       RR.REFERRAL_REGION_ID,  
    ORS.REFERRAL_REGION  
FROM FOX_TBL_ORDERING_REF_SOURCE AS ORS  
     LEFT JOIN FOX_TBL_REFERRAL_REGION AS RR ON(RR.REFERRAL_REGION_CODE = ORS.REFERRAL_REGION  
                                                OR RR.REFERRAL_REGION_NAME = ORS.REFERRAL_REGION)  
                                               AND ISNULL(RR.DELETED, 0) = 0  
                                               AND RR.PRACTICE_CODE = @PRACTICE_CODE  
WHERE ORS.SOURCE_ID = @ORDERING_REF_SOURCE_ID  
      AND ISNULL(ORS.DELETED, 0) = 0  
      AND ORS.PRACTICE_CODE = @PRACTICE_CODE  
   AND RR.IS_INACTIVE <> 1;  
