IF (OBJECT_ID('FOX_PROC_ADD_TO_DB_FROM_RFO') IS NOT NULL ) DROP PROCEDURE FOX_PROC_ADD_TO_DB_FROM_RFO
GO 
  -- =============================================                    
-- Author:  <Author,Abdur Rafey>                    
-- Create date: <Create Date,01/11/2021>                    
-- DESCRIPTION: <ADD TO DB FROM RFO>       
CREATE PROCEDURE FOX_PROC_ADD_TO_DB_FROM_RFO(    
@PRACTICE_CODE BIGINT NULL,    
@WORK_ID BIGINT NULL,    
@USER_NAME VARCHAR(255) NULL,    
@NO_OF_PAGES INT NULL,  
@IS_FROM_INDEX_INFO BIT NULL    
)    
AS    
BEGIN    
    
--DECLARE @PRACTICE_CODE BIGINT  = 1011163,    
--@WORK_ID BIGINT  = 1012,    
--@USER_NAME VARCHAR(255) = '1163testing',    
--@NO_OF_PAGES INT = 1;    
    
UPDATE FOX_TBL_WORK_QUEUE    
SET TOTAL_PAGES = @NO_OF_PAGES,    
 FAX_ID = '',    
 MODIFIED_BY = @USER_NAME,    
 MODIFIED_DATE = GETDATE()    
    
 WHERE WORK_ID = @WORK_ID AND PRACTICE_CODE = @PRACTICE_CODE AND ISNULL(DELETED, 0) = 0    
    
 select * from fox_tbl_work_queue WHERE WORK_ID = @WORK_ID AND PRACTICE_CODE = @PRACTICE_CODE AND ISNULL(DELETED, 0) = 0    
END; 