IF (OBJECT_ID('FOX_PROC_UPDATE_FOX_PHD_CALL_FROM_SERVICE_EMPTY') IS NOT NULL ) DROP PROCEDURE FOX_PROC_UPDATE_FOX_PHD_CALL_FROM_SERVICE_EMPTY  
GO 
-- =============================================  
-- Author:  <Author,Abdur Rafey>  
-- Create date: <Create Date,06/04/2019>  
-- DESCRIPTION: <UPDATE FOX PHD RECORDING PATH FROM SERVICE EMPTY>  


--[FOX_PROC_UPDATE_FOX_PHD_CALL_FROM_SERVICE_EMPTY] '548315'

CREATE PROCEDURE [dbo].[FOX_PROC_UPDATE_FOX_PHD_CALL_FROM_SERVICE_EMPTY]
(@FOX_PHD_CALL_DETAILS_ID BIGINT,
 @PRACTICE_CODE BIGINT
)
AS
     BEGIN
         SET NOCOUNT ON;
         UPDATE FOX_TBL_PHD_CALL_DETAILS
           SET 
               CALL_RECORDING_PATH = ''
         WHERE FOX_PHD_CALL_DETAILS_ID = @FOX_PHD_CALL_DETAILS_ID
		 AND ISNULL(DELETED, 0) = 0 
		 AND PRACTICE_CODE = @PRACTICE_CODE
     END;
