IF (OBJECT_ID('FOX_PROC_DASHBOARD_GET_TOTAL') IS NOT NULL ) DROP PROCEDURE FOX_PROC_DASHBOARD_GET_TOTAL
GO
CREATE PROCEDURE [dbo].[FOX_PROC_DASHBOARD_GET_TOTAL] --1011163
	@PRACTICE_CODE BIGINT
AS
BEGIN
	DECLARE @receive_date DATETIME = getdate();

	SELECT (
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND CHARINDEX('_', UNIQUE_ID) = 0
				AND ISNULL(DELETED, 0) = 0
				AND FOX_TBL_WORK_QUEUE.PRACTICE_CODE = @PRACTICE_CODE
			) AS actual
		,(
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND CHARINDEX('_', UNIQUE_ID) > 0
				AND ISNULL(DELETED, 0) = 0
				AND FOX_TBL_WORK_QUEUE.PRACTICE_CODE = @PRACTICE_CODE
			) AS splits
		,(
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND IS_EMERGENCY_ORDER = 1
				AND ISNULL(DELETED, 0) = 0
				AND FOX_TBL_WORK_QUEUE.PRACTICE_CODE = @PRACTICE_CODE
			) AS emergencyOrder
		,(
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND ASSIGNED_TO IS NOT NULL
				AND COMPLETED_BY IS NULL
				AND ISNULL(DELETED, 0) = 0
				AND FOX_TBL_WORK_QUEUE.PRACTICE_CODE = @PRACTICE_CODE
			) AS assign
		,(
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND ASSIGNED_TO IS NULL
				AND COMPLETED_BY IS NULL
				AND ISNULL(DELETED, 0) = 0
				AND FOX_TBL_WORK_QUEUE.PRACTICE_CODE = @PRACTICE_CODE
			) AS unassign
		,(
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND COMPLETED_BY IS NOT NULL
				AND ISNULL(DELETED, 0) = 0
				AND FOX_TBL_WORK_QUEUE.PRACTICE_CODE = @PRACTICE_CODE
			) AS compeleted
		,
		--(select COUNT(*) from FOX_TBL_WORK_QUEUE where CAST(RECEIVE_DATE AS date) = CAST(@receive_date AS date) and WORK_STATUS = 'indexed') as indexed,  
		(
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE WQ
			JOIN fox_tbl_application_user AU ON wq.ASSIGNED_TO = au.user_name
			LEFT JOIN fox_tbl_role tr ON au.ROLE_ID = tr.ROLE_ID
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND tr.ROLE_ID = 101
				AND COMPLETED_BY IS NULL
				AND WORK_STATUS = 'indexed'
				AND ISNULL(WQ.DELETED, 0) = 0
				AND WQ.PRACTICE_CODE = @PRACTICE_CODE
			) AS indexed
		,(
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE WQ
			JOIN fox_tbl_application_user AU ON wq.ASSIGNED_TO = au.user_name
			LEFT JOIN fox_tbl_role tr ON au.ROLE_ID = tr.ROLE_ID
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND tr.ROLE_ID = 100
				AND COMPLETED_BY IS NULL
				AND ISNULL(WQ.DELETED, 0) = 0
				AND WQ.PRACTICE_CODE = @PRACTICE_CODE
			) AS assinged_to_agent
		,(
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE WQ
			JOIN fox_tbl_application_user AU ON wq.ASSIGNED_TO = au.user_name
			LEFT JOIN fox_tbl_role tr ON au.ROLE_ID = tr.ROLE_ID
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND tr.ROLE_ID = 101
				AND COMPLETED_BY IS NULL
				AND WORK_STATUS <> 'indexed'
				AND ISNULL(WQ.DELETED, 0) = 0
				AND WQ.PRACTICE_CODE = @PRACTICE_CODE
			) AS assinged_to_indexers
		,(
			SELECT COUNT(*)
			FROM FOX_TBL_WORK_QUEUE WQ
			LEFT JOIN fox_tbl_application_user AU ON wq.ASSIGNED_TO = au.user_name
			LEFT JOIN fox_tbl_role tr ON au.ROLE_ID = tr.ROLE_ID
			WHERE CAST(RECEIVE_DATE AS DATE) = CAST(@receive_date AS DATE)
				AND tr.ROLE_ID = 102
				AND COMPLETED_BY IS NULL
				AND ISNULL(WQ.DELETED, 0) = 0
				AND WQ.PRACTICE_CODE = @PRACTICE_CODE
			) AS assinged_to_super
END

