IF (OBJECT_ID('FOX_PROC_GET_TOTAL_PAGES') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_TOTAL_PAGES  
GO 

CREATE PROCEDURE [dbo].[FOX_PROC_GET_TOTAL_PAGES]
(
	@WORK_ID BIGINT,
	@PRACTICE_CODE BIGINT
)
AS
BEGIN
SELECT ISNULL(TOTAL_PAGES,0) as TOTAL_PAGES FROM FOX_TBL_WORK_QUEUE
WHERE WORK_ID = @WORK_ID AND DELETED = 0 AND PRACTICE_CODE = @PRACTICE_CODE
END

