-- =============================================                          
-- AUTHOR:  <Muhammad Iqbal>                          
-- CREATE DATE: <CREATE DATE, 15/05/2023>                          
-- DESCRIPTION: <GET PATIENT EXTERNAL USER LIST>                                        
-- [dbo].[FOX_PROC_SAVE_EXTERNAL_USER_INFO] 1012714, '', '','','','','', 1012714         
ALTER PROCEDURE FOX_PROC_SAVE_EXTERNAL_USER_INFO                 
@FRICTIONLESS_UNAVAILABLE_ID BIGINT,                    
@SUBMITER_FIRST_NAME VARCHAR(50),                      
@SUBMITTER_LAST_NAME VARCHAR(50),                     
@SUBMITTER_PHONE VARCHAR(50),                     
@SUBMITTER_EMAIL VARCHAR(50),                     
@ZIP_CODE VARCHAR(50),                     
@CITY_NAME VARCHAR(50),                     
@PRACTICE_CODE  BIGINT,      
@FRICTIONLESS_REFERRAL_ID BIGINT,     
@SUBMITTER_ADDRESS VARCHAR(500),     
@SUBMITTER_STATE VARCHAR(2),         
@OPERATION VARCHAR(5)                     
AS BEGIN      
IF(@OPERATION = 'save')         
BEGIN                 
INSERT INTO FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE                   
(FOX_FRICTIONLESS_UNAVAILABLE_ID,FIRST_NAME, LAST_NAME,PHONE_NUMBER, EMAIL, ZIP_CODE,CITY_NAME,PRACTICE_CODE, FRICTIONLESS_REFERRAL_ID, ADDRESS, STATE)                    
VALUES               
(@FRICTIONLESS_UNAVAILABLE_ID,@SUBMITER_FIRST_NAME, @SUBMITTER_LAST_NAME,@SUBMITTER_PHONE, @SUBMITTER_EMAIL,@ZIP_CODE,@CITY_NAME,@PRACTICE_CODE,@FRICTIONLESS_REFERRAL_ID, @SUBMITTER_ADDRESS, @SUBMITTER_STATE)        
END      
ELSE      
BEGIN      
Update FOX_TBL_FRICTIONLESS_SERVICE_UNAVAILABLE_ZIPCODE set       
--FOX_FRICTIONLESS_UNAVAILABLE_ID = @FRICTIONLESS_UNAVAILABLE_ID      
 FIRST_NAME = @SUBMITER_FIRST_NAME      
 ,LAST_NAME = @SUBMITTER_LAST_NAME      
 ,EMAIL     = @SUBMITTER_EMAIL      
 ,ZIP_CODE = @ZIP_CODE      
 ,CITY_NAME = @CITY_NAME      
 ,PHONE_NUMBER = @SUBMITTER_PHONE      
 ,PRACTICE_CODE = @PRACTICE_CODE      
    ,FRICTIONLESS_REFERRAL_ID = @FRICTIONLESS_REFERRAL_ID     
 ,ADDRESS = @SUBMITTER_ADDRESS  
 ,STATE = @SUBMITTER_STATE     
 where       
 FOX_FRICTIONLESS_UNAVAILABLE_ID = @FRICTIONLESS_UNAVAILABLE_ID      
END      
                        
END 

