IF (OBJECT_ID('FOX_PROC_SET_USER_INVALID_LOGIN_ATTEMPTS') IS NOT NULL ) DROP PROCEDURE FOX_PROC_SET_USER_INVALID_LOGIN_ATTEMPTS  
GO 
-- =============================================    
-- Author:  <Author,,Name>    
-- Create date: <Create Date,,>    
-- Description: <Description,,>    
-- =============================================    
-- FOX_PROC_SET_USER_INVALID_LOGIN_ATTEMPTS '1163TESTING'    
CREATE PROCEDURE [dbo].[FOX_PROC_SET_USER_INVALID_LOGIN_ATTEMPTS]    
 -- Add the parameters for the stored procedure here    
 @USER_NAME NVARCHAR(100)    
AS    
BEGIN    
 DECLARE @MAX_ID BIGINT    
 SET @MAX_ID = (SELECT ISNULL(MAX(INVALID_USER_COUNT_ID), 500100) FROM FOX_TBL_INVALID_USER_ATTEMPTS)    
      
     
 IF EXISTS(SELECT * FROM FOX_TBL_INVALID_USER_ATTEMPTS WHERE USER_NAME = @USER_NAME)    
 BEGIN    
  UPDATE FOX_TBL_INVALID_USER_ATTEMPTS    
   SET FAIL_ATTEMPT_COUNT = FAIL_ATTEMPT_COUNT + 1,    
   MODIFIED_DATE = GETDATE()    
  WHERE USER_NAME = @USER_NAME    
    
  SELECT * FROM FOX_TBL_INVALID_USER_ATTEMPTS WHERE USER_NAME = @USER_NAME    
 END    
 ELSE    
 BEGIN    
  INSERT INTO FOX_TBL_INVALID_USER_ATTEMPTS(INVALID_USER_COUNT_ID,USER_NAME,FAIL_ATTEMPT_COUNT, CREATED_DATE, MODIFIED_DATE)    
           VALUES(@MAX_ID + 1, @USER_NAME, 1, GETDATE(), GETDATE())    
    
  SELECT * FROM FOX_TBL_INVALID_USER_ATTEMPTS WHERE INVALID_USER_COUNT_ID = @MAX_ID    
    
 END    
    
END 

