IF (OBJECT_ID('FOX_PROC_INSERT_RECONCILIATION_UPLOAD_LOG') IS NOT NULL ) DROP PROCEDURE FOX_PROC_INSERT_RECONCILIATION_UPLOAD_LOG  
GO 
CREATE PROCEDURE [dbo].[FOX_PROC_INSERT_RECONCILIATION_UPLOAD_LOG]  
 @PRACTICE_CODE BIGINT,  
 @TOTAL_RECORDS BIGINT,  
 @USER_NAME VARCHAR(70),  
 @RECORD_INSERTED BIGINT  
AS        
BEGIN        
 DECLARE @LOG_ID BIGINT                            
   SET @LOG_ID = (SELECT ISNULL(MAX(ID),500100) FROM FOX_TBL_RECONCILIATION_UPLOAD_LOG)                            
                            
   INSERT INTO FOX_TBL_RECONCILIATION_UPLOAD_LOG (ID, LAST_UPDATED_DATE, TOTAL_RECORDS,CREATED_DATE, CREATED_BY, MODIFIED_BY, MODIFIED_DATE, PRACTICE_CODE, SUCCESSFULLY_ADDED)                            
           VALUES(@LOG_ID+1, GETDATE(), @TOTAL_RECORDS, GETDATE(), @USER_NAME, @USER_NAME, GETDATE(), @PRACTICE_CODE, @RECORD_INSERTED)   
END 
