IF (OBJECT_ID('FOX_PROC_GET_ROLE_RIGHTS_BY_ROLEID') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_ROLE_RIGHTS_BY_ROLEID  
GO
CREATE Procedure [dbo].[FOX_PROC_GET_ROLE_RIGHTS_BY_ROLEID] --1011163,103  
(  
 @PRACTICE_CODE bigint,  
 @ROLE_ID bigint  
)  
AS  
BEGIN  
SET NOCOUNT ON;  
SELECT R.ROLE_ID,ROLE_NAME,RI.RIGHT_ID,RI.RIGHT_NAME,ISNULL(PR.RIGHTS_OF_ROLE_ID,ROR.RIGHTS_OF_ROLE_ID) RIGHTS_OF_ROLE_ID,Convert(bit,0) IS_CHECKED  
  FROM FOX_TBL_USER_RIGHTS RI    
  inner JOIN FOX_TBL_RIGHTS_OF_ROLE ROR ON ROR.RIGHT_ID=RI.RIGHT_ID   
  inner JOIN FOX_TBL_ROLE R ON ROR.ROLE_ID=R.ROLE_ID AND R.ROLE_ID=@ROLE_ID and (R.PRACTICE_CODE is null or R.PRACTICE_CODE = @PRACTICE_CODE)  
  inner join FOX_TBL_PRACTICE_ROLE_RIGHTS PR on PR.RIGHTS_OF_ROLE_ID=ROR.RIGHTS_OF_ROLE_ID and PR.PRACTICE_CODE=@PRACTICE_CODE and isnull(PR.CHECKED,0)=1  
  
  where ISNULL(R.DELETED, 0) = 0   
  AND ISNULL(RI.DELETED, 0) = 0   
END 