IF (OBJECT_ID('FOX_PROC_GET_PHD_SERVICE_SUMMARY') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PHD_SERVICE_SUMMARY  
GO  
CREATE PROCEDURE [dbo].[FOX_PROC_GET_PHD_SERVICE_SUMMARY]          
(@PRACTICE_CODE BIGINT        
,@DATE VARCHAR(20))          
AS          
BEGIN          
    
DECLARE @TOTAL_CALLS VARCHAR(5)    
DECLARE @MAPPED_CALLS VARCHAR(5)    
DECLARE @UNMAPPED_CALLS VARCHAR(5)    
DECLARE @DUPLICATE_CALLS VARCHAR(5)    
    
--SELECT INCOMING_CALL_NO,CALL_RECORDING_PATH,* FROM FOX_TBL_PHD_CALL_DETAILS    
--WHERE    
--cast(CALL_DATE as date) = '01/03/2020'    
--AND PRACTICE_CODE = 1011163    
--AND DELETED = 0    
    
SELECT @TOTAL_CALLS = COUNT(*) FROM FOX_TBL_PHD_CALL_DETAILS    
WHERE    
cast(CALL_DATE as date) = @DATE    
AND PRACTICE_CODE = 1012714    
AND DELETED = 0    
    
SELECT @MAPPED_CALLS = COUNT(*) FROM FOX_TBL_PHD_CALL_DETAILS    
WHERE    
cast(CALL_DATE as date) = @DATE    
AND PRACTICE_CODE = 1012714    
AND DELETED = 0    
AND ISNULL(CALL_RECORDING_PATH, '') <> ''    
    
SELECT @UNMAPPED_CALLS = COUNT(*) FROM FOX_TBL_PHD_CALL_DETAILS    
WHERE    
cast(CALL_DATE as date) = @DATE    
AND PRACTICE_CODE = 1012714    
AND DELETED = 0    
AND ISNULL(CALL_RECORDING_PATH, '') = ''    
    
SELECT  @DUPLICATE_CALLS = COUNT(*)  FROM FOX_TBL_PHD_CALL_UNMAPPED    
WHERE    
cast(CALL_DATE as date) = @DATE    
AND PRACTICE_CODE = 1012714    
AND DELETED = 0    
    
SELECT @TOTAL_CALLS As TOTAL_CALLS , @MAPPED_CALLS AS MAPPED_CALLS, @UNMAPPED_CALLS AS UNMAPPED_CALLS, @DUPLICATE_CALLS AS DUPLICATE_CALLS    
END;
