IF (OBJECT_ID('FOX_PROC_GET_MTBC_INSURANCES_LIST') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_MTBC_INSURANCES_LIST  
GO  
--=============================================  
 --AUTHOR:  <DEVELOPER, YOUSAF>  
 --CREATE DATE: <CREATE DATE,30/11/2018>  
 --DESCRIPTION: <GET MTBC INSURANCES LIST>  
 --=============================================   
 --FOX_PROC_GET_MTBC_INSURANCES_LIST NULL, '', NULL, '', '', 500691, '', '', '', '', '', '', '', '', '', '', '', 1 , 10  
CREATE PROCEDURE [dbo].[FOX_PROC_GET_MTBC_INSURANCES_LIST]     
(      
  @PAYER_ID BIGINT,  
  @PAYER_DESCRIPTION VARCHAR(100),  
  @INS_NAME_ID BIGINT,  
  @INSURANCE_NAME VARCHAR(100),  
  @GROUP_NAME VARCHAR(100),  
  @INSURANCE_ID BIGINT,  
  @INSURANCE_ADDRESS VARCHAR(200),  
  @ZIP VARCHAR(10),  
  @CITY VARCHAR(20),  
  @STATE VARCHAR(5),  
  @INSURANCE_STATE VARCHAR(5),  
  @PAYER_STATE VARCHAR(5),  
  @DEPARTMENT VARCHAR(20),  
  @EMC VARCHAR(100),  
  @PHONE VARCHAR(20),  
  @PHONE_TYPE VARCHAR(20),  
  @SEARCH_STRING VARCHAR(100),  
  @CURRENT_PAGE INT,  
  @RECORD_PER_PAGE INT  
)  
AS   
BEGIN  
  
    SET @CURRENT_PAGE = @CURRENT_PAGE - 1;          
    DECLARE @START_FROM INT= @CURRENT_PAGE * @RECORD_PER_PAGE;  
    DECLARE @TOATL_PAGESUDM FLOAT;  
  
 SELECT @TOATL_PAGESUDM = COUNT(*)          
    FROM INSURANCE_GROUPS IG  
    INNER JOIN INSURANCE_NAMES INA ON IG.INSGROUP_ID = INA.INSGROUP_ID  
    INNER JOIN INSURANCE_PAYERS IP ON INA.INSNAME_ID = IP.INSNAME_ID  
    INNER JOIN INSURANCES I ON IP.INSPAYER_ID = I.INSPAYER_ID  
  WHERE  
   ISNULL(IG.DELETED,0) = 0 AND  
   ISNULL(INA.DELETED,0) = 0 AND   
   ISNULL(IP.DELETED,0) = 0 AND  
   ISNULL(I.DELETED,0) = 0 AND  
   ( @PAYER_ID IS NULL OR IP.INSPAYER_ID = @PAYER_ID ) AND  
   ( @PAYER_DESCRIPTION = '' OR IP.INSPAYER_DESCRIPTION LIKE '%'+ @PAYER_DESCRIPTION +'%' ) AND  
   ( @INS_NAME_ID IS NULL OR INA.INSNAME_ID = @INS_NAME_ID ) AND  
   ( @INSURANCE_NAME = '' OR INA.INSNAME_DESCRIPTION LIKE '%'+ @INSURANCE_NAME +'%' ) AND  
   ( @GROUP_NAME = '' OR IG.INSGROUP_NAME LIKE '%'+ @GROUP_NAME +'%' ) AND  
   ( @INSURANCE_ID IS NULL OR I.INSURANCE_ID = @INSURANCE_ID ) AND  
   ( @INSURANCE_ADDRESS = '' OR I.INSURANCE_ADDRESS LIKE '%'+ @INSURANCE_ADDRESS +'%' ) AND  
   ( @ZIP = '' OR I.INSURANCE_ZIP LIKE '%'+ @ZIP +'%' ) AND  
   ( @CITY = '' OR I.INSURANCE_CITY LIKE '%'+ @CITY +'%' ) AND  
   ( @INSURANCE_STATE = '' OR I.INSURANCE_STATE LIKE '%'+ @INSURANCE_STATE +'%' ) AND  
   ( @DEPARTMENT = '' OR I.INSURANCE_DEPARTMENT LIKE '%'+ @DEPARTMENT +'%' ) AND  
   ( @EMC = '' OR IP.INSPAYER_ID = @PAYER_ID ) AND  
   ( @PHONE = '' OR I.INSURANCE_PHONE_NUMBER1 LIKE '%'+ @PHONE +'%' ) AND  
   ( @PHONE_TYPE = '' OR I.INSURANCE_PHONE_TYPE1 LIKE '%'+ @PHONE_TYPE +'%' ) AND  
   (  
    IG.INSGROUP_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR IG.INSGROUP_NAME LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_DESCRIPTION LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_PLAN LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_837_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_STATE LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR INA.INSNAME_DESCRIPTION LIKE '%'+ @SEARCH_STRING +'%'  
    OR INA.INSNAME_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_ZIP LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_CITY LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_STATE LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_ADDRESS LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_CARDCATEGORY LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_TYPE1 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_NUMBER1 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_TYPE2 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_NUMBER2 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_TYPE3 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_NUMBER3 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_DEPARTMENT LIKE '%'+ @SEARCH_STRING +'%'  
   )  
  
 IF(@RECORD_PER_PAGE = 0)  
  BEGIN  
   SET @RECORD_PER_PAGE = @TOATL_PAGESUDM;  
  END;  
 ELSE  
  BEGIN  
   SET @RECORD_PER_PAGE = @RECORD_PER_PAGE;  
  END;  
   
 DECLARE @TOTAL_RECORDS INT= @TOATL_PAGESUDM;  
 SET @TOATL_PAGESUDM = CEILING(@TOATL_PAGESUDM / @RECORD_PER_PAGE);  
  
 SELECT *,  
   @TOATL_PAGESUDM AS TOTAL_RECORD_PAGES,  
   @TOTAL_RECORDS AS TOTAL_RECORDS  
 FROM  
 (  
  SELECT  
   IG.INSGROUP_ID,  
   IG.INSGROUP_NAME,  
   IP.INSPAYER_ID,  
   IP.INSPAYER_DESCRIPTION,  
   IP.INSPAYER_PLAN,  
   IP.INSPAYER_837_ID,  
   IP.INSPAYER_STATE,  
   I.INSURANCE_ID,  
   INA.INSNAME_DESCRIPTION,  
   INA.INSNAME_ID,  
   I.INSURANCE_ZIP,  
   I.INSURANCE_CITY,  
   I.INSURANCE_STATE,  
   I.INSURANCE_ADDRESS,  
   I.INSURANCE_CARDCATEGORY,  
   I.INSURANCE_PHONE_TYPE1,  
   I.INSURANCE_PHONE_NUMBER1,  
   I.INSURANCE_PHONE_TYPE2,  
   I.INSURANCE_PHONE_NUMBER2,  
   I.INSURANCE_PHONE_TYPE3,  
   I.INSURANCE_PHONE_NUMBER3,  
   I.INSURANCE_DEPARTMENT,  
   CASE  
    WHEN INACTIVE = 1 THEN CAST(0 AS BIT)  
    ELSE CAST(1 AS BIT)  
   END AS INACTIVE  
   --ISNULL(I.INACTIVE, 0) AS INACTIVE  
  FROM INSURANCE_GROUPS IG  
    INNER JOIN INSURANCE_NAMES INA ON IG.INSGROUP_ID = INA.INSGROUP_ID  
    INNER JOIN INSURANCE_PAYERS IP ON INA.INSNAME_ID = IP.INSNAME_ID  
    INNER JOIN INSURANCES I ON IP.INSPAYER_ID = I.INSPAYER_ID  
  WHERE  
   ISNULL(IG.DELETED,0) = 0 AND  
   ISNULL(INA.DELETED,0) = 0 AND   
   ISNULL(IP.DELETED,0) = 0 AND  
   ISNULL(I.DELETED,0) = 0 AND  
   ( @PAYER_ID IS NULL OR IP.INSPAYER_ID = @PAYER_ID ) AND  
   ( @PAYER_DESCRIPTION = '' OR IP.INSPAYER_DESCRIPTION LIKE '%'+ @PAYER_DESCRIPTION +'%' ) AND  
   ( @INS_NAME_ID IS NULL OR INA.INSNAME_ID = @INS_NAME_ID ) AND  
   ( @INSURANCE_NAME = '' OR INA.INSNAME_DESCRIPTION LIKE '%'+ @INSURANCE_NAME +'%' ) AND  
   ( @GROUP_NAME = '' OR IG.INSGROUP_NAME LIKE '%'+ @GROUP_NAME +'%' ) AND  
   ( @INSURANCE_ID IS NULL OR I.INSURANCE_ID = @INSURANCE_ID ) AND  
   ( @INSURANCE_ADDRESS = '' OR I.INSURANCE_ADDRESS LIKE '%'+ @INSURANCE_ADDRESS +'%' ) AND  
   ( @ZIP = '' OR I.INSURANCE_ZIP LIKE '%'+ @ZIP +'%' ) AND  
   ( @CITY = '' OR I.INSURANCE_CITY LIKE '%'+ @CITY +'%' ) AND  
   ( @INSURANCE_STATE = '' OR I.INSURANCE_STATE LIKE '%'+ @INSURANCE_STATE +'%' ) AND  
   ( @DEPARTMENT = '' OR I.INSURANCE_DEPARTMENT LIKE '%'+ @DEPARTMENT +'%' ) AND  
   ( @EMC = '' OR IP.INSPAYER_ID = @PAYER_ID ) AND  
   ( @PHONE = '' OR I.INSURANCE_PHONE_NUMBER1 LIKE '%'+ @PHONE +'%' ) AND  
   ( @PHONE_TYPE = '' OR I.INSURANCE_PHONE_TYPE1 LIKE '%'+ @PHONE_TYPE +'%' ) AND  
   (  
    IG.INSGROUP_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR IG.INSGROUP_NAME LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_DESCRIPTION LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_PLAN LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_837_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR IP.INSPAYER_STATE LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR INA.INSNAME_DESCRIPTION LIKE '%'+ @SEARCH_STRING +'%'  
    OR INA.INSNAME_ID LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_ZIP LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_CITY LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_STATE LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_ADDRESS LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_CARDCATEGORY LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_TYPE1 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_NUMBER1 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_TYPE2 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_NUMBER2 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_TYPE3 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_PHONE_NUMBER3 LIKE '%'+ @SEARCH_STRING +'%'  
    OR I.INSURANCE_DEPARTMENT LIKE '%'+ @SEARCH_STRING +'%'  
   )  
 ) AS FOX_TBL_MTBC_INSURANCES  
   
 ORDER BY INSPAYER_DESCRIPTION  
 OFFSET @START_FROM ROWS FETCH NEXT @RECORD_PER_PAGE ROWS ONLY;  
  
END 