IF (OBJECT_ID('FOX_PROC_GET_UNMAPPED_CALLS') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_UNMAPPED_CALLS  
GO 
CREATE PROCEDURE FOX_PROC_GET_UNMAPPED_CALLS    
    
@PRACTICE_CODE BIGINT NULL,    
@CALL_DATE varchar (500) NULL,    
@CALL_NO varchar (500) NULL    
    
AS    
BEGIN    
    
SELECT      
--DATEDIFF(MINUTE, CAST(CALL_START_TIME AS TIME), CAST(CALL_END_TIME AS TIME)) AS LENGTH,*     
      
  --CAST(CALL_END_TIME - CALL_START_TIME as Time) AS LENGTH,*     
    
    RIGHT('0' + CAST(DATEDIFF(S, CALL_START_TIME, CALL_END_TIME) % 3600/60 AS VARCHAR(2)),2) + ':'    
   + RIGHT('0' + CAST(DATEDIFF(S, CALL_START_TIME, CALL_END_TIME) % 60 AS VARCHAR(2)),2) AS LENGTH,*     
    
    
    
FROM FOX_TBL_PHD_CALL_UNMAPPED     
WHERE CALL_NO = @CALL_NO    
AND PRACTICE_CODE = @PRACTICE_CODE     
AND ISNULL(DELETED, 0) = 0      
AND CAST(CALL_DATE AS DATE)       
     BETWEEN CAST(@CALL_DATE AS DATE)       
     AND CAST(@CALL_DATE AS DATE)    
    
    
END  
