IF (OBJECT_ID('FOX_GET_Work_History') IS NOT NULL) DROP PROCEDURE FOX_GET_Work_History
GO
CREATE PROCEDURE [dbo].[FOX_GET_Work_History]
(
	@UNIQUE_ID VARCHAR(100)
)
AS
BEGIN
	SELECT * FROM FOX_TBL_WORK_ORDER_HISTORY WHERE UNIQUE_ID = @UNIQUE_ID ORDER BY CREATED_ON
END
