-- AUTHOR:  <DEVELOPER, AFTAB KHAN>      
-- CREATE DATE: <CREATE DATE, 01/31/2024>  
-- MODIFIED BY:  <DEVELOPER, AFTAB KHAN>   
-- MODIFY DATE: <MODIFIED DATE, 01/02/2024>         
-- DESCRIPTION: <[FOX_PROC_DELETE_CANCELLATION_CHARGE]>   

CREATE PROCEDURE [dbo].[FOX_PROC_DELETE_CANCELLATION_CHARGE]  
   -- @PRACTICE_CODE VARCHAR(100),  
    @USER_NAME VARCHAR(100)  
AS  
BEGIN  
    -- Update records  
    UPDATE FOX_TBL_CANCEL_CHARGE_REGIONS  
    SET DELETED = 1,  
        MODIFIED_BY = @USER_NAME,  
        MODIFIED_DATE = GETDATE()  
    WHERE DELETED = 0;  
  
END  
