IF (OBJECT_ID('FOX_PROC_GET_AUDITOR_NAME_LIST') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_AUDITOR_NAME_LIST 
GO
---6
-- =============================================
-- AUTHOR:		<DEVELOPER, ABDUR RAFAY>
-- CREATE DATE: <CREATE DATE, 26/04/2018>
-- DESCRIPTION:	<GET AUDITOR NAME LIST>

--EXEC FOX_PROC_GET_AUDITOR_NAME_LIST 1011163,''

CREATE PROCEDURE [dbo].[FOX_PROC_GET_AUDITOR_NAME_LIST] 
	 @PRACTICE_CODE BIGINT,
	 @USER_NAME VARCHAR(50)
	
AS
BEGIN


	SELECT USER_NAME,FIRST_NAME + ' '+ LAST_NAME AS NAME
	FROM FOX_TBL_APPLICATION_USER
	WHERE
	     USER_NAME =  @USER_NAME
	     AND ISNULL(DELETED, 0) = 0
		 AND PRACTICE_CODE = @PRACTICE_CODE
		
	--ORDER BY USER_NAME DESC
END


