IF (OBJECT_ID('FOX_PROC_UPDATE_SURVEY_SERVICE_LAST_EXECUTION_DATE') IS NOT NULL ) DROP PROCEDURE FOX_PROC_UPDATE_SURVEY_SERVICE_LAST_EXECUTION_DATE  
GO   
CREATE PROC [dbo].[FOX_PROC_UPDATE_SURVEY_SERVICE_LAST_EXECUTION_DATE](@DATE DATE)    
AS    
     BEGIN    
         UPDATE [FOX_TBL_SURVEY_DATA_EXPORT_SERVICE_CONFIG]    
           SET     
               LAST_EXECUTION_DATE = @DATE;    
     END;  
  
