IF (OBJECT_ID('FOX_PROC_GET_USER_INTEL_TEMPL_LIST') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_USER_INTEL_TEMPL_LIST  
GO 
--5: Alter SP FOX_PROC_GET_USER_INTEL_TEMPL_LIST
CREATE PROCEDURE [dbo].[FOX_PROC_GET_USER_INTEL_TEMPL_LIST] --1011163, 1011163415, 0 --0
	@PRACTICE_CODE BIGINT
	,@USER_ID BIGINT
	,@TASK_SUB_TYPE_ID INT
	--DECLARE @PRACTICE_CODE BIGINT = 1011163
	--	,@USER_ID BIGINT = 1011163415
	--	,@TASK_SUB_TYPE_ID INT = 544100 --0 --544100
AS
BEGIN
	SELECT tst.TASK_SUB_TYPE_ID
		,tst.NAME AS TASK_SUB_TYPE_NAME
		,A.*
	FROM FOX_TBL_TASK_SUB_TYPE AS tst
	CROSS APPLY (
		SELECT itc.INTEL_TASK_CATEGORY_ID
			,itc.NAME AS CATEGORY_NAME
			,itf.INTEL_TASK_FIELD_ID
			,itf.NAME AS FIELD_NAME
			,ISNULL(tst_itf.IS_REQUIRED, 0) AS IS_REQUIRED
			,tst_itf.TASK_SUB_TYPE_INTEL_TASK_FIELD_ID
		FROM FOX_TBL_INTEL_TASK_CATEGORY AS itc
		INNER JOIN FOX_TBL_INTEL_TASK_FIELD AS itf ON itf.INTEL_TASK_CATEGORY_ID = itc.INTEL_TASK_CATEGORY_ID
			AND ISNULL(itf.DELETED, 0) = 0
			AND itf.PRACTICE_CODE = @PRACTICE_CODE
		LEFT JOIN FOX_TBL_TASK_SUB_TYPE_INTEL_TASK_FIELD AS tst_itf ON tst_itf.INTEL_TASK_FIELD_ID = itf.INTEL_TASK_FIELD_ID
			AND tst.TASK_SUB_TYPE_ID = tst_itf.TASK_SUB_TYPE_ID
			AND ISNULL(tst_itf.DELETED, 0) = 0
			AND tst_itf.PRACTICE_CODE = @PRACTICE_CODE
		LEFT JOIN (
			SELECT DISTINCT TASK_SUB_TYPE_INTEL_TASK_FIELD_ID
			FROM FOX_TBL_TASKSUBTYPE_REFSOURCE_MAPPING
			WHERE ISNULL(DELETED, 0) = 0
				AND PRACTICE_CODE = @PRACTICE_CODE
			) AS tst_rs_m ON tst_rs_m.TASK_SUB_TYPE_INTEL_TASK_FIELD_ID = tst_itf.TASK_SUB_TYPE_INTEL_TASK_FIELD_ID
		WHERE ISNULL(itc.DELETED, 0) = 0
			AND itc.PRACTICE_CODE = @PRACTICE_CODE
		) A
	WHERE (
			@TASK_SUB_TYPE_ID = 0
			OR tst.TASK_SUB_TYPE_ID = @TASK_SUB_TYPE_ID
			)
		AND ISNULL(tst.DELETED, 0) = 0
		AND tst.PRACTICE_CODE = @PRACTICE_CODE
		AND (
			@TASK_SUB_TYPE_ID = 0
			AND A.TASK_SUB_TYPE_INTEL_TASK_FIELD_ID IS NOT NULL
			AND IS_REQUIRED = 1
			OR @TASK_SUB_TYPE_ID <> 0
			)
END

