IF (OBJECT_ID('FOX_PROC_GET_PHD_PATIENT_DETAILS') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PHD_PATIENT_DETAILS  
GO 
CREATE PROCEDURE [dbo].[FOX_PROC_GET_PHD_PATIENT_DETAILS]        
@USERID INT                   
AS                  
BEGIN                    
SELECT LTRIM(RTRIM(P.First_Name)) AS firstName,               
P.Last_Name AS lastName,               
AU.FIRST_NAME + ' ' + AU.LAST_NAME AS CALL_ATTENDED_BY_NAME,               
convert(varchar, DY.DOCUMENT_TYPE_ID, 101) AS DOCUMENT_TYPE,              
DY.NAME AS DOCUMENT_TYPE_NAME,              
PDFA.DOCUMENT_PATH AS ATTACHMENT_NAME,                  
*                   
FROM PATIENT AS P                    
INNER JOIN FOX_TBL_PHD_CALL_DETAILS AS PCD ON P.Patient_Account = PCD.PATIENT_ACCOUNT                    
JOIN FOX_TBL_APPLICATION_USER AS AU ON PCD.CALL_ATTENDED_BY = AU.USER_ID                  
LEFT JOIN FOX_TBL_PATIENT_PAT_DOCUMENT PD ON PD.FOX_PHD_CALL_DETAILS_ID = PCD.FOX_PHD_CALL_DETAILS_ID                                                
LEFT JOIN FOX_TBL_DOCUMENT_TYPE DY ON DY.DOCUMENT_TYPE_ID = PD.DOCUMENT_TYPE                     
LEFT JOIN FOX_TBL_PATIENT_PAT_DOCUMENT AS PPD ON PPD.FOX_PHD_CALL_DETAILS_ID = PCD.FOX_PHD_CALL_DETAILS_ID              
LEFT JOIN FOX_TBL_PATIENT_DOCUMENT_FILE_ALL AS PDFA ON PDFA.PAT_DOCUMENT_ID = PPD.PAT_DOCUMENT_ID         
WHERE PCD.DELETED = 0 AND PCD.FOLLOW_UP_DATE !='' AND AU.USER_ID = @USERID            
ORDER BY PCD.Created_Date DESC                    
END; 