IF (OBJECT_ID('FOX_PROC_GET_TASK_APPLICATION_USER_LIST') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_TASK_APPLICATION_USER_LIST  
GO 
-- =============================================  
-- AUTHOR:  <DEVELOPER, YOUSAF>  
-- CREATE DATE: <CREATE DATE, 05/19/2018>  
-- DESCRIPTION: <GET TASK APPLICATION USER; LIST OF TASK APPLICATION USER>  
  
CREATE PROCEDURE [dbo].[FOX_PROC_GET_TASK_APPLICATION_USER_LIST] --1011163, 54425652  
(  
 @PRACTICE_CODE BIGINT,  
 @TASK_ID BIGINT  
)  
AS  
BEGIN  
  
 SELECT TAU.*, AU.FIRST_NAME AS USER_FNAME, AU.LAST_NAME AS USER_LNAME, AU.EMAIL AS USER_EMAIL, convert(bit, 1) AS IS_ACTIVE  
 FROM FOX_TBL_TASK_APPLICATION_USER TAU  
   --LEFT JOIN FOX_TBL_TASK T ON TAU.TASK_ID = t.TASK_ID  
   LEFT JOIN FOX_TBL_APPLICATION_USER AU ON TAU.USER_ID = AU.USER_ID  
 WHERE ISNULL(TAU.DELETED, 0) = 0  
   AND TAU.PRACTICE_CODE = @PRACTICE_CODE  
   AND TAU.TASK_ID = @TASK_ID  
END 