IF (OBJECT_ID('FOX_PROC_DELETE_REC_FROM_MTBC_CREDENTIALS') IS NOT NULL ) DROP PROCEDURE FOX_PROC_DELETE_REC_FROM_MTBC_CREDENTIALS
GO
----------------------------------------SP_HELPTEXT FOX_PROC_DELETE_REC_FROM_MTBC_CREDENTIALS----------------------  
  -- EXEC [DBO].[FOX_PROC_DELETE_REC_FROM_MTBC_CREDENTIALS] 1012714,'A'  
CREATE PROCEDURE FOX_PROC_DELETE_REC_FROM_MTBC_CREDENTIALS        
@PRACTICE_CODE  BIGINT,          
@DATATYPE VARCHAR(50)        
AS          
BEGIN          
           
 DELETE FROM FOX_TBL_MTBC_CREDENTIALS_AUTOMATION         
  WHERE  DATA_TYPE = @DATATYPE         
  And PRACTICE_CODE = @PRACTICE_CODE        
END 