IF (OBJECT_ID('FOX_PROC_GET_RANDOM_PATIENT_SURVEY') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_RANDOM_PATIENT_SURVEY  
GO
-- =============================================              
-- AUTHOR:  <DEVELOPER, YOUSAF>              
-- CREATE DATE: <CREATE DATE, 06/23/2018>              
-- DESCRIPTION: <GET RANDOM PATIENT SURVEY>              
              
--[DBO].[FOX_PROC_GET_RANDOM_PATIENT_SURVEY] 1012714 ,'07/20/2021','08/20/2021'              
--[DBO].[FOX_PROC_GET_RANDOM_PATIENT_SURVEY] 1012714 ,'07/21/2021','08/20/2021'              
CREATE PROCEDURE [DBO].[FOX_PROC_GET_RANDOM_PATIENT_SURVEY] --1011163            
 @PRACTICE_CODE BIGINT,            
 @DATE_FROM       DATETIME,               
    @DATE_TO         DATETIME            
AS            
BEGIN            
 SELECT TOP 1  SURVEY_STATUS_CHILD,   
 CASE  
 WHEN   
   (SL.IS_SMS = 1 OR SL.IS_EMAIL = 1) AND DATEDIFF(DAY, SL.MODIFIED_DATE, GETDATE()) < 15  THEN 'AUTOMATED SURVEY'  
   ELSE 'MANUAL SURVEY'  
 END AS SurveyCategory,  
 CONVERT(VARCHAR, SL.MODIFIED_DATE, 120) AS SurveyTime,  
 CASE  
   WHEN COALESCE(SL.IS_EMAIL, 0) = 1 AND COALESCE(SL.IS_SMS, 0) = 1 THEN 'SMS and Email'  
   WHEN COALESCE(SL.IS_SMS, 0) = 1 THEN 'SMS'  
   WHEN COALESCE(SL.IS_EMAIL, 0) = 1 THEN 'Email'   
   ELSE ''  
END AS SurveyMethod,   
 *   
  ,CONVERT(INT, ROUND(DATEDIFF(hour, PATIENT_DATE_OF_BIRTH, GETDATE()) / 8766.0, 0)) AS PATIENT_AGE          
 FROM FOX_TBL_PATIENT_SURVEY PS WITH (NOLOCK)     
 left join FOX_TBL_SURVEY_AUTOMATION_SERVICE_LOG SL WITH (NOLOCK) on  SL.PATIENT_ACCOUNT = '00'+ PS.PATIENT_ACCOUNT_NUMBER and ISNULL(IS_PERFORMED_SURVEY,0) = 0  
 WHERE ISNULL(PS.DELETED, 0) = 0            
  AND ISNULL(PS.IN_PROGRESS, 0) = 0            
  AND PS.PRACTICE_CODE = @PRACTICE_CODE            
  --AND ISNULL(IS_SURVEYED, 0) = 0            
  AND CONVERT(DATE, PS.CREATED_DATE) BETWEEN CONVERT(DATE, @DATE_FROM) AND CONVERT(DATE, @DATE_TO)           
  AND (PS.SURVEY_STATUS_CHILD = 'Callback' or ISNULL(PS.SURVEY_STATUS_CHILD,'') = '')          
 ORDER BY NEWID()            
END 