IF (OBJECT_ID('FOX_PROC_INSERT_UPDATE_DIAGNOSIS_INFO') IS NOT NULL ) DROP PROCEDURE FOX_PROC_INSERT_UPDATE_DIAGNOSIS_INFO  
GO   
-- =============================================      
-- Author:  <Muhammad Imran>      
-- Create date: <09/25/2019>      
-- Description: <Description,,>      
-- =============================================      
    
CREATE PROCEDURE FOX_PROC_INSERT_UPDATE_DIAGNOSIS_INFO      
 @PAT_DIAG_ID BIGINT NULL,      
 @WORK_ID BIGINT NULL,      
 @DIAG_CODE VARCHAR(20) NULL,      
 @PATIENT_ACCOUNT BIGINT NULL,      
 @DIAG_DESC VARCHAR(255) NULL,      
 @USER_NAME VARCHAR(70) NULL     
      
AS      
BEGIN      
 DECLARE @ID BIGINT       
       
 IF ISNULL(@PAT_DIAG_ID,0) <> 0 AND ISNULL(@PATIENT_ACCOUNT,0) <> 0 AND EXISTS (SELECT TOP 1 * FROM FOX_TBL_PATIENT_DIAGNOSIS WITH (NOLOCK) WHERE PAT_DIAG_ID = @PAT_DIAG_ID AND ISNULL(DELETED,0) = 0)      
 BEGIN      
 -- UPDATE HERE      
  --DECLARE @PROC_ID BIGINT = (SELECT TOP 1 PAT_PROC_ID FROM FOX_TBL_PATIENT_PROCEDURE WHERE WORK_ID = @WORK_ID AND ISNULL(DELETED,0) = 0)      
  UPDATE FOX_TBL_PATIENT_DIAGNOSIS       
   SET WORK_ID = @WORK_ID,      
    DIAG_CODE = @DIAG_CODE,      
    PATIENT_ACCOUNT = @PATIENT_ACCOUNT,      
    DIAG_DESC = @DIAG_DESC,      
    MODIFIED_BY = @USER_NAME,      
    MODIFIED_DATE = GETDATE(),       
    ISNULL(DELETED, 0) = 0    
  WHERE PAT_DIAG_ID = @PAT_DIAG_ID     
 END      
 ELSE      
 BEGIN      
  EXEC DBO.Web_PROC_GetColumnMaxID_Changed 'PAT_DIAG_ID', @ID output      
      
  INSERT INTO FOX_TBL_PATIENT_DIAGNOSIS (PAT_DIAG_ID, WORK_ID, DIAG_CODE, PATIENT_ACCOUNT, DIAG_DESC, CREATED_BY, CREATED_DATE, MODIFIED_BY,  MODIFIED_DATE, DELETED)      
          VALUES (@ID, @WORK_ID, @DIAG_CODE, @PATIENT_ACCOUNT, @DIAG_DESC, @USER_NAME, GETDATE(), @USER_NAME, GETDATE(), 0)      
      
      
 END       
END   
  