
-- =============================================                  
-- AUTHOR:  MUHAMMAD SALMAN                  
-- CREATE DATE: 03-22-2023                  
-- DESCRIPTION: THIS SP IS TRIGGER TO GET DETAILS OF CASE_TRATEMENT_TEAM                  
-- =============================================                                 
--FOX_PROC_GET_CASE_TRATEMENT_TEAM 1012714,1012714534318092901    
CREATE PROCEDURE FOX_PROC_GET_CASE_TRATEMENT_TEAM --1012714,1012714534318092901    
(    
@PRACTICE_CODE BIGINT,    
@PATIENT_ACCOUNT BIGINT    
)    
AS     
BEGIN    
SELECT TT.*,    
CASE     
WHEN ISNULL(FTP1.LAST_NAME,'')='' THEN FTP1.FIRST_NAME    
ELSE FTP1.LAST_NAME + ', ' + FTP1.FIRST_NAME    
END AS TREATING_PROVIDER,    
CASE     
WHEN ISNULL(FTP2.LAST_NAME,'')='' THEN FTP2.FIRST_NAME    
ELSE FTP2.LAST_NAME + ', ' + FTP2.FIRST_NAME    
END AS CASE_PROVIDER    
FROM     
FOX_TBL_CASE_TREATMENT_TEAM TT WITH(NOLOCK)     
LEFT JOIN FOX_TBL_PROVIDER FTP1 WITH(NOLOCK) ON FTP1.FOX_PROVIDER_ID = TT.TREATING_PROVIDER_ID    
         AND ISNULL(FTP1.DELETED,0)=0    
         AND FTP1.PRACTICE_CODE = @PRACTICE_CODE    
LEFT JOIN FOX_TBL_PROVIDER FTP2 WITH(NOLOCK) ON FTP2.FOX_PROVIDER_ID = TT.CASE_PROVIDER_ID    
         AND ISNULL(FTP2.DELETED,0)=0    
         AND FTP2.PRACTICE_CODE = @PRACTICE_CODE    
WHERE     
ISNULL(TT.DELETED,0)=0    
AND TT.PRACTICE_CODE = @PRACTICE_CODE    
AND TT.PATIENT_ACCOUNT = @PATIENT_ACCOUNT    
END