IF (OBJECT_ID('FOX_PROC_GET_USER') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_USER  
GO 
-- =============================================
-- Author:		<Author,Mehmood ul Hassan>
-- Create date: <Create Date,12/10/2017>
-- Description:	<get user on every call>
CREATE PROCEDURE [dbo].[FOX_PROC_GET_USER] @USERNAME VARCHAR(255)
AS
BEGIN
	SET NOCOUNT ON;
	SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED

	--SELECT USER_ID,PRACTICE_CODE,USER_NAME,PASSWORD,PASSWORD_CHANGED_DATE,FIRST_NAME,LAST_NAME,USER_DISPLAY_NAME,
	--DESIGNATION,DATE_OF_BIRTH,EMAIL,RESET_PASS,SECURITY_QUESTION,SECURITY_QUESTION_ANSWER  
	--,LOCKEDBY,LAST_LOGIN_DATE,FAILED_PASSWORD_ATTEMPT_COUNT,
	--COMMENTS ,PASS_RESET_CODE,ACTIVATION_CODE,IS_ACTIVE,
	--CREATED_DATE,CREATED_BY,MODIFIED_DATE,MODIFIED_BY,DELETED,ROLE_ID,IS_ADMIN,MANAGER_ID,isnull(USER_TYPE,'Internal') as USER_TYPE, 
	-- isnull(SENDER_TYPE,'') as SENDER_TYPE, isnull(PRACTICE_NAME, '') as PRACTICE_NAME,  isnull(NPI, '') as NPI
	--, HOME_PHONE, WORK_PHONE, FAX, LANGUAGE, TIME_ZONE, TERMINATION_DATE, GENDER, SIGNATURE_PATH
	SELECT *
	FROM FOX_TBL_APPLICATION_USER
	WHERE EMAIL = @USERNAME
		OR USER_NAME = @USERNAME
END

