IF (OBJECT_ID('FOX_PROC_GET_PHD_CALL_HISTORY_DETAILS') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PHD_CALL_HISTORY_DETAILS  
GO   
CREATE PROCEDURE [dbo].[FOX_PROC_GET_PHD_CALL_HISTORY_DETAILS] -- 1011163, 605124                            
@PRACTICE_CODE BIGINT,          
@FOX_PHD_CALL_DETAILS_ID BIGINT                      
AS                                  
BEGIN                                  
 SELECT DISTINCT CLH.PHD_CALL_LOG_ID, CLH.FOX_PHD_CALL_DETAILS_ID, CLH.PATIENT_ACCOUNT, CLH.PRACTICE_CODE,         
 CLH.CALL_DETAILS, CLH.FOLLOW_UP_DATE, CLH.CREATED_DATE FROM         
 FOX_TBL_PHD_CALL_LOG_HISTORY AS CLH        
 INNER JOIN FOX_TBL_PHD_CALL_DETAILS AS PCD ON CLH.FOX_PHD_CALL_DETAILS_ID = @FOX_PHD_CALL_DETAILS_ID        
 WHERE ISNULL(PCD.DELETED, 0) = 0 AND PCD.PRACTICE_CODE = @PRACTICE_CODE        
 ORDER BY CLH.PHD_CALL_LOG_ID DESC        
END; 