IF (OBJECT_ID('FOX_PROC_GET_APPLICATION_USERS_NAME ') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_APPLICATION_USERS_NAME 
GO   
-- =============================================  
-- AUTHOR:  <DEVELOPER, YOUSAF>  
-- CREATE DATE: <CREATE DATE, 03/30/2018>  
-- DESCRIPTION: <GET APPLICATION USERS NAME LIST>  
CREATE PROCEDURE [dbo].[FOX_PROC_GET_APPLICATION_USERS_NAME] --1011163, ''    
 (  
 @PRACTICE_CODE BIGINT  
 ,@SEARCH_NAME VARCHAR(100)  
 )  
AS  
BEGIN  
 IF OBJECT_ID('TEMPDB..#TEMP_TABLE_FOX_TBL_APPLICATION_USER') IS NOT NULL  
  DROP TABLE #TEMP_TABLE_FOX_TBL_APPLICATION_USER  
  
 SELECT FIRST_NAME  
  ,LAST_NAME  
  ,(LAST_NAME + ', ' + FIRST_NAME) AS Full_NAME  
  ,(FIRST_NAME + ', ' + LAST_NAME) AS Full_NAME2  
  ,(LAST_NAME + ' ' + FIRST_NAME) AS Full_NAME3  
  ,(FIRST_NAME + ' ' + LAST_NAME) AS Full_NAME4  
 INTO #TEMP_TABLE_FOX_TBL_APPLICATION_USER  
 FROM FOX_TBL_APPLICATION_USER  
 WHERE ISNULL(DELETED, 0) = 0  
  AND ISNULL(IS_ACTIVE, 1) = 1  
  AND PRACTICE_CODE = @PRACTICE_CODE  
  
 SELECT TOP (10) *  
 FROM #TEMP_TABLE_FOX_TBL_APPLICATION_USER  
 WHERE FIRST_NAME LIKE '%' + @SEARCH_NAME + '%'  
  OR LAST_NAME LIKE '%' + @SEARCH_NAME + '%'  
  OR Full_NAME LIKE '%' + @SEARCH_NAME + '%'  
  OR Full_NAME2 LIKE '%' + @SEARCH_NAME + '%'  
  OR Full_NAME3 LIKE '%' + @SEARCH_NAME + '%'  
  OR Full_NAME4 LIKE '%' + @SEARCH_NAME + '%'  
END  
