IF (OBJECT_ID('FOX_PROC_INSERT_CLIENT_EXPERIENCE_SERVICE_LOG') IS NOT NULL ) DROP PROCEDURE FOX_PROC_INSERT_CLIENT_EXPERIENCE_SERVICE_LOG  
GO 
-- [FOX_PROC_INSERT_CLIENT_EXPERIENCE_SERVICE_LOG] '1011163', '', '', 'Green'        
CREATE PROCEDURE  [dbo].[FOX_PROC_INSERT_CLIENT_EXPERIENCE_SERVICE_LOG]        
@PRACTICE_CODE BIGINT,        
@DATE_TO DATETIME,        
@DATE_FROM DATETIME,        
@SURVEY_FLAG VARCHAR(15)        
AS        
BEGIN        
 DECLARE @TOTAL_CALLS INT              
 SET    @TOTAL_CALLS = 0;          
         
 DECLARE @LOG_ID BIGINT        
        
 SET @LOG_ID = (SELECT ISNULL(MAX(FOX_TBL_ClIENT_EXPERIENCE_LOG_ID), 50100) FROM FOX_TBL_CLIENT_EXPERIENCE_SERVICE_LOG)        
       
 SELECT @TOTAL_CALLS = COUNT(*) FROM FOX_TBL_PATIENT_SURVEY AS PS      
 INNER JOIN FOX_TBL_PATIENT_SURVEY_CALL_LOG AS CL ON CL.SURVEY_ID = PS.SURVEY_ID          
 WHERE CONVERT(DATE, PS.MODIFIED_DATE) BETWEEN CONVERT(DATE, @DATE_FROM) AND CONVERT(DATE, @DATE_TO)       
 AND SURVEY_FLAG = @SURVEY_FLAG              
 AND PS.PRACTICE_CODE = @PRACTICE_CODE       
 AND REGION <> ''      
 AND PS.DELETED = 0              
       
 IF(@SURVEY_FLAG = 'Green')      
 BEGIN      
  INSERT INTO FOX_TBL_CLIENT_EXPERIENCE_SERVICE_LOG(FOX_TBL_ClIENT_EXPERIENCE_LOG_ID, SURVEY_FLAG, SURVEY_ID_COUNT, IS_SUCCESSFUL, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, DELETED)        
  VALUES(@LOG_ID + 1, @SURVEY_FLAG, @TOTAL_CALLS, 1, 'FOX SURVEY SERVICE - MONTHLY', GETDATE(),  'FOX SURVEY SERVICE - MONTHLY', GETDATE(), 0)       
 END      
 ELSE      
 BEGIN      
 INSERT INTO FOX_TBL_CLIENT_EXPERIENCE_SERVICE_LOG(FOX_TBL_ClIENT_EXPERIENCE_LOG_ID, SURVEY_FLAG, SURVEY_ID_COUNT, IS_SUCCESSFUL, CREATED_BY, CREATED_DATE, MODIFIED_BY, MODIFIED_DATE, DELETED)        
 VALUES(@LOG_ID + 1, @SURVEY_FLAG, @TOTAL_CALLS, 1, 'FOX SURVEY SERVICE - WEEKLY', GETDATE(),  'FOX SURVEY SERVICE - WEEKLY', GETDATE(), 0)       
 END      
END
