IF (OBJECT_ID('FOX_PROC_INSERT_LOG') IS NOT NULL ) DROP PROCEDURE FOX_PROC_INSERT_LOG  
GO 
CREATE PROCEDURE [dbo].[FOX_PROC_INSERT_LOG]  
(
 @LOG_ID BIGINT,
 @WORK_ID BIGINT,
 @LOG_MESSAGE nvarchar(max),
 @CREATED_BY nvarchar(100)
)
AS 
BEGIN                
                 
 INSERT INTO FOX_TBL_WORK_ORDER_HISTORY(LOG_ID,WORK_ID,UNIQUE_ID,LOG_MESSAGE,	CREATED_BY,	CREATED_ON)
 VALUES(@LOG_ID, @WORK_ID,convert(varchar(100),@WORK_ID), @LOG_MESSAGE, @CREATED_BY, GETDATE())            
         
END   
