-- =============================================                                                  
-- AUTHOR:  <DEVELOPER, TASEER IQBAL>                                                  
-- CREATE DATE: <CREATE DATE, 12/24/2022>                                                  
-- DESCRIPTION:  THIS PROCEDURE IS USE TO GET PROVIDER DETAILS                                            
-- =============================================          
CREATE PROCEDURE FOX_PROC_GET_PROVIDER_DETAILS_BY_NPI(      
@PROVIDER_NPI VARCHAR(20),      
@PRACTICE_CODE BIGINT      
)      
AS      
BEGIN      
SELECT TAXONOMY.DESCRIPTION , PROVIDER.INDIVIDUAL_NPI,PROVIDER.FIRST_NAME, PROVIDER.LAST_NAME,PROVIDER.ADDRESS,PROVIDER.CITY,PROVIDER.STATE,PROVIDER.ZIP,PROVIDER.REGION_NAME,PROVIDER.REGION_CODE,  
PROVIDER.FAX,PROVIDER.PHONE  
FROM FOX_TBL_PROVIDER PROVIDER WITH (NOLOCK)     
INNER JOIN TAXONOMY_CODES TAXONOMY  WITH (NOLOCK)     
ON PROVIDER.TAXONOMY_CODE = TAXONOMY.TAXONOMY_CODES      
WHERE       
PROVIDER.INDIVIDUAL_NPI = @PROVIDER_NPI      
AND PROVIDER.PRACTICE_CODE = @PRACTICE_CODE      
AND ISNULL(PROVIDER.DELETED,0)= 0    
END 