-- =============================================    
-- AUTHOR:  MUHAMMAD ARSLAN TUFAIL    
-- CREATE DATE: 07/26/2022    
-- DESCRIPTION: THIS PROCEDURE IS TRIGGER TO GET ACTIVE CATEGORT CREDENTIALS    
-- =============================================    
-- [FOX_PROC_GET_ACTIVE_CATEGORY_DESCRIPTION_CREDENTIAL] 1012714  
CREATE PROCEDURE [FOX_PROC_GET_ACTIVE_CATEGORY_DESCRIPTION_CREDENTIAL]    
@PRACTICE_CODE BIGINT    
    
AS    
BEGIN    
 SELECT [NAME] FROM     
 FOX_TBL_HR_AUTOEMAILS_CONFIGURE_ATTACHMENTS    
 WHERE ISNULL(DELETED, 0) = 0 AND PRACTICE_CODE = @PRACTICE_CODE    
 AND IS_ENABLED = 1    
END    