IF (OBJECT_ID('FOX_PROC_GET_HR_AUTOEMAILS_UPLOAD_LOG') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_HR_AUTOEMAILS_UPLOAD_LOG 
GO   
------------------------------------------SP_HELPTEXT FOX_PROC_GET_HR_AUTOEMAILS_UPLOAD_LOG------------------------   
CREATE PROCEDURE FOX_PROC_GET_HR_AUTOEMAILS_UPLOAD_LOG-- '1011163', 'StudentPlacement'      
@PRACTICE_CODE BIGINT ,      
@DATA_TYPE VARCHAR(50)        
AS        
     DECLARE @TOTAL_RECORDSE BIGINT;        
     BEGIN        
         SET @TOTAL_RECORDSE =        
         (        
             SELECT COUNT(*) AS rec        
             FROM FOX_TBL_MTBC_CREDENTIALS_AUTOMATION        
    WHERE PRACTICE_CODE = @PRACTICE_CODE AND DATA_TYPE = @DATA_TYPE      
      
         );        
         SELECT TOP 1 CREATED_DATE AS LAST_UPLOAD_DATE,@TOTAL_RECORDSE AS RECORDS_ADDED_SUCCESSFULLY,*        
         FROM FOX_TBL_MTBC_CREDENTIALS_AUTOMATION        
         WHERE PRACTICE_CODE = @PRACTICE_CODE AND DATA_TYPE = @DATA_TYPE      
         ORDER BY CREATED_DATE DESC;           
     END; 