IF (OBJECT_ID('FOX_PROC_GET_RECONCILIATION_CATEGORIES') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_RECONCILIATION_CATEGORIES  
GO         
CREATE PROCEDURE [DBO].[FOX_PROC_GET_RECONCILIATION_CATEGORIES](@PRACTICE_CODE BIGINT)          
AS          
     BEGIN          
         SELECT *          
         FROM dbo.FOX_TBL_RECONCILIATION_CATEGORY ftrc          
         WHERE ISNULL(ftrc.DELETED,0) = 0 AND ftrc.PRACTICE_CODE = @PRACTICE_CODE;          
     END;          
