IF (OBJECT_ID('FOX_PROC_GET_GUEST_LOGIN') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_GUEST_LOGIN 
GO   
-- =============================================  
-- AUTHOR:  <DEVELOPER, YOUSAF>  
-- CREATE DATE: <CREATE DATE, 06/04/2018>  
-- DESCRIPTION: <GET GUEST LOGIN; GET GUEST LOGIN BY WORK ID>  
CREATE PROCEDURE [dbo].[FOX_PROC_GET_GUEST_LOGIN] --1011163, 12121  
 (  
 @PRACTICE_CODE BIGINT  
 ,@WORK_ID BIGINT  
 )  
AS  
BEGIN  
 SELECT WS.*  
 FROM FOX_TBL_WORK_QUEUE WQ  
 INNER JOIN WS_TBL_FOX_GUEST_LOGIN WS ON WQ.GUESTID = WS.GUESTID  
 WHERE WQ.WORK_ID = @WORK_ID  
END  
