IF (OBJECT_ID('FOX_GET_INDEX_INFO_DIAGNOSIS') IS NOT NULL) DROP PROCEDURE FOX_GET_INDEX_INFO_DIAGNOSIS
GO
CREATE PROCEDURE [dbo].[FOX_GET_INDEX_INFO_DIAGNOSIS] --544105
	(@WORK_ID BIGINT)
AS
BEGIN
	SELECT PAT_DIAG_ID
		,DIAG_CODE
		,DIAG_DESC
	FROM FOX_TBL_PATIENT_DIAGNOSIS
	WHERE work_id = @WORK_ID
		AND isnull(DELETED, 0) = 0
	ORDER BY PAT_DIAG_ID DESC
END

