IF (OBJECT_ID('FOX_GET_PROVIDER_LOCATION') IS NOT NULL ) DROP PROCEDURE FOX_GET_PROVIDER_LOCATION  
GO 
     -- =============================================                                          
-- AUTHOR:  <DEVELOPER, JOHAR>                                          
-- CREATE DATE: <CREATE DATE, 11/21/2018>                                          
-- DESCRIPTION: <GET FOX FOX_TBL_GET_PROVIDER_LOCATION LIST>                                                                          
 --   FOX_GET_PROVIDER_LOCATION 'EP',5481756,1011163  
  
Create PROCEDURE  [dbo].[FOX_GET_PROVIDER_LOCATION]  
(  
@PROVIDER_TYPE VARCHAR(10),  
@FOX_PROVIDER_ID BIGINT,  
@PRACTICE_CODE BIGINT  
)  
  
AS   
BEGIN  
  
IF(@PROVIDER_TYPE = 'PT')  
BEGIN  
 SELECT TOP(1) LOC_ID, NAME AS TREATMENT_LOCATION, CODE FROM FOX_TBL_ACTIVE_LOCATIONS  WHERE   
 PT_PROVIDER_ID = @FOX_PROVIDER_ID AND ISNULL(DELETED,0) = 0 AND PRACTICE_CODE = @PRACTICE_CODE   
END  
IF(@PROVIDER_TYPE = 'OT')  
BEGIN  
 SELECT TOP(1) LOC_ID, NAME AS TREATMENT_LOCATION, CODE FROM FOX_TBL_ACTIVE_LOCATIONS  WHERE   
 OT_PROVIDER_ID = @FOX_PROVIDER_ID AND ISNULL(DELETED,0) = 0 AND PRACTICE_CODE = @PRACTICE_CODE  
END  
IF(@PROVIDER_TYPE = 'ST')  
BEGIN  
 SELECT TOP(1) LOC_ID, NAME AS TREATMENT_LOCATION, CODE FROM FOX_TBL_ACTIVE_LOCATIONS  WHERE   
 ST_PROVIDER_ID = @FOX_PROVIDER_ID  AND ISNULL(DELETED,0) = 0 AND PRACTICE_CODE = @PRACTICE_CODE  
END  
IF(@PROVIDER_TYPE = 'EP')  
BEGIN  
 SELECT TOP(1) LOC_ID, NAME AS TREATMENT_LOCATION, CODE FROM FOX_TBL_ACTIVE_LOCATIONS  WHERE   
 EP_PROVIDER_ID = @FOX_PROVIDER_ID   AND ISNULL(DELETED,0) = 0 AND PRACTICE_CODE = 1011163  
END  
  
END  


