IF (OBJECT_ID('FOX_PROC_GET_PS_REGION_LIST') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PS_REGION_LIST  
GO   
-- =============================================
-- AUTHOR:		<DEVELOPER, YOUSAF>
-- CREATE DATE: <CREATE DATE, 05/03/2018>
-- DESCRIPTION:	<GET REGION LIST>
CREATE PROCEDURE [dbo].[FOX_PROC_GET_PS_REGION_LIST] --1011163,''
	(
	@PRACTICE_CODE BIGINT
	,@SEARCH_TEXT VARCHAR(100)
	)
AS
BEGIN
	SELECT DISTINCT TOP (10) REGION
	FROM FOX_TBL_PATIENT_SURVEY
	WHERE ISNULL(DELETED, 0) = 0
		AND PRACTICE_CODE = @PRACTICE_CODE
		AND REGION LIKE '%' + @SEARCH_TEXT + '%'
END

