-- =============================================  
-- Author:  Muhammad Arslan Tufail  
-- Create date: 01/06/2023  
-- Description: This procedure is trigger to get inbound calls of survey  
-- =============================================  
  
-- FOX_PROC_GET_SURVEY_INBOUND_CALL_DETAILS 151870, 1012714  
Create PROCEDURE FOX_PROC_GET_SURVEY_INBOUND_CALL_DETAILS   
 -- Add the parameters for the stored procedure here
 @PATIENT_ACCOUNT BIGINT ,  
 @PRACTICE_CODE BIGINT    
 --declare @PATIENT_ACCOUNT BIGINT = 151870,  
 --@PRACTICE_CODE BIGINT=1012714  
AS  
BEGIN  
IF OBJECT_ID('TEMPDB.DBO.#TempinBoudCalls', 'U') IS NOT NULL DROP TABLE #TempinBoudCalls;   
 SELECT   
 IC.SURVEY_INBOUND_CALL_ID,  
 PS.PATIENT_ACCOUNT_NUMBER,  
 PS.SERVICE_OR_PAYMENT_DESCRIPTION,  
 IC.CALL_DATE,  
 IC.CALL_START_TIME,  
 IC.CALL_END_TIME,
 IC.CALL_NO,  
 IC.CALL_BY,  
 IC.OFFICE_NAME,  
 IC.CALL_RECORDING_PATH  into #TempinBoudCalls
 FROM FOX_TBL_PATIENT_SURVEY_INBOUND_CALL AS IC WITH (NOLOCK)  
 INNER JOIN FOX_TBL_PATIENT_SURVEY AS PS WITH (NOLOCK) ON IC.CALL_NO = REPLACE(PS.PATIENT_TELEPHONE_NUMBER, '-', '')  
 WHERE PS.PRACTICE_CODE = @PRACTICE_CODE AND ISNULL(PS.DELETED, 0) = 0 AND  PS.PATIENT_ACCOUNT_NUMBER = @PATIENT_ACCOUNT  
 select  SURVEY_INBOUND_CALL_ID,  
 PATIENT_ACCOUNT_NUMBER,  
 SERVICE_OR_PAYMENT_DESCRIPTION,  
CALL_DATE,  
 CALL_START_TIME,  
CALL_END_TIME,  
    RIGHT('0' + CAST(DATEDIFF(SECOND, CALL_START_TIME, CALL_END_TIME) % 3600/60 AS VARCHAR(2)),2) + ':'    
   + RIGHT('0' + CAST(DATEDIFF(SECOND, CALL_START_TIME, CALL_END_TIME) % 60 AS VARCHAR(2)),2) AS CALL_DURATION,     
 CALL_NO,  
 CALL_BY,  
 OFFICE_NAME,  
 CALL_RECORDING_PATH from #TempinBoudCalls
END 