IF (OBJECT_ID('FOX_PROC_GET_RECONCILIATION_STATUSES') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_RECONCILIATION_STATUSES  
GO 
CREATE PROCEDURE [DBO].[FOX_PROC_GET_RECONCILIATION_STATUSES](@PRACTICE_CODE BIGINT)          
AS          
     BEGIN          
         SELECT *          
         FROM dbo.FOX_TBL_RECONCILIATION_STATUS ftrs          
         WHERE ISNULL(ftrs.DELETED,0) = 0 AND ftrs.PRACTICE_CODE = @PRACTICE_CODE;          
     END;          
