IF (OBJECT_ID('FOX_PROC_SET_PRACTICE_ROLE_RIGHTS') IS NOT NULL ) DROP PROCEDURE FOX_PROC_SET_PRACTICE_ROLE_RIGHTS  
GO   
-- Author:  <Author,Mehmood ul Hassan>  
-- Create date: <Create Date,12/10/2017>  
-- DESCRIPTION: <GET ROLE FOR DROPDOWN>  
CREATE Procedure [dbo].[FOX_PROC_SET_PRACTICE_ROLE_RIGHTS] --1011163,54410087  
(  
 @PRACTICE_CODE BIGINT,  
 @ROLE_ID bigint  
)  
AS  
BEGIN  
SET NOCOUNT ON;  
begin tran  
DECLARE @MAX_RIGHT_OF_ROLEID BIGINT   
SELECT @MAX_RIGHT_OF_ROLEID=MAX(RIGHTS_OF_ROLE_ID) FROM FOX_TBL_RIGHTS_OF_ROLE  
DECLARE @CREATED_BY VARCHAR(50)  
DECLARE @CREATED_DATE DATETIME  
SELECT @CREATED_BY=CREATED_BY,@CREATED_DATE=CREATED_DATE FROM FOX_TBL_ROLE WHERE ROLE_ID=@ROLE_ID and FOX_TBL_ROLE.PRACTICE_CODE = @PRACTICE_CODE  
  
  
INSERT INTO FOX_TBL_RIGHTS_OF_ROLE( RIGHTS_OF_ROLE_ID,RIGHT_ID,ROLE_ID,CREATED_BY,CREATED_DATE,MODIFIED_BY,MODIFIED_DATE,DELETED)  
SELECT @MAX_RIGHT_OF_ROLEID+ROWNUM ,RIGHT_ID,@ROLE_ID,@CREATED_BY,@CREATED_DATE,@CREATED_BY,@CREATED_DATE,0  
FROM (SELECT ROW_NUMBER() OVER(ORDER BY RIGHT_ID) AS ROWNUM, RIGHT_ID  
 FROM FOX_TBL_USER_RIGHTS) AS ROLE_OF_RIGHT  
  
 commit  
END  
  
--------------------------------------------------------------------------------------  
