IF (OBJECT_ID('FOX_PROC_GET_SURVEY_SERCVICE_CONFIG') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_SURVEY_SERCVICE_CONFIG  
GO   
   CREATE PROCEDURE [dbo].[FOX_PROC_GET_SURVEY_SERCVICE_CONFIG]      
AS      
     BEGIN      
         SET NOCOUNT ON;      
         SELECT * FROM FOX_TBL_SURVEY_DATA_EXPORT_SERVICE_CONFIG WHERE deleted = 0;      
     END;  
