IF (OBJECT_ID('FOX_TBL_GET_WORK_ID') IS NOT NULL ) DROP PROCEDURE FOX_TBL_GET_WORK_ID  
GO   
CREATE procedure FOX_TBL_GET_WORK_ID @WORK_ID BIGINT, @PRACTICE_CODE BIGINT      
AS      
BEGIN      
 select WORK_STATUS AS WORK_STATUS      
 FROM FOX_TBL_WORK_QUEUE       
 WHERE WORK_ID = @WORK_ID      
 AND PRACTICE_CODE = @PRACTICE_CODE      
 AND ISNULL(DELETED,0) = 0      
END   
  
