IF (OBJECT_ID('FOX_PROC_GET_PATIENT_SURVEY_CALL_LOG_LIST') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PATIENT_SURVEY_CALL_LOG_LIST  
GO   
-- =============================================
-- AUTHOR:		<DEVELOPER, YOUSAF>
-- CREATE DATE: <CREATE DATE, 07/07/2018>
-- DESCRIPTION:	<GET PATIENT SURVEY CALL LOG LIST>
CREATE PROCEDURE [dbo].[FOX_PROC_GET_PATIENT_SURVEY_CALL_LOG_LIST] --1011163, 101116354448952, 112235828
	@PRACTICE_CODE BIGINT
	,@SURVEY_ID BIGINT
	,@PATIENT_ACCOUNT BIGINT
AS
BEGIN
	SELECT SURVEY_CALL_ID
		,PRACTICE_CODE
		,ACU_CALL_ID
		,SURVEY_ID
		,PATIENT_ACCOUNT
		,FILE_NAME
		,IS_RECEIVED
		,CALL_DURATION
		,CREATED_BY
		,CREATED_DATE
		,MODIFIED_BY
		,MODIFIED_DATE
		,DELETED
	FROM FOX_TBL_PATIENT_SURVEY_CALL_LOG
	WHERE ISNULL(DELETED, 0) = 0
		AND ISNULL(IS_RECEIVED, 0) = 1
		AND PRACTICE_CODE = @PRACTICE_CODE
		AND PATIENT_ACCOUNT = @PATIENT_ACCOUNT
	ORDER BY CREATED_DATE DESC
END

