IF (OBJECT_ID('FOX_PROC_GET_RECONCILIATION_DEPOSIT_TYPES') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_RECONCILIATION_DEPOSIT_TYPES  
GO    
CREATE PROCEDURE [DBO].[FOX_PROC_GET_RECONCILIATION_DEPOSIT_TYPES](@PRACTICE_CODE BIGINT)            
AS            
     BEGIN            
         SELECT *          
         FROM dbo.FOX_TBL_RECONCILIATION_DEPOSIT_TYPE ftrdt            
         WHERE  ISNULL(ftrdt.DELETED,0) = 0 and ftrdt.PRACTICE_CODE = @PRACTICE_CODE;            
     END; 