IF (OBJECT_ID('FOX_GET_ORDER_INFORMATION') IS NOT NULL) DROP PROCEDURE FOX_GET_ORDER_INFORMATION
GO
Create PROCEDURE [dbo].[FOX_GET_ORDER_INFORMATION] @PRACTICE_CODE BIGINT      
 ,@CASE_ID BIGINT      
AS      
BEGIN      
 SELECT ISNULL(O.ORDER_INFO_ID,0) ORDER_INFO_ID    
  ,O.PRACTICE_CODE      
  ,O.CASE_ID      
  ,O.ORDER_STATUS_ID      
  ,O.CASE_TYPE_ID      
  ,O.PRESC_PROVIDER_ID      
  ,O.EFFECTIVE_DATE      
  ,O.END_DATE      
  ,O.VISIT_PER_WEEK      
  ,O.NO_OF_WEEK      
  ,O.TOTAL_VISITS      
  , CASE WHEN S.FIRST_NAME IS NULL    
  THEN ''    
  ELSE S.FIRST_NAME + ' ' + S.LAST_NAME    
  END    
  AS PRESC_PROVIDER_NAME    
  ,OS.DESCRIPTION      
  ,S.CODE      
 FROM FOX_TBL_ORDER_INFORMATION AS O      
 JOIN FOX_TBL_ORDER_STATUS OS ON OS.ORDER_STATUS_ID = O.ORDER_STATUS_ID      
  AND ISNULL(OS.DELETED, 0) = 0      
 LEFT JOIN FOX_TBL_ORDERING_REF_SOURCE S ON S.SOURCE_ID = O.PRESC_PROVIDER_ID      
 WHERE    
   ISNULL(S.DELETED, 0) = 0      
  AND O.CASE_ID = @CASE_ID      
  AND O.PRACTICE_CODE = @PRACTICE_CODE      
  AND ISNULL(O.DELETED, 0) = 0      
END 
