 -- AUTHOR:  <DEVELOPER, AFTAB KHAN>      
-- CREATE DATE: <CREATE DATE, 01/31/2024>  
-- MODIFIED BY:  <DEVELOPER, AFTAB KHAN>   
-- MODIFY DATE: <MODIFIED DATE, 01/02/2024>                        
 --EXEC [FOX_PROC_GET_CANCELLED_REFERRAL_REGION_LIST] 1012714,'', '', '', 1, 10, 'createdDate' , 'DESC'                                             
ALTER PROCEDURE [dbo].[FOX_PROC_GET_CANCELLED_REFERRAL_REGION_LIST]             
                                          
AS   
BEGIN                       
    SELECT R.REFERRAL_REGION_CODE, R.REFERRAL_REGION_NAME, CCR.*  
FROM FOX_TBL_CANCEL_CHARGE_REGIONS CCR  WITH (NOLOCK)
LEFT JOIN FOX_TBL_REFERRAL_REGION R WITH (NOLOCK )ON CCR.REFERRAL_REGION_ID = R.REFERRAL_REGION_ID  
WHERE CCR.DELETED = 0;  
END  