IF (OBJECT_ID('FOX_PROC_GET_TASK_COMMENTS') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_TASK_COMMENTS  
GO  
CREATE PROCEDURE [dbo].[FOX_PROC_GET_TASK_COMMENTS] --1011163, 54425637  
(  
 @PRACTICE_CODE BIGINT,  
 @TASK_ID BIGINT  
)  
AS  
BEGIN  
  
 SELECT N.*, (AU.LAST_NAME + ', ' + AU.FIRST_NAME) AS CREATED_BY_FULL_NAME  
 FROM FOX_TBL_NOTES N  
   LEFT JOIN FOX_TBL_APPLICATION_USER AU ON N.CREATED_BY = AU.USER_NAME  
 WHERE ISNULL(N.DELETED, 0) = 0  
   AND N.PRACTICE_CODE = @PRACTICE_CODE  
   AND (N.TASK_ID = @TASK_ID)  
 ORDER BY CREATED_DATE DESC  
END  
