IF (OBJECT_ID('FOX_PROC_GET_PRACTICE_ROLE') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PRACTICE_ROLE  
GO
-- Author:  <Author,Mehmood ul Hassan>  
-- Create date: <Create Date,12/10/2017>  
-- DESCRIPTION: <GET ROLE FOR DROPDOWN>  
CREATE Procedure [dbo].[FOX_PROC_GET_PRACTICE_ROLE] --1011163  
(  
--PRACTICE CODE CHECK WILL BE DONE LATER  
 @PRACTICE_CODE BIGINT  
)  
AS  
BEGIN  
SET NOCOUNT ON;  
SELECT ROLE_ID,ROLE_NAME  
  FROM FOX_TBL_ROLE R WHERE ISNULL(R.DELETED,0)=0 and (R.PRACTICE_CODE is null or R.PRACTICE_CODE = @PRACTICE_CODE)
END 

