IF (OBJECT_ID('FOX_PROC_GET_PATIENT_SURVEY_LAST_UPLOAD') IS NOT NULL ) DROP PROCEDURE FOX_PROC_GET_PATIENT_SURVEY_LAST_UPLOAD  
GO
-- =============================================      
-- AUTHOR:  <DEVELOPER, YOUSAF>      
-- CREATE DATE: <CREATE DATE, 04/25/2018>      
-- DESCRIPTION: <GET PATIENT SURVEY LAST UPLOAD>            
CREATE PROCEDURE [dbo].[FOX_PROC_GET_PATIENT_SURVEY_LAST_UPLOAD] --1011163      
(      
 @PRACTICE_CODE BIGINT      
)      
AS      
BEGIN      
 DECLARE @FElE_NAME varchar(200)      
 SELECT @FElE_NAME = FILE_NAME from FOX_TBL_PATIENT_SURVEY where ISNULL(DELETED, 0) = 0 and PRACTICE_CODE = @PRACTICE_CODE order by CREATED_DATE asc      
 select *, (DATENAME(dw, CAST(DATEPART(m, CREATED_DATE) AS VARCHAR) + '/' + CAST(DATEPART(d, CREATED_DATE) AS VARCHAR) + '/' + CAST(DATEPART(yy, CREATED_DATE) AS VARCHAR))) AS DAY_NAME      
 from FOX_TBL_PATIENT_SURVEY where ISNULL(DELETED, 0) = 0 and FILE_NAME = @FElE_NAME      
END
