IF (OBJECT_ID('GET_NON_HOLD_ISSUE_LIST') IS NOT NULL ) DROP PROCEDURE GET_NON_HOLD_ISSUE_LIST  
GO 
CREATE PROCEDURE GET_NON_HOLD_ISSUE_LIST --1011163,'HOLD'    
(@PRACTICE_CODE  BIGINT,        
 @TYPE  VARCHAR(50)    
)  
AS    
     BEGIN    
  SELECT HOLD_NON_REASONS_ID, [NAME],[DESCRIPTION],[TYPE],RT_CODE  
   FROM FOX_TBL_HOLD_NON_REASONS  
   WHERE ISNULL(DELETED,0) = 0 AND [TYPE] LIKE @TYPE AND PRACTICE_CODE = @PRACTICE_CODE  
  END;  
