IF (OBJECT_ID('SYNCHED_FAILED_PATIENT_RETRY') IS NOT NULL ) DROP PROCEDURE SYNCHED_FAILED_PATIENT_RETRY  
GO 
-- =============================================        
-- Author:  <Abdur Rafay>        
-- Create date: <28/3/2019>        
-- DESCRIPTION: <SYNCHED FAILED PATIENT RETRY>      
    
 -- EXEC [SYNCHED_FAILED_PATIENT_RETRY] '1012714','101271499911707'   
CREATE PROCEDURE [dbo].[SYNCHED_FAILED_PATIENT_RETRY]    
@PRACTICE_CODE BIGINT,  
@PATIENT_ACCOUNT  VARCHAR(70)       
  
AS  
     BEGIN  
  
  SELECT *   
  FROM FOX_TBL_INTERFACE_SYNCH   
  WHERE PATIENT_ACCOUNT = @PATIENT_ACCOUNT  
     AND ISNULL(DELETED, 0) = 0  
        AND PRACTICE_CODE = @PRACTICE_CODE  
  --AND Work_ID IS NOT NULL  
  --AND TASK_ID IS NOT NULL  
  END;  
