IF (OBJECT_ID('UPDATE_CURRENT_FOLDER') IS NOT NULL ) DROP PROCEDURE UPDATE_CURRENT_FOLDER  
GO       
CREATE PROCEDURE UPDATE_CURRENT_FOLDER        
@RECORDING_NAME VARCHAR (100),        
@CURRENT_FOLDER VARCHAR (100)        
AS        
BEGIN        
UPDATE FOX_TBL_AVAYA_CALL_RECORDINGS_LOGS        
SET CURRENT_FOLDER = @CURRENT_FOLDER , Modified_date = GETDATE()        
WHERE RECORDING_NAME = @RECORDING_NAME        
END