IF (OBJECT_ID('UPDATE_FILE_INITIAL_SIZE') IS NOT NULL ) DROP PROCEDURE UPDATE_FILE_INITIAL_SIZE  
GO       
CREATE PROCEDURE UPDATE_FILE_INITIAL_SIZE        
@RECORDING_NAME VARCHAR (100),        
@INITIAL_SIZE VARCHAR (100)        
AS        
BEGIN        
UPDATE FOX_TBL_AVAYA_CALL_RECORDINGS_LOGS        
SET INITIAL_SIZE = @INITIAL_SIZE , Modified_date = GETDATE()        
WHERE RECORDING_NAME = @RECORDING_NAME        
END  
  
  