IF (OBJECT_ID('WEB_PROC_ONLYISB_VALIDATEUSERIP') IS NOT NULL ) DROP PROCEDURE WEB_PROC_ONLYISB_VALIDATEUSERIP  
GO 
-- =============================================              
-- AUTHOR:<ISRAR GHANI>
-- CREATE DATE: <02/19/2016>               
-- DESCRIPTION: <DESCRIPTION,OUTSIDE USER SHOULD NOT ACCESS (SECURELOGINTEST) PAGE>
-- =============================================               
CREATE PROCEDURE [dbo].[WEB_PROC_ONLYISB_VALIDATEUSERIP]
-- ADD THE PARAMETERS FOR THE STORED PROCEDURE HERE              
@USERNAME VARCHAR(50),              
@USERIP VARCHAR(20)              
AS              
BEGIN              
-- SET NOCOUNT ON ADDED TO PREVENT EXTRA RESULT SETS FROM              
          
-- INTERFERING WITH SELECT STATEMENTS.              
SET NOCOUNT ON;              
DECLARE @DOWNLOADID BIGINT              
DECLARE @IPADDRESS VARCHAR(20)              
DECLARE @RESULT INT              
SET @IPADDRESS = @USERIP              
SET @DOWNLOADID =256 * 256 * 256 * CAST(PARSENAME(@IPADDRESS, 4) AS FLOAT) + 256 * 256 * CAST(PARSENAME(@IPADDRESS, 3) AS FLOAT) + 256 * CAST  (PARSENAME(@IPADDRESS, 2) AS FLOAT) + CAST(PARSENAME(@IPADDRESS, 1) AS FLOAT)              
    
--TO BE USED FOR FILTERING THE BLOCKED COUNTRIES          
 SET @RESULT =(          
  SELECT COUNT(*) FROM IPCOUNTRY IPC INNER JOIN ALL_COUNTRIES AC ON IPC.COUNTRYSHORT = AC.COUNTRY_CODE          
  WHERE @DOWNLOADID BETWEEN IPFROM AND IPTO          
  AND ISNULL(DELETED, 0) <> 1          
  AND COUNTRY_FLAG = 'B'          
 )          
          
 IF(@RESULT>= 1)            
 SET @RESULT = '403'           
           
ELSE    
SELECT @RESULT = ALLOWED FROM               
( 
  SELECT COUNT(*) AS ALLOWED FROM ISBIPCOUNTRY WHERE @DOWNLOADID BETWEEN IPNUMBERFROM AND IPNUMBERTO AND IS_ACTIVE = 1              
) AS ISALLOWED              
SELECT @RESULT AS VALIDIP              
END 
