//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FOX.ExternalServices.PatientEligibilityService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Diagnostics.CodeAnalysis;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_Service", Namespace="https://realtime.mtbc.com/Service.svc")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback MTBC271ResponseOperationCompleted;
        
        private System.Threading.SendOrPostCallback MTBCResponseOperationCompleted;
        
        private System.Threading.SendOrPostCallback MTBC837StringOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        [ExcludeFromCodeCoverage]
        /// <remarks/>
        public Service() {
            this.Url = global::FOX.ExternalServices.Properties.Settings.Default.FOX_ExternalServices_PatientEligibilityService_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        [ExcludeFromCodeCoverage]
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        [ExcludeFromCodeCoverage]
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event MTBC271ResponseCompletedEventHandler MTBC271ResponseCompleted;
        
        /// <remarks/>
        public event MTBCResponseCompletedEventHandler MTBCResponseCompleted;
        
        /// <remarks/>
        public event MTBC837StringCompletedEventHandler MTBC837StringCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://realtime.mtbc.com/Service/MTBC271Response", RequestNamespace="https://realtime.mtbc.com", ResponseNamespace="https://realtime.mtbc.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string MTBC271Response([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MTBC270RequestData request, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MTBCClientAuthentication authentication) {
            object[] results = this.Invoke("MTBC271Response", new object[] {
                        request,
                        authentication});
            return ((string)(results[0]));
        }
        [ExcludeFromCodeCoverage]
        /// <remarks/>
        public void MTBC271ResponseAsync(MTBC270RequestData request, MTBCClientAuthentication authentication) {
            this.MTBC271ResponseAsync(request, authentication, null);
        }
        [ExcludeFromCodeCoverage]
        /// <remarks/>
        public void MTBC271ResponseAsync(MTBC270RequestData request, MTBCClientAuthentication authentication, object userState) {
            if ((this.MTBC271ResponseOperationCompleted == null)) {
                this.MTBC271ResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMTBC271ResponseOperationCompleted);
            }
            this.InvokeAsync("MTBC271Response", new object[] {
                        request,
                        authentication}, this.MTBC271ResponseOperationCompleted, userState);
        }
        [ExcludeFromCodeCoverage]
        private void OnMTBC271ResponseOperationCompleted(object arg) {
            if ((this.MTBC271ResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MTBC271ResponseCompleted(this, new MTBC271ResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://realtime.mtbc.com/Service/MTBCResponse", RequestNamespace="https://realtime.mtbc.com", ResponseNamespace="https://realtime.mtbc.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string MTBCResponse([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MTBC270RequestData objRequest, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MTBCData objMtbcData) {
            object[] results = this.Invoke("MTBCResponse", new object[] {
                        objRequest,
                        objMtbcData});
            return ((string)(results[0]));
        }
        [ExcludeFromCodeCoverage]
        /// <remarks/>
        public void MTBCResponseAsync(MTBC270RequestData objRequest, MTBCData objMtbcData) {
            this.MTBCResponseAsync(objRequest, objMtbcData, null);
        }
        [ExcludeFromCodeCoverage]
        /// <remarks/>
        public void MTBCResponseAsync(MTBC270RequestData objRequest, MTBCData objMtbcData, object userState) {
            if ((this.MTBCResponseOperationCompleted == null)) {
                this.MTBCResponseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMTBCResponseOperationCompleted);
            }
            this.InvokeAsync("MTBCResponse", new object[] {
                        objRequest,
                        objMtbcData}, this.MTBCResponseOperationCompleted, userState);
        }
        [ExcludeFromCodeCoverage]
        private void OnMTBCResponseOperationCompleted(object arg) {
            if ((this.MTBCResponseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MTBCResponseCompleted(this, new MTBCResponseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://realtime.mtbc.com/Service/MTBC837String", RequestNamespace="https://realtime.mtbc.com", ResponseNamespace="https://realtime.mtbc.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string MTBC837String([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MTBC837RequestData request, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] MTBCClientAuthentication authentication) {
            object[] results = this.Invoke("MTBC837String", new object[] {
                        request,
                        authentication});
            return ((string)(results[0]));
        }
        [ExcludeFromCodeCoverage]
        /// <remarks/>
        public void MTBC837StringAsync(MTBC837RequestData request, MTBCClientAuthentication authentication) {
            this.MTBC837StringAsync(request, authentication, null);
        }

        /// <remarks/>
        [ExcludeFromCodeCoverage]
        public void MTBC837StringAsync(MTBC837RequestData request, MTBCClientAuthentication authentication, object userState) {
            if ((this.MTBC837StringOperationCompleted == null)) {
                this.MTBC837StringOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMTBC837StringOperationCompleted);
            }
            this.InvokeAsync("MTBC837String", new object[] {
                        request,
                        authentication}, this.MTBC837StringOperationCompleted, userState);
        }
        [ExcludeFromCodeCoverage]
        private void OnMTBC837StringOperationCompleted(object arg) {
            if ((this.MTBC837StringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MTBC837StringCompleted(this, new MTBC837StringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        [ExcludeFromCodeCoverage]
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        [ExcludeFromCodeCoverage]
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class MTBC270RequestData {
        
        private string addressField;
        
        private string cityField;
        
        private string dateOfServiceField;
        
        private string dependentDOBField;
        
        private string dependentFirstNameField;
        
        private string dependentGenderField;
        
        private string dependentLastNameField;
        
        private string organizationNPIField;
        
        private string organizationNameField;
        
        private string organizationTypeField;
        
        private string payerIDField;
        
        private string payerNameField;
        
        private string providerFirstNameField;
        
        private string providerLastNameField;
        
        private string providerNPIField;
        
        private string providerSSNField;
        
        private string relationshipField;
        
        private string serviceTypeField;
        
        private string stateField;
        
        private string subscriberDateOfBirthField;
        
        private string subscriberDateOfDeathField;
        
        private string subscriberFirstNameField;
        
        private string subscriberGenderField;
        
        private string subscriberGroupNumberField;
        
        private string subscriberLastNameField;
        
        private string subscriberMemberIDField;
        
        private string subscriberSSNField;
        
        private string taxIDField;
        
        private string zipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string DateOfService {
            get {
                return this.dateOfServiceField;
            }
            set {
                this.dateOfServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string DependentDOB {
            get {
                return this.dependentDOBField;
            }
            set {
                this.dependentDOBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string DependentFirstName {
            get {
                return this.dependentFirstNameField;
            }
            set {
                this.dependentFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string DependentGender {
            get {
                return this.dependentGenderField;
            }
            set {
                this.dependentGenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string DependentLastName {
            get {
                return this.dependentLastNameField;
            }
            set {
                this.dependentLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string OrganizationNPI {
            get {
                return this.organizationNPIField;
            }
            set {
                this.organizationNPIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string OrganizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string OrganizationType {
            get {
                return this.organizationTypeField;
            }
            set {
                this.organizationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string PayerID {
            get {
                return this.payerIDField;
            }
            set {
                this.payerIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string PayerName {
            get {
                return this.payerNameField;
            }
            set {
                this.payerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ProviderFirstName {
            get {
                return this.providerFirstNameField;
            }
            set {
                this.providerFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ProviderLastName {
            get {
                return this.providerLastNameField;
            }
            set {
                this.providerLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ProviderNPI {
            get {
                return this.providerNPIField;
            }
            set {
                this.providerNPIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ProviderSSN {
            get {
                return this.providerSSNField;
            }
            set {
                this.providerSSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string Relationship {
            get {
                return this.relationshipField;
            }
            set {
                this.relationshipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ServiceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string SubscriberDateOfBirth {
            get {
                return this.subscriberDateOfBirthField;
            }
            set {
                this.subscriberDateOfBirthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string SubscriberDateOfDeath {
            get {
                return this.subscriberDateOfDeathField;
            }
            set {
                this.subscriberDateOfDeathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string SubscriberFirstName {
            get {
                return this.subscriberFirstNameField;
            }
            set {
                this.subscriberFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string SubscriberGender {
            get {
                return this.subscriberGenderField;
            }
            set {
                this.subscriberGenderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string SubscriberGroupNumber {
            get {
                return this.subscriberGroupNumberField;
            }
            set {
                this.subscriberGroupNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string SubscriberLastName {
            get {
                return this.subscriberLastNameField;
            }
            set {
                this.subscriberLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string SubscriberMemberID {
            get {
                return this.subscriberMemberIDField;
            }
            set {
                this.subscriberMemberIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string SubscriberSSN {
            get {
                return this.subscriberSSNField;
            }
            set {
                this.subscriberSSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string TaxID {
            get {
                return this.taxIDField;
            }
            set {
                this.taxIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class MTBC837RequestData {
        
        private string claim_noField;
        
        private bool history_UpdatedField;
        
        private bool history_UpdatedFieldSpecified;
        
        private bool iS_RTA_PAYERField;
        
        private bool iS_RTA_PAYERFieldSpecified;
        
        private string pri_Sec_Oth_TypeField;
        
        private string request_ServerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string Claim_no {
            get {
                return this.claim_noField;
            }
            set {
                this.claim_noField = value;
            }
        }

        /// <remarks/>
        [ExcludeFromCodeCoverage]
        public bool History_Updated {
            get {
                return this.history_UpdatedField;
            }
            set {
                this.history_UpdatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [ExcludeFromCodeCoverage]
        public bool History_UpdatedSpecified {
            get {
                return this.history_UpdatedFieldSpecified;
            }
            set {
                this.history_UpdatedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [ExcludeFromCodeCoverage]
        public bool IS_RTA_PAYER {
            get {
                return this.iS_RTA_PAYERField;
            }
            set {
                this.iS_RTA_PAYERField = value;
            }
        }

        /// <remarks/>
        [ExcludeFromCodeCoverage]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IS_RTA_PAYERSpecified {
            get {
                return this.iS_RTA_PAYERFieldSpecified;
            }
            set {
                this.iS_RTA_PAYERFieldSpecified = value;
            }
        }

        /// <remarks/>
        [ExcludeFromCodeCoverage]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Pri_Sec_Oth_Type {
            get {
                return this.pri_Sec_Oth_TypeField;
            }
            set {
                this.pri_Sec_Oth_TypeField = value;
            }
        }

        /// <remarks/>
        [ExcludeFromCodeCoverage]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Request_Server {
            get {
                return this.request_ServerField;
            }
            set {
                this.request_ServerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class MTBCData {
        
        private string appointmentIDField;
        
        private string claimNoField;
        
        private string clientIDField;
        
        private string clientTypeField;
        
        private string insPayerDescriptionNameField;
        
        private string insuranceIDField;
        
        private string patientAccountField;
        
        private string payerTypeField;
        
        private string serverNameField;
        
        private string userIDField;
        
        private string viewTypeField;
        
        private string insPayerIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string AppointmentID {
            get {
                return this.appointmentIDField;
            }
            set {
                this.appointmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ClaimNo {
            get {
                return this.claimNoField;
            }
            set {
                this.claimNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ClientType {
            get {
                return this.clientTypeField;
            }
            set {
                this.clientTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string InsPayerDescriptionName {
            get {
                return this.insPayerDescriptionNameField;
            }
            set {
                this.insPayerDescriptionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string InsuranceID {
            get {
                return this.insuranceIDField;
            }
            set {
                this.insuranceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string PatientAccount {
            get {
                return this.patientAccountField;
            }
            set {
                this.patientAccountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string PayerType {
            get {
                return this.payerTypeField;
            }
            set {
                this.payerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ServerName {
            get {
                return this.serverNameField;
            }
            set {
                this.serverNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ViewType {
            get {
                return this.viewTypeField;
            }
            set {
                this.viewTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string insPayerID {
            get {
                return this.insPayerIDField;
            }
            set {
                this.insPayerIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class MTBCClientAuthentication {
        
        private string clientIDField;
        
        private string passwordField;
        
        private string receiverIDField;
        
        private string userIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string ReceiverID {
            get {
                return this.receiverIDField;
            }
            set {
                this.receiverIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        [ExcludeFromCodeCoverage]
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void MTBC271ResponseCompletedEventHandler(object sender, MTBC271ResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MTBC271ResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        [ExcludeFromCodeCoverage]
        internal MTBC271ResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        [ExcludeFromCodeCoverage]
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void MTBCResponseCompletedEventHandler(object sender, MTBCResponseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MTBCResponseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        [ExcludeFromCodeCoverage]
        internal MTBCResponseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        [ExcludeFromCodeCoverage]
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void MTBC837StringCompletedEventHandler(object sender, MTBC837StringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MTBC837StringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        [ExcludeFromCodeCoverage]
        internal MTBC837StringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        [ExcludeFromCodeCoverage]
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591